/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录，成功后通过 HttpOnly Cookie 建立会话 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出登录，销毁当前会话 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前登录用户 */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户可见的项目列表 */
        get: operations["listProjects"];
        put?: never;
        /** 创建项目 */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单个项目详情（项目内页面外壳用） */
        get: operations["getProject"];
        /** 更新项目（全量字段） */
        put: operations["updateProject"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        /** 项目成员列表（含成员角色） */
        get: operations["listProjectMembers"];
        put?: never;
        /** 将用户加入项目并赋予成员角色（仅项目管理员／项目负责人） */
        post: operations["addProjectMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                userId: number;
            };
            cookie?: never;
        };
        get?: never;
        /** 调整成员角色（仅项目管理员／项目负责人） */
        put: operations["updateProjectMemberRole"];
        post?: never;
        /** 将成员移出项目（仅项目管理员／项目负责人） */
        delete: operations["removeProjectMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/objectives": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        /** 项目的 O／KR 层级列表（O 含下属 KR，按排序返回） */
        get: operations["listObjectives"];
        put?: never;
        /** 表格式批量创建 O／KR（仅项目管理员／项目负责人；整批一个事务，全部成功或全部失败） */
        post: operations["createOkrBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        /** 项目全部任务（含派生动作标志与最近一次入池审批单） */
        get: operations["listTasks"];
        put?: never;
        /** 表格式批量创建任务草稿（可选一并提交入池；KR 负责人本人创建免审直接进入未开始，AC-26） */
        post: operations["createTaskBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/submit-pool-review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 将草稿任务提交所属 KR 负责人入池审批（AC-04；退回后可修改重新提交） */
        post: operations["submitTaskPoolReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/pool-review-decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 所属 KR 负责人通过或退回入池审批（AC-04；管理员不能替代 KR 负责人） */
        post: operations["decideTaskPoolReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        /** 任务详情（AC-31／AC-34；全体项目成员可查看，操作按钮按派生权限标志出现） */
        get: operations["getTaskDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/update-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手工流转任务状态：开始执行或取消（AC-12；完成走三道审批，不在此端点） */
        post: operations["updateTaskStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        get?: never;
        /** 更新或清除任务的可选进度百分比（AC-12；系统不产生虚构百分比） */
        put: operations["updateTaskProgress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/field-changes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 编辑任务／提交关键字段修改（AC-23；草稿直接完善，KR 负责人本人免审即时生效，其余进入审批且旧值继续生效） */
        post: operations["submitFieldChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/field-changes/{changeId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
                changeId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 所属 KR 负责人通过或退回关键字段修改（AC-23；通过后拟议值生效，退回后拟议值作废） */
        post: operations["decideFieldChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/field-changes/{changeId}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
                changeId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 放弃已退回的本次变更（清除退回待处理事项） */
        post: operations["abandonFieldChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/deliverables": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 为任务新增交付物项（任务负责人／创建人／可编辑项目者；非终态任务） */
        post: operations["createDeliverable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/deliverables/{deliverableId}/candidate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
                deliverableId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登记候选交付物内容并取得预签名上传地址（任务负责人；重复调用覆盖未提交审核的候选） */
        post: operations["uploadCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/files/{fileId}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                fileId: number;
            };
            cookie?: never;
        };
        /** 取得交付物内容的预签名下载地址（全体项目成员可查看／下载当前与候选内容，§3.3） */
        get: operations["getFileDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/reviewers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        get?: never;
        /** 调整中间审核人配置（非关键字段可直接调整，§5.2.B；审核中与终态不可） */
        put: operations["setTaskReviewers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/completion-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交完成申请（AC-13；无中间审核时直接进入待 KR 终审；含全部候选交付物与提交说明） */
        post: operations["submitCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/completion-reviews/{reviewId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
                reviewId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** KR 负责人终审（AC-15／39／40）：通过则候选整体覆盖对应当前内容且旧文件永久删除、任务完成；退回则删除候选、任务回到进行中 */
        post: operations["decideCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新增输入要求并自动建立「来源任务 → 目标任务」交付物边（AC-28；任务负责人／可编辑项目者） */
        post: operations["createTaskInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/member-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 指定项目成员提供输入（AC-29）：建立「成员 → 目标任务」交付物边并生成输入请求；任务已入池时立即发站内通知，否则待入池审批通过后发送 */
        post: operations["createMemberInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/input-requests/{requestId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                requestId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 对接人同意接收（AC-30）；接收只表示承担责任，不代表输入就绪 */
        post: operations["acceptInputRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/input-requests/{requestId}/provide": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                requestId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 对接人提交内容或文件（AC-30）；提交后输入请求变为已提供，目标任务输入更新为就绪 */
        post: operations["provideInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/input-requests/{requestId}/file-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                requestId: number;
            };
            cookie?: never;
        };
        /** 输入请求已提交文件的预签名下载地址 */
        get: operations["getInputRequestFileUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/edges/{edgeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                edgeId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 解除交付物边（目标任务负责人／可编辑项目者） */
        delete: operations["removeEdge"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/edges": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        /** 项目全部交付物边（关系数据源；图谱与列表 */
        get: operations["listEdges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/blockers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 主动上报结构化卡点（AC-11）：类型、缺失输入／条件、阻塞原因、希望行动人必填 */
        post: operations["createBlocker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/blockers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        /** 项目全部结构化卡点（风险队列数据源；开放在前） */
        get: operations["listBlockers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/blockers/{blockerId}/remind": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                blockerId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 一键提醒希望行动人（AC-11）：发送带卡点上下文的站内通知 */
        post: operations["remindBlocker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/blockers/{blockerId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                blockerId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 解除卡点；处理事实保留 */
        post: operations["resolveBlocker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tasks/{taskId}/discussions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交任务讨论意见（全体项目成员含只读；提交后不可编辑或删除；通知任务负责人与被 @ 成员） */
        post: operations["createDiscussion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户的站内通知（最新在前） */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 将当前用户全部通知标记为已读 */
        post: operations["markAllNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/my-work": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        /** 我的工作五分组（AC-16）：按当前成员职责派生个人行动与等待事实 */
        get: operations["getMyWork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/task-invites": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        /** 项目内全部任务创建邀请（含派生动作标志） */
        get: operations["listTaskInvites"];
        put?: never;
        /** 邀请成员为某个 KR 创建任务（KR 负责人／项目管理员／项目负责人；可多选受邀成员） */
        post: operations["createTaskInvites"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/task-invites/{inviteId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                inviteId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤回待处理的任务创建邀请（邀请人／项目管理员／项目负责人） */
        post: operations["revokeTaskInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全部用户（用于人员选择） */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Error: {
            /** @description 机器可读错误码 */
            code: string;
            /** @description 面向用户的错误说明 */
            message: string;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        CurrentUser: {
            /** Format: int64 */
            id: number;
            username: string;
            displayName: string;
        };
        UserSummary: {
            /** Format: int64 */
            id: number;
            username: string;
            displayName: string;
        };
        /**
         * @description 项目状态（未开始／进行中／已完成／已归档），与自由文本“阶段”正交
         * @enum {string}
         */
        ProjectStatus: "not_started" | "in_progress" | "completed" | "archived";
        /**
         * @description 成员角色（项目管理员／普通成员／只读成员），见词汇表「成员角色」
         * @enum {string}
         */
        MemberRole: "admin" | "member" | "viewer";
        ProjectMember: {
            /** Format: int64 */
            userId: number;
            username: string;
            displayName: string;
            role: components["schemas"]["MemberRole"];
        };
        AddProjectMemberRequest: {
            /** Format: int64 */
            userId: number;
            role: components["schemas"]["MemberRole"];
        };
        UpdateProjectMemberRoleRequest: {
            role: components["schemas"]["MemberRole"];
        };
        /**
         * @description 风险等级（正常／预警／高风险），见词汇表「风险等级」；不由任务生命周期状态自动推导
         * @enum {string}
         */
        RiskLevel: "normal" | "warning" | "high_risk";
        KeyResult: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            objectiveId: number;
            /** @description KR 描述 */
            description: string;
            /** @description 量化指标，选填 */
            metric?: string;
            /**
             * Format: int64
             * @description KR 负责人（项目成员，选填；工作职责而非权限级别）
             */
            ownerId?: number;
            /** @description KR 负责人姓名（派生字段） */
            ownerName?: string;
            /**
             * Format: date
             * @description 周期开始日期
             */
            startDate?: string;
            /**
             * Format: date
             * @description 周期截止日期
             */
            endDate?: string;
            riskLevel: components["schemas"]["RiskLevel"];
            sortOrder: number;
            progressSummary?: components["schemas"]["ProgressSummary"];
            /** @description 预警／高风险的一行原因（派生字段；来自 KR 下任务的开放卡点，AC-05） */
            riskNote?: string;
            /** @description KR 下任务的开放卡点数量（派生字段；图谱 KR 节点展示，AC-08） */
            openBlockerCount?: number;
        };
        /** @description KR 层进度数据覆盖度（词汇表「进度数据覆盖度」）；只统计已入池且未取消的任务，平均值任务等权 */
        ProgressSummary: {
            totalTasks: number;
            filledTasks: number;
            /** @description 已填写任务的等权平均（四舍五入）；无已填任务时不返回 */
            averageProgress?: number;
        };
        UpdateTaskStatusRequest: {
            /**
             * @description 手工流转目标：开始执行（未开始／等待输入 → 进行中）或取消（非终态 → 已取消，需原因）
             * @enum {string}
             */
            status: "in_progress" | "cancelled";
            /** @description 取消原因；status 为 cancelled 时必填 */
            reason?: string;
        };
        UpdateTaskProgressRequest: {
            /** @description 省略或 null 表示清除进度，回到只展示状态 */
            progress?: number;
        };
        Objective: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            projectId: number;
            /** @description O 标题 */
            title: string;
            /** @description O 说明，选填 */
            description?: string;
            sortOrder: number;
            keyResults: components["schemas"]["KeyResult"][];
        };
        CreateKeyResultInput: {
            description: string;
            metric?: string;
            /**
             * Format: int64
             * @description KR 负责人，必须是项目成员
             */
            ownerId?: number;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
        };
        /** @description 二选一：填 title（可带 description）新建 O，或填 objectiveId 向已有 O 追加 KR（此时 keyResults 至少一条） */
        CreateOkrBatchItem: {
            /** Format: int64 */
            objectiveId?: number;
            title?: string;
            description?: string;
            keyResults?: components["schemas"]["CreateKeyResultInput"][];
        };
        CreateOkrBatchRequest: {
            items: components["schemas"]["CreateOkrBatchItem"][];
        };
        /**
         * @description 任务生命周期状态（词汇表「任务生命周期状态」）；页面主状态汇总，审批原始状态在审批单中
         * @enum {string}
         */
        TaskStatus: "draft" | "pending_pool_review" | "not_started" | "waiting_input" | "in_progress" | "pending_intermediate_review" | "pending_final_review" | "completed" | "cancelled";
        /**
         * @description 入池审批单状态（词汇表「入池审批单」）；未提交即无审批单
         * @enum {string}
         */
        PoolReviewStatus: "pending" | "approved" | "rejected";
        /** @description 任务最近一次入池审批单 */
        PoolReview: {
            status: components["schemas"]["PoolReviewStatus"];
            /** @description KR 负责人本人创建免审时由系统自动生成并标记（AC-26） */
            exempt: boolean;
            /** @description 审批意见；免审时为系统记录的免审原因 */
            opinion?: string;
            /** @description 提交人姓名（派生字段） */
            submittedByName?: string;
            /** @description 处理人姓名（派生字段） */
            decidedByName?: string;
            /** Format: date-time */
            submittedAt?: string;
            /** Format: date-time */
            decidedAt?: string;
        };
        Task: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            keyResultId: number;
            name: string;
            /**
             * Format: int64
             * @description 任务负责人
             */
            ownerId: number;
            /** @description 任务负责人姓名（派生字段） */
            ownerName: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            status: components["schemas"]["TaskStatus"];
            /** @description 任务说明，选填 */
            description?: string;
            /** @description 完成标准，选填 */
            completionCriteria?: string;
            /** @description 当前环节（词汇表「当前环节」；中文标签，派生字段） */
            currentStage: string;
            /**
             * Format: int64
             * @description 待行动人（词汇表「待行动人」；派生字段，无待行动人时不返回）
             */
            pendingActorId?: number;
            pendingActorName?: string;
            /** @description 可选进度百分比（词汇表「任务进度」）；未填写时不返回，前端只展示状态 */
            progress?: number;
            /** @description 取消原因（已取消任务保留，PRD §5.1） */
            cancelReason?: string;
            poolReview?: components["schemas"]["PoolReview"];
            /** @description 当前用户能否开始执行本任务（派生字段；负责人／可编辑项目者，未开始或等待输入时） */
            canStart: boolean;
            /** @description 当前用户能否更新本任务进度（派生字段；负责人／可编辑项目者，执行中状态） */
            canUpdateProgress: boolean;
            /** @description 当前用户能否取消本任务（派生字段；负责人／创建人／可编辑项目者，非终态） */
            canCancel: boolean;
            /** @description 最近一张需要关注的变更单（待审批＝拟议值标示，或退回未处理＝退回待处理事项）；无则不返回 */
            fieldChange?: components["schemas"]["FieldChange"];
            /** @description 交付物项名称列表（列表「预期交付物」列展示用，派生字段） */
            deliverableNames?: string[];
            /** @description 当前用户能否编辑任务／提交关键字段修改（派生字段） */
            canProposeFieldChange: boolean;
            /** @description 当前用户能否配置任务交付物项（派生字段；负责人／创建人／可编辑项目者，非终态） */
            canManageDeliverables?: boolean;
            /** @description 当前用户能否提交完成申请（派生字段；负责人，进行中且有候选内容） */
            canSubmitCompletion?: boolean;
            /** @description 当前用户能否调整中间审核人配置（派生字段；负责人／创建人／可编辑项目者，审核中与终态不可） */
            canManageReviewers?: boolean;
            /** @description 开放中的结构化卡点数量（派生字段） */
            openBlockerCount?: number;
            /** @description 当前用户能否上报卡点（派生字段；负责人／创建人／可编辑项目者，已入池执行类状态） */
            canReportBlocker?: boolean;
            /** @description 当前用户能否登记候选交付物内容（派生字段；负责人，执行类状态） */
            canUploadCandidate?: boolean;
            /** @description 当前用户能否提交本任务入池（派生字段；草稿且为创建人／负责人／可编辑项目者） */
            canSubmitPoolReview: boolean;
            /** @description 当前用户能否处理本任务的入池审批（派生字段；仅所属 KR 负责人） */
            canDecidePoolReview: boolean;
        };
        CreateTaskItem: {
            /** Format: int64 */
            keyResultId: number;
            name: string;
            /**
             * Format: int64
             * @description 任务负责人，必须是项目成员
             */
            ownerId: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** @description 预期交付物名称（选填，原型创建弹窗列）；随任务创建对应交付物项 */
            expectedDeliverable?: string;
        };
        CreateTaskBatchRequest: {
            items: components["schemas"]["CreateTaskItem"][];
            /** @description true 时保存后立即提交各自所属 KR 的入池审批（原型「提交入池审批」按钮）；KR 负责人本人创建的任务始终免审直接进入未开始 */
            submitForReview: boolean;
            /**
             * Format: int64
             * @description 通过任务创建邀请响应时携带（AC-03）；须为发给当前用户的待处理邀请，且本批至少一项任务属于邀请指定的 KR 并提交入池，成功后邀请变为已完成
             */
            taskInviteId?: number;
        };
        /** @description 任务详情抽屉数据（AC-31／AC-34）：任务事实、O／KR 归属与全部审核记录 */
        TaskDetail: {
            task: components["schemas"]["Task"];
            /** @description 所属 O 标题（派生字段） */
            objectiveTitle: string;
            /** @description 所属 KR 描述（派生字段） */
            krDescription: string;
            /** @description 入池审批记录，最新在前（词汇表「审核记录」） */
            poolReviews: components["schemas"]["PoolReview"][];
            /** @description 关键字段变更单记录，最新在前（词汇表「关键字段变更单」） */
            fieldChanges: components["schemas"]["FieldChange"][];
            /** @description 交付物项列表（含当前内容与候选审核提示，AC-32／AC-33） */
            deliverables: components["schemas"]["Deliverable"][];
            /** @description 任务讨论意见，按时间正序（AC-35／AC-36） */
            discussions: components["schemas"]["Discussion"][];
            /** @description 完成申请记录，最新在前（AC-13／AC-15／AC-38～40） */
            completionReviews: components["schemas"]["CompletionReview"][];
            /** @description 任务级中间审核人配置（或签组；提交完成申请时快照进申请） */
            reviewers: components["schemas"]["ReviewerInfo"][];
            /** @description 结构化卡点，开放在前（AC-11） */
            blockers: components["schemas"]["Blocker"][];
            /** @description 指向本任务的交付物边（必要输入与参考输入，AC-07／28） */
            inputs: components["schemas"]["DeliverableEdge"][];
            /** @description 从本任务出发的交付物边（直接下游） */
            outputs: components["schemas"]["DeliverableEdge"][];
        };
        /** @enum {string} */
        FieldChangeState: "pending" | "approved" | "rejected";
        /** @description 单个关键字段的修改前后差异（展示用字符串） */
        FieldChangeDiff: {
            /** @description 字段名（name／description／completionCriteria／ownerId／endDate） */
            field: string;
            /** @description 中文字段名（派生字段） */
            label: string;
            oldValue: string;
            newValue: string;
        };
        /** @description 关键字段变更单（词汇表）；rejected 且 resolved=false 即「退回待处理事项」 */
        FieldChange: {
            /** Format: int64 */
            id: number;
            state: components["schemas"]["FieldChangeState"];
            /** @description 修改原因 */
            reason: string;
            /** @description 审批意见 */
            opinion?: string;
            /** @description 退回后是否已处理（重新提交或放弃） */
            resolved: boolean;
            /** @description KR 负责人本人修改免审即时生效时由系统标记 */
            exempt: boolean;
            changes: components["schemas"]["FieldChangeDiff"][];
            /** Format: int64 */
            submittedById?: number;
            submittedByName?: string;
            decidedByName?: string;
            /** Format: date-time */
            submittedAt?: string;
            /** Format: date-time */
            decidedAt?: string;
            /** @description 当前用户能否处理本变更单（派生字段；仅所属 KR 负责人且待审批） */
            canDecide?: boolean;
            /** @description 当前用户能否放弃本次变更（派生字段；退回未处理且为提交人／可编辑项目者） */
            canAbandon?: boolean;
        };
        SubmitFieldChangeRequest: {
            /** @description 拟议值；至少一项。草稿任务直接生效；KR 负责人改本人 KR 下任务免审即时生效 */
            changes: {
                name?: string;
                description?: string;
                completionCriteria?: string;
                /** Format: int64 */
                ownerId?: number;
                /** Format: date */
                endDate?: string;
            };
            /** @description 修改原因；进入审批（含免审留痕）时必填，草稿直接完善可不填 */
            reason?: string;
        };
        FieldChangeDecisionRequest: {
            /** @enum {string} */
            decision: "approved" | "rejected";
            opinion?: string;
        };
        /** @description 交付物内容（词汇表「交付物」；当前已生效或候选审核中） */
        DeliverableFile: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            state: "current" | "candidate";
            fileName: string;
            fileType?: string;
            /**
             * Format: int64
             * @description 字节数
             */
            fileSize?: number;
            /** @description 提交人姓名（派生字段） */
            uploadedByName?: string;
            /** Format: date-time */
            uploadedAt?: string;
            /**
             * Format: date-time
             * @description 当前内容的生效时间（终审通过时刻）
             */
            effectiveAt?: string;
        };
        /** @description 交付物项：至多一份当前内容与一份候选内容，无版本号与历史（PRD §5.3） */
        Deliverable: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            taskId: number;
            name: string;
            current?: components["schemas"]["DeliverableFile"];
            /** @description 审核中的候选内容；任务概况只提示不展示内容（AC-33） */
            candidate?: components["schemas"]["DeliverableFile"];
        };
        CreateDeliverableRequest: {
            name: string;
        };
        UploadCandidateRequest: {
            fileName: string;
            fileType?: string;
            /** Format: int64 */
            fileSize?: number;
        };
        UploadCandidateResponse: {
            file: components["schemas"]["DeliverableFile"];
            /** @description MinIO 预签名 PUT 地址，客户端直接上传文件内容 */
            uploadUrl: string;
        };
        DownloadUrlResponse: {
            /** @description MinIO 预签名 GET 地址（预览/下载） */
            url: string;
        };
        /** @description 任务讨论意见（词汇表「任务讨论」）；提交后不可编辑或删除 */
        Discussion: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            taskId: number;
            /** Format: int64 */
            authorId: number;
            authorName: string;
            content: string;
            /** @description 被 @ 成员姓名（派生字段） */
            mentionNames?: string[];
            /** Format: date-time */
            createdAt: string;
        };
        CreateDiscussionRequest: {
            content: string;
            /** @description 被 @ 的项目成员 */
            mentionUserIds?: number[];
        };
        /** @description 站内通知（词汇表「站内通知」） */
        Notification: {
            /** Format: int64 */
            id: number;
            /** @description 通知类型（discussion_mention／discussion_owner 等） */
            kind: string;
            content: string;
            /** Format: int64 */
            projectId?: number;
            /** Format: int64 */
            taskId?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            readAt?: string;
        };
        /**
         * @description 交付物边类型（PRD §4.3；词汇表「交付物边」）
         * @enum {string}
         */
        EdgeType: "hard_prerequisite" | "information" | "handover" | "feedback";
        /**
         * @description 输入必要性（必要／参考）
         * @enum {string}
         */
        Necessity: "required" | "reference";
        /** @description 交付物边（词汇表）；边上关联当前与候选交付物，就绪状态派生（AC-48） */
        DeliverableEdge: {
            /** Format: int64 */
            id: number;
            /** @description 输入／交付物名称 */
            name: string;
            edgeType: components["schemas"]["EdgeType"];
            necessity: components["schemas"]["Necessity"];
            /**
             * Format: int64
             * @description 来源任务（来源为指定项目成员时缺省，见
             */
            sourceTaskId?: number;
            sourceTaskName?: string;
            sourceTaskStatus?: components["schemas"]["TaskStatus"];
            /** @description 提供方姓名（派生字段） */
            sourceOwnerName?: string;
            /** Format: int64 */
            targetTaskId: number;
            targetTaskName?: string;
            /**
             * Format: int64
             * @description 对应来源任务的交付物项
             */
            deliverableId?: number;
            deliverableName?: string;
            /**
             * Format: int64
             * @description 已生效当前内容（可下载；派生字段）
             */
            currentFileId?: number;
            currentFileName?: string;
            /** @description 关系就绪状态（AC-48）：仅当前内容生效时就绪；候选不提前满足输入 */
            ready: boolean;
            /** @description 审核期间存在候选更新（不改变原有就绪状态） */
            hasCandidate: boolean;
            /**
             * Format: date
             * @description 期望时间
             */
            expectedDate?: string;
            /** @description 当前用户能否解除该边（派生字段；目标任务负责人／可编辑项目者） */
            canRemove?: boolean;
            /** @description 来源为指定项目成员时的输入请求（AC-29／30） */
            inputRequest?: components["schemas"]["InputRequest"];
        };
        /** @description 新增输入要求（来源＝系统内已有任务，AC-28；指定项目成员来源见 */
        CreateTaskInputRequest: {
            /** @description 输入名称 */
            name: string;
            necessity: components["schemas"]["Necessity"];
            edgeType: components["schemas"]["EdgeType"];
            /** Format: int64 */
            sourceTaskId: number;
            /**
             * Format: int64
             * @description 来源任务的交付物项（选填；未选时以边本身表达结构化条件）
             */
            deliverableId?: number;
            /** Format: date */
            expectedDate?: string;
        };
        /** @description 我的工作事项（词汇表「我的工作事项」）；卡片派生事实，动作在任务详情抽屉完成 */
        WorkItem: {
            /** @description 事项类型（task/pool_review/field_change/intermediate_review/final_review/input_request/invite/upstream/blocker 等） */
            kind: string;
            title: string;
            /** Format: int64 */
            taskId?: number;
            taskName?: string;
            /**
             * Format: int64
             * @description 事项自身 ID（审批单／输入请求／邀请／卡点）
             */
            refId?: number;
            /**
             * Format: date
             * @description 任务截止或输入期望时间
             */
            dueDate?: string;
            /** @description 审批件与输入请求的已等待天数 */
            waitingDays?: number;
            /** @description 超期标红（模块 PRD §5.4） */
            overdue?: boolean;
            /** @description 被退回事项的「已退回：理由」 */
            rejectedReason?: string;
            /** @description 「上游未就绪：缺 XX」标记 */
            unreadyNote?: string;
            /** @description 当前环节（等待他人卡片显示停在谁手里） */
            stage?: string;
            /** @description 建议打开的任务详情 Tab（overview/audit/discussion） */
            drawerTab?: string;
        };
        /** @description 我的工作五分组（AC-16；KR 终审归入待我审批） */
        MyWork: {
            pending: components["schemas"]["WorkItem"][];
            approvals: components["schemas"]["WorkItem"][];
            receipts: components["schemas"]["WorkItem"][];
            waiting: components["schemas"]["WorkItem"][];
            blockers: components["schemas"]["WorkItem"][];
        };
        /**
         * @description 卡点类型（词汇表「结构化卡点」）
         * @enum {string}
         */
        BlockerKind: "input_missing" | "approval_waiting" | "resource" | "other";
        /** @enum {string} */
        BlockerState: "open" | "resolved";
        /** @description 结构化卡点（词汇表）；解除后保留处理事实 */
        Blocker: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            taskId: number;
            kind: components["schemas"]["BlockerKind"];
            /** @description 缺失的输入或条件 */
            missing: string;
            /** @description 阻塞原因 */
            reason: string;
            /**
             * Format: int64
             * @description 希望行动人
             */
            actionOwnerId?: number;
            actionOwnerName?: string;
            /** @description 预警或高风险（结构化卡点不使用 normal） */
            level: components["schemas"]["RiskLevel"];
            /** Format: date */
            expectedRecoveryDate?: string;
            state: components["schemas"]["BlockerState"];
            createdByName?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            resolvedAt?: string;
            /** @description 解除说明（处理事实） */
            resolvedNote?: string;
            /** @description 当前用户能否一键提醒（派生字段；上报人／任务负责人／可编辑项目者，开放中） */
            canRemind?: boolean;
            /** @description 当前用户能否解除（派生字段；上报人／希望行动人／任务负责人／可编辑项目者，开放中） */
            canResolve?: boolean;
        };
        CreateBlockerRequest: {
            kind: components["schemas"]["BlockerKind"];
            missing: string;
            reason: string;
            /** Format: int64 */
            actionOwnerId: number;
            level: components["schemas"]["RiskLevel"];
            /**
             * Format: date
             * @description 预计恢复时间，选填
             */
            expectedRecoveryDate?: string;
        };
        ResolveBlockerRequest: {
            /** @description 解除说明，选填 */
            note?: string;
        };
        /**
         * @description 输入请求状态（词汇表「输入请求」；PRD §5.5）
         * @enum {string}
         */
        InputRequestState: "pending" | "accepted" | "provided";
        /** @description 指定项目成员的输入请求（附着在成员 → 目标任务的交付物边上） */
        InputRequest: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            edgeId: number;
            /** Format: int64 */
            providerId: number;
            providerName: string;
            /** @description 所需内容说明 */
            contentNote?: string;
            state: components["schemas"]["InputRequestState"];
            /**
             * Format: date-time
             * @description 站内通知发送时间（入池审批通过后才发送）
             */
            notifiedAt?: string;
            /** Format: date-time */
            acceptedAt?: string;
            /** Format: date-time */
            providedAt?: string;
            /** @description 对接人提交的文字内容 */
            providedText?: string;
            providedFileName?: string;
            /** @description 当前用户能否同意接收（派生字段；对接人本人且待接收） */
            canAccept?: boolean;
            /** @description 当前用户能否提交内容（派生字段；对接人本人且已接收） */
            canProvide?: boolean;
        };
        /** @description 新增输入要求（来源＝指定项目成员，AC-29） */
        CreateMemberInputRequest: {
            name: string;
            necessity: components["schemas"]["Necessity"];
            /**
             * Format: int64
             * @description 对接人（非只读项目成员）
             */
            providerId: number;
            /** @description 所需内容（§9.1 必填） */
            contentNote: string;
            /**
             * Format: date
             * @description 期望时间（§9.1 必填）
             */
            expectedDate: string;
        };
        ProvideInputRequest: {
            /** @description 文字内容；与文件至少提交其一 */
            text?: string;
            /** @description 上传文件名；返回预签名上传地址 */
            fileName?: string;
        };
        ProvideInputResponse: {
            request: components["schemas"]["InputRequest"];
            /** @description 提交了 fileName 时返回的预签名上传地址 */
            uploadUrl?: string;
        };
        /**
         * @description 完成申请状态（词汇表「完成申请」；PRD §5.2.C）
         * @enum {string}
         */
        CompletionReviewState: "intermediate_review" | "pending_final" | "approved" | "rejected";
        /** @description 申请内的候选交付物快照；文件按覆盖／退回规则删除后 fileId 不再返回 */
        CompletionReviewItem: {
            /** Format: int64 */
            deliverableId: number;
            deliverableName: string;
            fileName: string;
            /**
             * Format: int64
             * @description 仍可预览／下载的在库文件；已删除时缺省
             */
            fileId?: number;
        };
        ReviewerInfo: {
            /** Format: int64 */
            userId: number;
            displayName: string;
        };
        SetReviewersRequest: {
            /** @description 中间审核人（或签组；可为空表示不配置）；须为非只读项目成员 */
            userIds: number[];
        };
        /** @description 完成申请（词汇表）；整体通过或整体退回 */
        CompletionReview: {
            /** Format: int64 */
            id: number;
            state: components["schemas"]["CompletionReviewState"];
            /** @description 提交说明 */
            note: string;
            /** @description 审核意见；退回意见必填（AC-38） */
            opinion?: string;
            items: components["schemas"]["CompletionReviewItem"][];
            submittedByName?: string;
            decidedByName?: string;
            /** Format: date-time */
            submittedAt?: string;
            /** Format: date-time */
            decidedAt?: string;
            /** @description 中间审核组快照（或签；AC-14） */
            reviewers?: components["schemas"]["ReviewerInfo"][];
            /** @description 或签通过的处理人姓名（派生字段） */
            intermediateByName?: string;
            /** Format: date-time */
            intermediateAt?: string;
            intermediateOpinion?: string;
            /** @description 当前用户能否处理本申请（派生字段；中间审核中为或签组成员，待 KR 终审时仅所属 KR 负责人，AC-37） */
            canDecide?: boolean;
        };
        SubmitCompletionRequest: {
            /** @description 提交说明（§9.1 必填） */
            note: string;
        };
        CompletionDecisionRequest: {
            /** @enum {string} */
            decision: "approved" | "rejected";
            /** @description 通过意见选填，退回意见必填（AC-38） */
            opinion?: string;
        };
        /**
         * @description 任务创建邀请状态（词汇表「任务创建邀请」）
         * @enum {string}
         */
        TaskInviteState: "pending" | "completed" | "revoked";
        TaskInvite: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            keyResultId: number;
            /** Format: int64 */
            inviterId: number;
            /** @description 邀请人姓名（派生字段） */
            inviterName: string;
            /** Format: int64 */
            inviteeId: number;
            /** @description 受邀成员姓名（派生字段） */
            inviteeName: string;
            /** @description 邀请说明 */
            note?: string;
            state: components["schemas"]["TaskInviteState"];
            /** Format: date-time */
            createdAt: string;
            /** @description 当前用户能否响应本邀请（派生字段；受邀人且待处理） */
            canHandle: boolean;
            /** @description 当前用户能否撤回本邀请（派生字段；邀请人／项目管理员／项目负责人且待处理） */
            canRevoke: boolean;
        };
        CreateTaskInvitesRequest: {
            /** Format: int64 */
            keyResultId: number;
            /** @description 受邀成员（可多选；须为非只读项目成员，不能邀请自己） */
            inviteeIds: number[];
            /** @description 邀请说明，随站内通知一同展示 */
            note?: string;
        };
        PoolReviewDecisionRequest: {
            /** @enum {string} */
            decision: "approved" | "rejected";
            opinion?: string;
        };
        Project: {
            /** Format: int64 */
            id: number;
            name: string;
            /**
             * Format: int64
             * @description 项目负责人（单人；与项目管理员为独立角色）
             */
            ownerId: number;
            /** @description 项目负责人姓名（派生字段，前端直接展示） */
            ownerName: string;
            status: components["schemas"]["ProjectStatus"];
            /** @description 业务里程碑标签，自由文本，选填 */
            stage?: string;
            /** Format: date */
            plannedStartDate?: string;
            /** Format: date */
            plannedEndDate?: string;
            /** Format: date-time */
            createdAt: string;
            /** @description 当前用户能否编辑本项目（派生字段，按成员角色与项目负责人身份在 domain 层判定） */
            canEdit: boolean;
            /** @description 当前用户能否管理本项目成员和权限（派生字段，同上） */
            canManageMembers: boolean;
        };
        CreateProjectRequest: {
            name: string;
            /** Format: int64 */
            ownerId: number;
            stage?: string;
            /** Format: date */
            plannedStartDate?: string;
            /** Format: date */
            plannedEndDate?: string;
        };
        UpdateProjectRequest: {
            name: string;
            /** Format: int64 */
            ownerId: number;
            status: components["schemas"]["ProjectStatus"];
            stage?: string;
            /** Format: date */
            plannedStartDate?: string;
            /** Format: date */
            plannedEndDate?: string;
        };
    };
    responses: {
        /** @description 未登录或会话已过期 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 登录失败次数过多，暂时限速 */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 请求内容未通过校验 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 当前用户无权执行该动作（动作权限按成员角色在 domain 层统一判定） */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 与现有资源状态冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退出 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    listProjectMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成员列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMember"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addProjectMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProjectMemberRequest"];
            };
        };
        responses: {
            /** @description 已加入 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMember"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateProjectMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectMemberRoleRequest"];
            };
        };
        responses: {
            /** @description 已调整 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMember"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    removeProjectMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已移出 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listObjectives: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description O 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Objective"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createOkrBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOkrBatchRequest"];
            };
        };
        responses: {
            /** @description 创建成功，返回项目最新的完整 O／KR 列表 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Objective"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    listTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createTaskBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskBatchRequest"];
            };
        };
        responses: {
            /** @description 创建成功，返回项目最新的完整任务列表 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    submitTaskPoolReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已提交，任务进入待入池审批 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    decideTaskPoolReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PoolReviewDecisionRequest"];
            };
        };
        responses: {
            /** @description 已处理，返回任务最新状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getTaskDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskStatusRequest"];
            };
        };
        responses: {
            /** @description 已流转，返回任务最新状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateTaskProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskProgressRequest"];
            };
        };
        responses: {
            /** @description 已更新，返回任务最新状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    submitFieldChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitFieldChangeRequest"];
            };
        };
        responses: {
            /** @description 已受理，返回任务最新状态（含拟议值标示） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    decideFieldChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
                changeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldChangeDecisionRequest"];
            };
        };
        responses: {
            /** @description 已处理，返回任务最新状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    abandonFieldChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
                changeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已放弃，返回任务最新状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    createDeliverable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeliverableRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deliverable"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    uploadCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
                deliverableId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadCandidateRequest"];
            };
        };
        responses: {
            /** @description 已登记，客户端用 uploadUrl 直传文件 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadCandidateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getFileDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                fileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 预签名地址 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrlResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    setTaskReviewers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetReviewersRequest"];
            };
        };
        responses: {
            /** @description 已调整，返回最新配置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewerInfo"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    submitCompletion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitCompletionRequest"];
            };
        };
        responses: {
            /** @description 已提交，返回任务最新状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    decideCompletion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
                reviewId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletionDecisionRequest"];
            };
        };
        responses: {
            /** @description 已处理，返回任务最新状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    createTaskInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskInputRequest"];
            };
        };
        responses: {
            /** @description 已建立 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliverableEdge"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    createMemberInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberInputRequest"];
            };
        };
        responses: {
            /** @description 已建立 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliverableEdge"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    acceptInputRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                requestId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已接收 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InputRequest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    provideInput: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                requestId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvideInputRequest"];
            };
        };
        responses: {
            /** @description 已提交 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvideInputResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getInputRequestFileUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                requestId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 预签名地址 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrlResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    removeEdge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                edgeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已解除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listEdges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 交付物边列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliverableEdge"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createBlocker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBlockerRequest"];
            };
        };
        responses: {
            /** @description 已上报 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blocker"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listBlockers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 卡点列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blocker"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    remindBlocker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                blockerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已提醒 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    resolveBlocker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                blockerId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveBlockerRequest"];
            };
        };
        responses: {
            /** @description 已解除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blocker"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    createDiscussion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                taskId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDiscussionRequest"];
            };
        };
        responses: {
            /** @description 已提交 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Discussion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 通知列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已标记 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMyWork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 五分组事项 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyWork"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTaskInvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 邀请列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskInvite"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createTaskInvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskInvitesRequest"];
            };
        };
        responses: {
            /** @description 已发出，返回项目最新的完整邀请列表 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskInvite"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    revokeTaskInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: number;
                inviteId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已撤回 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskInvite"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
