// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completionReviewCountsByProject = `-- name: CompletionReviewCountsByProject :many
SELECT cr.task_id, COUNT(*) AS n
FROM completion_reviews cr
JOIN tasks t ON t.id = cr.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE o.project_id = $1
GROUP BY cr.task_id
`

type CompletionReviewCountsByProjectRow struct {
	TaskID int64
	N      int64
}

func (q *Queries) CompletionReviewCountsByProject(ctx context.Context, projectID int64) ([]CompletionReviewCountsByProjectRow, error) {
	rows, err := q.db.Query(ctx, completionReviewCountsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompletionReviewCountsByProjectRow
	for rows.Next() {
		var i CompletionReviewCountsByProjectRow
		if err := rows.Scan(&i.TaskID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliverableFilesByProject = `-- name: ListDeliverableFilesByProject :many
SELECT df.id, df.deliverable_id, df.state, df.file_name, df.file_type, df.file_size, df.object_key, df.uploaded_by, df.uploaded_at, df.effective_at, u.display_name AS uploaded_by_name
FROM deliverable_files df
JOIN deliverables d ON d.id = df.deliverable_id
JOIN tasks t ON t.id = d.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
JOIN users u ON u.id = df.uploaded_by
WHERE o.project_id = $1
ORDER BY df.id
`

type ListDeliverableFilesByProjectRow struct {
	ID             int64
	DeliverableID  int64
	State          string
	FileName       string
	FileType       string
	FileSize       int64
	ObjectKey      string
	UploadedBy     int64
	UploadedAt     pgtype.Timestamptz
	EffectiveAt    pgtype.Timestamptz
	UploadedByName string
}

func (q *Queries) ListDeliverableFilesByProject(ctx context.Context, projectID int64) ([]ListDeliverableFilesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listDeliverableFilesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliverableFilesByProjectRow
	for rows.Next() {
		var i ListDeliverableFilesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliverableID,
			&i.State,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.ObjectKey,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.EffectiveAt,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliverablesByProject = `-- name: ListDeliverablesByProject :many

SELECT d.id, d.task_id, d.name, d.created_by, d.created_at, t.name AS task_name, t.status AS task_status, t.key_result_id, k.objective_id
FROM deliverables d
JOIN tasks t ON t.id = d.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE o.project_id = $1
ORDER BY d.id
`

type ListDeliverablesByProjectRow struct {
	ID          int64
	TaskID      int64
	Name        string
	CreatedBy   int64
	CreatedAt   pgtype.Timestamptz
	TaskName    string
	TaskStatus  string
	KeyResultID int64
	ObjectiveID int64
}

// 成果归档（AC-17）：GetArtifacts 与项目报告共用的项目级清单查询。
// 原与成果包查询同文件；裁决 G1（#140）删除成果包后仅保留这三条。
// 归档视角（AC-17）：项目全部交付物项与任务/KR/O 归属。
func (q *Queries) ListDeliverablesByProject(ctx context.Context, projectID int64) ([]ListDeliverablesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listDeliverablesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliverablesByProjectRow
	for rows.Next() {
		var i ListDeliverablesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.TaskName,
			&i.TaskStatus,
			&i.KeyResultID,
			&i.ObjectiveID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
