// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blockers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlocker = `-- name: CreateBlocker :one
INSERT INTO blockers (task_id, kind, missing, reason, action_owner_id, level, expected_recovery_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, task_id, kind, missing, reason, action_owner_id, level, expected_recovery_date, state, created_by, created_at, resolved_at, resolved_note
`

type CreateBlockerParams struct {
	TaskID               int64
	Kind                 string
	Missing              string
	Reason               string
	ActionOwnerID        int64
	Level                string
	ExpectedRecoveryDate pgtype.Date
	CreatedBy            int64
}

func (q *Queries) CreateBlocker(ctx context.Context, arg CreateBlockerParams) (Blocker, error) {
	row := q.db.QueryRow(ctx, createBlocker,
		arg.TaskID,
		arg.Kind,
		arg.Missing,
		arg.Reason,
		arg.ActionOwnerID,
		arg.Level,
		arg.ExpectedRecoveryDate,
		arg.CreatedBy,
	)
	var i Blocker
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.Missing,
		&i.Reason,
		&i.ActionOwnerID,
		&i.Level,
		&i.ExpectedRecoveryDate,
		&i.State,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedNote,
	)
	return i, err
}

const getBlockerInProject = `-- name: GetBlockerInProject :one
SELECT b.id, b.task_id, b.kind, b.missing, b.reason, b.action_owner_id, b.level, b.expected_recovery_date, b.state, b.created_by, b.created_at, b.resolved_at, b.resolved_note, t.name AS task_name, t.owner_id AS task_owner_id, t.created_by AS task_created_by
FROM blockers b
JOIN tasks t ON t.id = b.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE b.id = $1 AND o.project_id = $2
`

type GetBlockerInProjectParams struct {
	ID        int64
	ProjectID int64
}

type GetBlockerInProjectRow struct {
	ID                   int64
	TaskID               int64
	Kind                 string
	Missing              string
	Reason               string
	ActionOwnerID        int64
	Level                string
	ExpectedRecoveryDate pgtype.Date
	State                string
	CreatedBy            int64
	CreatedAt            pgtype.Timestamptz
	ResolvedAt           pgtype.Timestamptz
	ResolvedNote         string
	TaskName             string
	TaskOwnerID          int64
	TaskCreatedBy        int64
}

func (q *Queries) GetBlockerInProject(ctx context.Context, arg GetBlockerInProjectParams) (GetBlockerInProjectRow, error) {
	row := q.db.QueryRow(ctx, getBlockerInProject, arg.ID, arg.ProjectID)
	var i GetBlockerInProjectRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.Missing,
		&i.Reason,
		&i.ActionOwnerID,
		&i.Level,
		&i.ExpectedRecoveryDate,
		&i.State,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedNote,
		&i.TaskName,
		&i.TaskOwnerID,
		&i.TaskCreatedBy,
	)
	return i, err
}

const listBlockersByProject = `-- name: ListBlockersByProject :many
SELECT b.id, b.task_id, b.kind, b.missing, b.reason, b.action_owner_id, b.level, b.expected_recovery_date, b.state, b.created_by, b.created_at, b.resolved_at, b.resolved_note, au.display_name AS action_owner_name, cu.display_name AS created_by_name,
    t.owner_id AS task_owner_id, t.created_by AS task_created_by
FROM blockers b
JOIN tasks t ON t.id = b.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
JOIN users au ON au.id = b.action_owner_id
JOIN users cu ON cu.id = b.created_by
WHERE o.project_id = $1
ORDER BY (b.state = 'open') DESC, b.id DESC
`

type ListBlockersByProjectRow struct {
	ID                   int64
	TaskID               int64
	Kind                 string
	Missing              string
	Reason               string
	ActionOwnerID        int64
	Level                string
	ExpectedRecoveryDate pgtype.Date
	State                string
	CreatedBy            int64
	CreatedAt            pgtype.Timestamptz
	ResolvedAt           pgtype.Timestamptz
	ResolvedNote         string
	ActionOwnerName      string
	CreatedByName        string
	TaskOwnerID          int64
	TaskCreatedBy        int64
}

func (q *Queries) ListBlockersByProject(ctx context.Context, projectID int64) ([]ListBlockersByProjectRow, error) {
	rows, err := q.db.Query(ctx, listBlockersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockersByProjectRow
	for rows.Next() {
		var i ListBlockersByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.Missing,
			&i.Reason,
			&i.ActionOwnerID,
			&i.Level,
			&i.ExpectedRecoveryDate,
			&i.State,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ResolvedNote,
			&i.ActionOwnerName,
			&i.CreatedByName,
			&i.TaskOwnerID,
			&i.TaskCreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockersByTask = `-- name: ListBlockersByTask :many
SELECT b.id, b.task_id, b.kind, b.missing, b.reason, b.action_owner_id, b.level, b.expected_recovery_date, b.state, b.created_by, b.created_at, b.resolved_at, b.resolved_note, au.display_name AS action_owner_name, cu.display_name AS created_by_name
FROM blockers b
JOIN users au ON au.id = b.action_owner_id
JOIN users cu ON cu.id = b.created_by
WHERE b.task_id = $1
ORDER BY (b.state = 'open') DESC, b.id DESC
`

type ListBlockersByTaskRow struct {
	ID                   int64
	TaskID               int64
	Kind                 string
	Missing              string
	Reason               string
	ActionOwnerID        int64
	Level                string
	ExpectedRecoveryDate pgtype.Date
	State                string
	CreatedBy            int64
	CreatedAt            pgtype.Timestamptz
	ResolvedAt           pgtype.Timestamptz
	ResolvedNote         string
	ActionOwnerName      string
	CreatedByName        string
}

func (q *Queries) ListBlockersByTask(ctx context.Context, taskID int64) ([]ListBlockersByTaskRow, error) {
	rows, err := q.db.Query(ctx, listBlockersByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockersByTaskRow
	for rows.Next() {
		var i ListBlockersByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.Missing,
			&i.Reason,
			&i.ActionOwnerID,
			&i.Level,
			&i.ExpectedRecoveryDate,
			&i.State,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ResolvedNote,
			&i.ActionOwnerName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openBlockerCountsByProject = `-- name: OpenBlockerCountsByProject :many
SELECT b.task_id, COUNT(*) AS n
FROM blockers b
JOIN tasks t ON t.id = b.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE o.project_id = $1 AND b.state = 'open'
GROUP BY b.task_id
`

type OpenBlockerCountsByProjectRow struct {
	TaskID int64
	N      int64
}

func (q *Queries) OpenBlockerCountsByProject(ctx context.Context, projectID int64) ([]OpenBlockerCountsByProjectRow, error) {
	rows, err := q.db.Query(ctx, openBlockerCountsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenBlockerCountsByProjectRow
	for rows.Next() {
		var i OpenBlockerCountsByProjectRow
		if err := rows.Scan(&i.TaskID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveBlocker = `-- name: ResolveBlocker :one
UPDATE blockers
SET state = 'resolved', resolved_at = now(), resolved_note = $2
WHERE id = $1
RETURNING id, task_id, kind, missing, reason, action_owner_id, level, expected_recovery_date, state, created_by, created_at, resolved_at, resolved_note
`

type ResolveBlockerParams struct {
	ID           int64
	ResolvedNote string
}

func (q *Queries) ResolveBlocker(ctx context.Context, arg ResolveBlockerParams) (Blocker, error) {
	row := q.db.QueryRow(ctx, resolveBlocker, arg.ID, arg.ResolvedNote)
	var i Blocker
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.Missing,
		&i.Reason,
		&i.ActionOwnerID,
		&i.Level,
		&i.ExpectedRecoveryDate,
		&i.State,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedNote,
	)
	return i, err
}
