// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: completion_reviews.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const candidateCountsByProject = `-- name: CandidateCountsByProject :many
SELECT d.task_id, COUNT(*) AS n
FROM deliverable_files df
JOIN deliverables d ON d.id = df.deliverable_id
JOIN tasks t ON t.id = d.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE o.project_id = $1 AND df.state = 'candidate'
GROUP BY d.task_id
`

type CandidateCountsByProjectRow struct {
	TaskID int64
	N      int64
}

// 每个任务的候选内容数量（canSubmitCompletion 派生用）。
func (q *Queries) CandidateCountsByProject(ctx context.Context, projectID int64) ([]CandidateCountsByProjectRow, error) {
	rows, err := q.db.Query(ctx, candidateCountsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandidateCountsByProjectRow
	for rows.Next() {
		var i CandidateCountsByProjectRow
		if err := rows.Scan(&i.TaskID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCompletionReview = `-- name: CreateCompletionReview :one
INSERT INTO completion_reviews (task_id, submitted_by, note, state)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, submitted_by, note, state, opinion, submitted_at, decided_by, decided_at
`

type CreateCompletionReviewParams struct {
	TaskID      int64
	SubmittedBy int64
	Note        string
	State       string
}

func (q *Queries) CreateCompletionReview(ctx context.Context, arg CreateCompletionReviewParams) (CompletionReview, error) {
	row := q.db.QueryRow(ctx, createCompletionReview,
		arg.TaskID,
		arg.SubmittedBy,
		arg.Note,
		arg.State,
	)
	var i CompletionReview
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubmittedBy,
		&i.Note,
		&i.State,
		&i.Opinion,
		&i.SubmittedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const createCompletionReviewItem = `-- name: CreateCompletionReviewItem :exec
INSERT INTO completion_review_items (review_id, deliverable_id, deliverable_name, file_name, file_id)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCompletionReviewItemParams struct {
	ReviewID        int64
	DeliverableID   int64
	DeliverableName string
	FileName        string
	FileID          pgtype.Int8
}

func (q *Queries) CreateCompletionReviewItem(ctx context.Context, arg CreateCompletionReviewItemParams) error {
	_, err := q.db.Exec(ctx, createCompletionReviewItem,
		arg.ReviewID,
		arg.DeliverableID,
		arg.DeliverableName,
		arg.FileName,
		arg.FileID,
	)
	return err
}

const decideCompletionReview = `-- name: DecideCompletionReview :one
UPDATE completion_reviews
SET state = $2, opinion = $3, decided_by = $4, decided_at = now()
WHERE id = $1
RETURNING id, task_id, submitted_by, note, state, opinion, submitted_at, decided_by, decided_at
`

type DecideCompletionReviewParams struct {
	ID        int64
	State     string
	Opinion   string
	DecidedBy pgtype.Int8
}

func (q *Queries) DecideCompletionReview(ctx context.Context, arg DecideCompletionReviewParams) (CompletionReview, error) {
	row := q.db.QueryRow(ctx, decideCompletionReview,
		arg.ID,
		arg.State,
		arg.Opinion,
		arg.DecidedBy,
	)
	var i CompletionReview
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubmittedBy,
		&i.Note,
		&i.State,
		&i.Opinion,
		&i.SubmittedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const getCompletionReview = `-- name: GetCompletionReview :one
SELECT id, task_id, submitted_by, note, state, opinion, submitted_at, decided_by, decided_at FROM completion_reviews
WHERE id = $1 AND task_id = $2
`

type GetCompletionReviewParams struct {
	ID     int64
	TaskID int64
}

func (q *Queries) GetCompletionReview(ctx context.Context, arg GetCompletionReviewParams) (CompletionReview, error) {
	row := q.db.QueryRow(ctx, getCompletionReview, arg.ID, arg.TaskID)
	var i CompletionReview
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubmittedBy,
		&i.Note,
		&i.State,
		&i.Opinion,
		&i.SubmittedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const getCurrentFile = `-- name: GetCurrentFile :one
SELECT id, deliverable_id, state, file_name, file_type, file_size, object_key, uploaded_by, uploaded_at, effective_at FROM deliverable_files
WHERE deliverable_id = $1 AND state = 'current'
LIMIT 1
`

func (q *Queries) GetCurrentFile(ctx context.Context, deliverableID int64) (DeliverableFile, error) {
	row := q.db.QueryRow(ctx, getCurrentFile, deliverableID)
	var i DeliverableFile
	err := row.Scan(
		&i.ID,
		&i.DeliverableID,
		&i.State,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.EffectiveAt,
	)
	return i, err
}

const listCandidateFilesByTask = `-- name: ListCandidateFilesByTask :many
SELECT df.id, df.deliverable_id, df.state, df.file_name, df.file_type, df.file_size, df.object_key, df.uploaded_by, df.uploaded_at, df.effective_at, d.name AS deliverable_name
FROM deliverable_files df
JOIN deliverables d ON d.id = df.deliverable_id
WHERE d.task_id = $1 AND df.state = 'candidate'
ORDER BY df.id
`

type ListCandidateFilesByTaskRow struct {
	ID              int64
	DeliverableID   int64
	State           string
	FileName        string
	FileType        string
	FileSize        int64
	ObjectKey       string
	UploadedBy      int64
	UploadedAt      pgtype.Timestamptz
	EffectiveAt     pgtype.Timestamptz
	DeliverableName string
}

// 任务当前全部候选内容（提交完成申请时整体纳入）。
func (q *Queries) ListCandidateFilesByTask(ctx context.Context, taskID int64) ([]ListCandidateFilesByTaskRow, error) {
	rows, err := q.db.Query(ctx, listCandidateFilesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidateFilesByTaskRow
	for rows.Next() {
		var i ListCandidateFilesByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliverableID,
			&i.State,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.ObjectKey,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.EffectiveAt,
			&i.DeliverableName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletionReviewItems = `-- name: ListCompletionReviewItems :many
SELECT review_id, deliverable_id, deliverable_name, file_name, file_id FROM completion_review_items
WHERE review_id = $1
ORDER BY deliverable_id
`

func (q *Queries) ListCompletionReviewItems(ctx context.Context, reviewID int64) ([]CompletionReviewItem, error) {
	rows, err := q.db.Query(ctx, listCompletionReviewItems, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompletionReviewItem
	for rows.Next() {
		var i CompletionReviewItem
		if err := rows.Scan(
			&i.ReviewID,
			&i.DeliverableID,
			&i.DeliverableName,
			&i.FileName,
			&i.FileID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletionReviewsByTask = `-- name: ListCompletionReviewsByTask :many
SELECT cr.id, cr.task_id, cr.submitted_by, cr.note, cr.state, cr.opinion, cr.submitted_at, cr.decided_by, cr.decided_at, su.display_name AS submitted_by_name, du.display_name AS decided_by_name
FROM completion_reviews cr
JOIN users su ON su.id = cr.submitted_by
LEFT JOIN users du ON du.id = cr.decided_by
WHERE cr.task_id = $1
ORDER BY cr.id DESC
`

type ListCompletionReviewsByTaskRow struct {
	ID              int64
	TaskID          int64
	SubmittedBy     int64
	Note            string
	State           string
	Opinion         string
	SubmittedAt     pgtype.Timestamptz
	DecidedBy       pgtype.Int8
	DecidedAt       pgtype.Timestamptz
	SubmittedByName string
	DecidedByName   pgtype.Text
}

func (q *Queries) ListCompletionReviewsByTask(ctx context.Context, taskID int64) ([]ListCompletionReviewsByTaskRow, error) {
	rows, err := q.db.Query(ctx, listCompletionReviewsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletionReviewsByTaskRow
	for rows.Next() {
		var i ListCompletionReviewsByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.SubmittedBy,
			&i.Note,
			&i.State,
			&i.Opinion,
			&i.SubmittedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.SubmittedByName,
			&i.DecidedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteCandidateToCurrent = `-- name: PromoteCandidateToCurrent :one
UPDATE deliverable_files
SET state = 'current', effective_at = now()
WHERE id = $1
RETURNING id, deliverable_id, state, file_name, file_type, file_size, object_key, uploaded_by, uploaded_at, effective_at
`

// 终审通过：候选成为当前内容并盖生效时间（旧当前内容由调用方先删除）。
func (q *Queries) PromoteCandidateToCurrent(ctx context.Context, id int64) (DeliverableFile, error) {
	row := q.db.QueryRow(ctx, promoteCandidateToCurrent, id)
	var i DeliverableFile
	err := row.Scan(
		&i.ID,
		&i.DeliverableID,
		&i.State,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.EffectiveAt,
	)
	return i, err
}
