// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edges.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEdge = `-- name: CreateEdge :one
INSERT INTO deliverable_edges (target_task_id, source_task_id, source_user_id, name, necessity, expected_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, target_task_id, source_task_id, source_user_id, name, necessity, expected_date, created_by, created_at
`

type CreateEdgeParams struct {
	TargetTaskID int64
	SourceTaskID pgtype.Int8
	SourceUserID pgtype.Int8
	Name         string
	Necessity    string
	ExpectedDate pgtype.Date
	CreatedBy    int64
}

func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) (DeliverableEdge, error) {
	row := q.db.QueryRow(ctx, createEdge,
		arg.TargetTaskID,
		arg.SourceTaskID,
		arg.SourceUserID,
		arg.Name,
		arg.Necessity,
		arg.ExpectedDate,
		arg.CreatedBy,
	)
	var i DeliverableEdge
	err := row.Scan(
		&i.ID,
		&i.TargetTaskID,
		&i.SourceTaskID,
		&i.SourceUserID,
		&i.Name,
		&i.Necessity,
		&i.ExpectedDate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEdge = `-- name: DeleteEdge :execrows
DELETE FROM deliverable_edges WHERE id = $1
`

func (q *Queries) DeleteEdge(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEdge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEdgeInProject = `-- name: GetEdgeInProject :one
SELECT e.id, e.target_task_id, e.source_task_id, e.source_user_id, e.name, e.necessity, e.expected_date, e.created_by, e.created_at, tt.owner_id AS target_owner_id, tt.created_by AS target_created_by, tt.status AS target_status,
    k.owner_id AS target_kr_owner_id
FROM deliverable_edges e
JOIN tasks tt ON tt.id = e.target_task_id
JOIN key_results k ON k.id = tt.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE e.id = $1 AND o.project_id = $2
`

type GetEdgeInProjectParams struct {
	ID        int64
	ProjectID int64
}

type GetEdgeInProjectRow struct {
	ID              int64
	TargetTaskID    int64
	SourceTaskID    pgtype.Int8
	SourceUserID    pgtype.Int8
	Name            string
	Necessity       string
	ExpectedDate    pgtype.Date
	CreatedBy       int64
	CreatedAt       pgtype.Timestamptz
	TargetOwnerID   int64
	TargetCreatedBy int64
	TargetStatus    string
	TargetKrOwnerID pgtype.Int8
}

func (q *Queries) GetEdgeInProject(ctx context.Context, arg GetEdgeInProjectParams) (GetEdgeInProjectRow, error) {
	row := q.db.QueryRow(ctx, getEdgeInProject, arg.ID, arg.ProjectID)
	var i GetEdgeInProjectRow
	err := row.Scan(
		&i.ID,
		&i.TargetTaskID,
		&i.SourceTaskID,
		&i.SourceUserID,
		&i.Name,
		&i.Necessity,
		&i.ExpectedDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.TargetOwnerID,
		&i.TargetCreatedBy,
		&i.TargetStatus,
		&i.TargetKrOwnerID,
	)
	return i, err
}

const listCurrentFilesByProjectTask = `-- name: ListCurrentFilesByProjectTask :many
SELECT d.task_id, df.id AS file_id, df.file_name, df.file_size
FROM deliverable_files df
JOIN deliverables d ON d.id = df.deliverable_id
JOIN tasks t ON t.id = d.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE o.project_id = $1 AND df.state = 'current'
ORDER BY df.id
`

type ListCurrentFilesByProjectTaskRow struct {
	TaskID   int64
	FileID   int64
	FileName string
	FileSize int64
}

// 裁决 J1（#142）：关系列表「当前交付物」列——项目内各任务全部已生效当前内容，
// 供边未绑定具体交付物项时按来源任务归组展示。
func (q *Queries) ListCurrentFilesByProjectTask(ctx context.Context, projectID int64) ([]ListCurrentFilesByProjectTaskRow, error) {
	rows, err := q.db.Query(ctx, listCurrentFilesByProjectTask, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentFilesByProjectTaskRow
	for rows.Next() {
		var i ListCurrentFilesByProjectTaskRow
		if err := rows.Scan(
			&i.TaskID,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgeRefsByDeliverableTask = `-- name: ListEdgeRefsByDeliverableTask :many
SELECT e.id, e.source_task_id, e.name, e.necessity, e.target_task_id,
    tt.name AS target_task_name
FROM deliverable_edges e
JOIN tasks tt ON tt.id = e.target_task_id
WHERE e.source_task_id = $1
ORDER BY e.id
`

type ListEdgeRefsByDeliverableTaskRow struct {
	ID             int64
	SourceTaskID   pgtype.Int8
	Name           string
	Necessity      string
	TargetTaskID   int64
	TargetTaskName string
}

// 交付物承接的关系边（AC-17 归档视角「来源关系边」列；裁决 #163：按来源任务归属）。
func (q *Queries) ListEdgeRefsByDeliverableTask(ctx context.Context, sourceTaskID pgtype.Int8) ([]ListEdgeRefsByDeliverableTaskRow, error) {
	rows, err := q.db.Query(ctx, listEdgeRefsByDeliverableTask, sourceTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEdgeRefsByDeliverableTaskRow
	for rows.Next() {
		var i ListEdgeRefsByDeliverableTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceTaskID,
			&i.Name,
			&i.Necessity,
			&i.TargetTaskID,
			&i.TargetTaskName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgeRefsByProject = `-- name: ListEdgeRefsByProject :many
SELECT e.id, e.source_task_id, e.name, e.necessity, e.target_task_id,
    tt.name AS target_task_name
FROM deliverable_edges e
JOIN tasks tt ON tt.id = e.target_task_id
JOIN key_results k ON k.id = tt.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE e.source_task_id IS NOT NULL AND o.project_id = $1
ORDER BY e.id
`

type ListEdgeRefsByProjectRow struct {
	ID             int64
	SourceTaskID   pgtype.Int8
	Name           string
	Necessity      string
	TargetTaskID   int64
	TargetTaskName string
}

// 同上，项目全量：归档视角一次性取齐所有来源任务的输出边。
func (q *Queries) ListEdgeRefsByProject(ctx context.Context, projectID int64) ([]ListEdgeRefsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listEdgeRefsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEdgeRefsByProjectRow
	for rows.Next() {
		var i ListEdgeRefsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceTaskID,
			&i.Name,
			&i.Necessity,
			&i.TargetTaskID,
			&i.TargetTaskName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesByProject = `-- name: ListEdgesByProject :many
SELECT e.id, e.target_task_id, e.source_task_id, e.source_user_id, e.name, e.necessity, e.expected_date, e.created_by, e.created_at,
    st.name AS source_task_name, st.status AS source_task_status,
    st.owner_id AS source_owner_id, su.display_name AS source_owner_name,
    mu.display_name AS source_user_name,
    tt.name AS target_task_name, tt.owner_id AS target_owner_id, tt.created_by AS target_created_by
FROM deliverable_edges e
JOIN tasks tt ON tt.id = e.target_task_id
JOIN key_results k ON k.id = tt.key_result_id
JOIN objectives o ON o.id = k.objective_id
LEFT JOIN tasks st ON st.id = e.source_task_id
LEFT JOIN users su ON su.id = st.owner_id
LEFT JOIN users mu ON mu.id = e.source_user_id
WHERE o.project_id = $1
ORDER BY e.id
`

type ListEdgesByProjectRow struct {
	ID               int64
	TargetTaskID     int64
	SourceTaskID     pgtype.Int8
	SourceUserID     pgtype.Int8
	Name             string
	Necessity        string
	ExpectedDate     pgtype.Date
	CreatedBy        int64
	CreatedAt        pgtype.Timestamptz
	SourceTaskName   pgtype.Text
	SourceTaskStatus pgtype.Text
	SourceOwnerID    pgtype.Int8
	SourceOwnerName  pgtype.Text
	SourceUserName   pgtype.Text
	TargetTaskName   string
	TargetOwnerID    int64
	TargetCreatedBy  int64
}

// 项目全部交付物边，含两端任务事实（AC-48 修订，裁决 #163：就绪只看来源任务状态，
// 成员来源由输入请求状态判定，均在 domain/handler 计算）。
func (q *Queries) ListEdgesByProject(ctx context.Context, projectID int64) ([]ListEdgesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listEdgesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEdgesByProjectRow
	for rows.Next() {
		var i ListEdgesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetTaskID,
			&i.SourceTaskID,
			&i.SourceUserID,
			&i.Name,
			&i.Necessity,
			&i.ExpectedDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.SourceTaskName,
			&i.SourceTaskStatus,
			&i.SourceOwnerID,
			&i.SourceOwnerName,
			&i.SourceUserName,
			&i.TargetTaskName,
			&i.TargetOwnerID,
			&i.TargetCreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInputReadinessByProject = `-- name: ListInputReadinessByProject :many
SELECT tt.key_result_id, tt.status AS target_status,
    st.status AS source_task_status,
    ir.state AS input_request_state
FROM deliverable_edges e
JOIN tasks tt ON tt.id = e.target_task_id
JOIN key_results k ON k.id = tt.key_result_id
JOIN objectives o ON o.id = k.objective_id
LEFT JOIN tasks st ON st.id = e.source_task_id
LEFT JOIN input_requests ir ON ir.edge_id = e.id
WHERE o.project_id = $1
`

type ListInputReadinessByProjectRow struct {
	KeyResultID       int64
	TargetStatus      string
	SourceTaskStatus  pgtype.Text
	InputRequestState pgtype.Text
}

// #150 风险队列「未就绪摘要」：项目全部输入边的就绪事实——目标任务所属 KR、
// 目标任务状态、来源任务状态与成员来源的输入请求状态（与 AC-48 修订同源）；计数规则在 domain。
func (q *Queries) ListInputReadinessByProject(ctx context.Context, projectID int64) ([]ListInputReadinessByProjectRow, error) {
	rows, err := q.db.Query(ctx, listInputReadinessByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInputReadinessByProjectRow
	for rows.Next() {
		var i ListInputReadinessByProjectRow
		if err := rows.Scan(
			&i.KeyResultID,
			&i.TargetStatus,
			&i.SourceTaskStatus,
			&i.InputRequestState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
