// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: field_changes.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyTaskKeyFields = `-- name: ApplyTaskKeyFields :one
UPDATE tasks
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    completion_criteria = COALESCE($3, completion_criteria),
    owner_id = COALESCE($4, owner_id),
    end_date = COALESCE($5, end_date),
    updated_at = now()
WHERE id = $6
RETURNING id, key_result_id, name, owner_id, start_date, end_date, status, created_by, created_at, progress, cancel_reason, description, completion_criteria, updated_at, receiver_scope, code_seq, result_update
`

type ApplyTaskKeyFieldsParams struct {
	Name               pgtype.Text
	Description        pgtype.Text
	CompletionCriteria pgtype.Text
	OwnerID            pgtype.Int8
	EndDate            pgtype.Date
	ID                 int64
}

// 变更单通过／免审生效：仅覆盖拟议的字段（NULL 表示未修改）。
func (q *Queries) ApplyTaskKeyFields(ctx context.Context, arg ApplyTaskKeyFieldsParams) (Task, error) {
	row := q.db.QueryRow(ctx, applyTaskKeyFields,
		arg.Name,
		arg.Description,
		arg.CompletionCriteria,
		arg.OwnerID,
		arg.EndDate,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Progress,
		&i.CancelReason,
		&i.Description,
		&i.CompletionCriteria,
		&i.UpdatedAt,
		&i.ReceiverScope,
		&i.CodeSeq,
		&i.ResultUpdate,
	)
	return i, err
}

const createFieldChange = `-- name: CreateFieldChange :one
INSERT INTO field_change_requests (
    task_id, submitted_by, reason, state, exempt, opinion, decided_by, decided_at,
    change_type, old_status, new_status, payload,
    old_name, new_name, old_description, new_description,
    old_completion_criteria, new_completion_criteria,
    old_owner_id, new_owner_id, old_end_date, new_end_date
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
RETURNING id, task_id, submitted_by, reason, state, exempt, opinion, resolved, old_name, new_name, old_description, new_description, old_completion_criteria, new_completion_criteria, old_owner_id, new_owner_id, old_end_date, new_end_date, submitted_at, decided_by, decided_at, change_type, old_status, new_status, payload
`

type CreateFieldChangeParams struct {
	TaskID                int64
	SubmittedBy           int64
	Reason                string
	State                 string
	Exempt                bool
	Opinion               string
	DecidedBy             pgtype.Int8
	DecidedAt             pgtype.Timestamptz
	ChangeType            string
	OldStatus             pgtype.Text
	NewStatus             pgtype.Text
	Payload               []byte
	OldName               pgtype.Text
	NewName               pgtype.Text
	OldDescription        pgtype.Text
	NewDescription        pgtype.Text
	OldCompletionCriteria pgtype.Text
	NewCompletionCriteria pgtype.Text
	OldOwnerID            pgtype.Int8
	NewOwnerID            pgtype.Int8
	OldEndDate            pgtype.Date
	NewEndDate            pgtype.Date
}

func (q *Queries) CreateFieldChange(ctx context.Context, arg CreateFieldChangeParams) (FieldChangeRequest, error) {
	row := q.db.QueryRow(ctx, createFieldChange,
		arg.TaskID,
		arg.SubmittedBy,
		arg.Reason,
		arg.State,
		arg.Exempt,
		arg.Opinion,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.ChangeType,
		arg.OldStatus,
		arg.NewStatus,
		arg.Payload,
		arg.OldName,
		arg.NewName,
		arg.OldDescription,
		arg.NewDescription,
		arg.OldCompletionCriteria,
		arg.NewCompletionCriteria,
		arg.OldOwnerID,
		arg.NewOwnerID,
		arg.OldEndDate,
		arg.NewEndDate,
	)
	var i FieldChangeRequest
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubmittedBy,
		&i.Reason,
		&i.State,
		&i.Exempt,
		&i.Opinion,
		&i.Resolved,
		&i.OldName,
		&i.NewName,
		&i.OldDescription,
		&i.NewDescription,
		&i.OldCompletionCriteria,
		&i.NewCompletionCriteria,
		&i.OldOwnerID,
		&i.NewOwnerID,
		&i.OldEndDate,
		&i.NewEndDate,
		&i.SubmittedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ChangeType,
		&i.OldStatus,
		&i.NewStatus,
		&i.Payload,
	)
	return i, err
}

const decideFieldChange = `-- name: DecideFieldChange :one
UPDATE field_change_requests
SET state = $2, opinion = $3, decided_by = $4, decided_at = now()
WHERE id = $1
RETURNING id, task_id, submitted_by, reason, state, exempt, opinion, resolved, old_name, new_name, old_description, new_description, old_completion_criteria, new_completion_criteria, old_owner_id, new_owner_id, old_end_date, new_end_date, submitted_at, decided_by, decided_at, change_type, old_status, new_status, payload
`

type DecideFieldChangeParams struct {
	ID        int64
	State     string
	Opinion   string
	DecidedBy pgtype.Int8
}

func (q *Queries) DecideFieldChange(ctx context.Context, arg DecideFieldChangeParams) (FieldChangeRequest, error) {
	row := q.db.QueryRow(ctx, decideFieldChange,
		arg.ID,
		arg.State,
		arg.Opinion,
		arg.DecidedBy,
	)
	var i FieldChangeRequest
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubmittedBy,
		&i.Reason,
		&i.State,
		&i.Exempt,
		&i.Opinion,
		&i.Resolved,
		&i.OldName,
		&i.NewName,
		&i.OldDescription,
		&i.NewDescription,
		&i.OldCompletionCriteria,
		&i.NewCompletionCriteria,
		&i.OldOwnerID,
		&i.NewOwnerID,
		&i.OldEndDate,
		&i.NewEndDate,
		&i.SubmittedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ChangeType,
		&i.OldStatus,
		&i.NewStatus,
		&i.Payload,
	)
	return i, err
}

const getFieldChange = `-- name: GetFieldChange :one
SELECT id, task_id, submitted_by, reason, state, exempt, opinion, resolved, old_name, new_name, old_description, new_description, old_completion_criteria, new_completion_criteria, old_owner_id, new_owner_id, old_end_date, new_end_date, submitted_at, decided_by, decided_at, change_type, old_status, new_status, payload FROM field_change_requests
WHERE id = $1 AND task_id = $2
`

type GetFieldChangeParams struct {
	ID     int64
	TaskID int64
}

func (q *Queries) GetFieldChange(ctx context.Context, arg GetFieldChangeParams) (FieldChangeRequest, error) {
	row := q.db.QueryRow(ctx, getFieldChange, arg.ID, arg.TaskID)
	var i FieldChangeRequest
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubmittedBy,
		&i.Reason,
		&i.State,
		&i.Exempt,
		&i.Opinion,
		&i.Resolved,
		&i.OldName,
		&i.NewName,
		&i.OldDescription,
		&i.NewDescription,
		&i.OldCompletionCriteria,
		&i.NewCompletionCriteria,
		&i.OldOwnerID,
		&i.NewOwnerID,
		&i.OldEndDate,
		&i.NewEndDate,
		&i.SubmittedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ChangeType,
		&i.OldStatus,
		&i.NewStatus,
		&i.Payload,
	)
	return i, err
}

const hasPendingFieldChange = `-- name: HasPendingFieldChange :one
SELECT EXISTS (
    SELECT 1 FROM field_change_requests WHERE task_id = $1 AND state = 'pending'
) AS has_pending
`

func (q *Queries) HasPendingFieldChange(ctx context.Context, taskID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingFieldChange, taskID)
	var has_pending bool
	err := row.Scan(&has_pending)
	return has_pending, err
}

const latestFieldChangesByProject = `-- name: LatestFieldChangesByProject :many
SELECT DISTINCT ON (fc.task_id) fc.id, fc.task_id, fc.submitted_by, fc.reason, fc.state, fc.exempt, fc.opinion, fc.resolved, fc.old_name, fc.new_name, fc.old_description, fc.new_description, fc.old_completion_criteria, fc.new_completion_criteria, fc.old_owner_id, fc.new_owner_id, fc.old_end_date, fc.new_end_date, fc.submitted_at, fc.decided_by, fc.decided_at, fc.change_type, fc.old_status, fc.new_status, fc.payload,
    su.display_name AS submitted_by_name,
    du.display_name AS decided_by_name
FROM field_change_requests fc
JOIN tasks t ON t.id = fc.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
JOIN users su ON su.id = fc.submitted_by
LEFT JOIN users du ON du.id = fc.decided_by
WHERE o.project_id = $1
  AND (fc.state = 'pending' OR (fc.state = 'rejected' AND NOT fc.resolved))
ORDER BY fc.task_id, fc.id DESC
`

type LatestFieldChangesByProjectRow struct {
	ID                    int64
	TaskID                int64
	SubmittedBy           int64
	Reason                string
	State                 string
	Exempt                bool
	Opinion               string
	Resolved              bool
	OldName               pgtype.Text
	NewName               pgtype.Text
	OldDescription        pgtype.Text
	NewDescription        pgtype.Text
	OldCompletionCriteria pgtype.Text
	NewCompletionCriteria pgtype.Text
	OldOwnerID            pgtype.Int8
	NewOwnerID            pgtype.Int8
	OldEndDate            pgtype.Date
	NewEndDate            pgtype.Date
	SubmittedAt           pgtype.Timestamptz
	DecidedBy             pgtype.Int8
	DecidedAt             pgtype.Timestamptz
	ChangeType            string
	OldStatus             pgtype.Text
	NewStatus             pgtype.Text
	Payload               []byte
	SubmittedByName       string
	DecidedByName         pgtype.Text
}

// 每个任务最近一张需要关注的变更单（待审批，或退回未处理），列表标示用。
func (q *Queries) LatestFieldChangesByProject(ctx context.Context, projectID int64) ([]LatestFieldChangesByProjectRow, error) {
	rows, err := q.db.Query(ctx, latestFieldChangesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestFieldChangesByProjectRow
	for rows.Next() {
		var i LatestFieldChangesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.SubmittedBy,
			&i.Reason,
			&i.State,
			&i.Exempt,
			&i.Opinion,
			&i.Resolved,
			&i.OldName,
			&i.NewName,
			&i.OldDescription,
			&i.NewDescription,
			&i.OldCompletionCriteria,
			&i.NewCompletionCriteria,
			&i.OldOwnerID,
			&i.NewOwnerID,
			&i.OldEndDate,
			&i.NewEndDate,
			&i.SubmittedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.ChangeType,
			&i.OldStatus,
			&i.NewStatus,
			&i.Payload,
			&i.SubmittedByName,
			&i.DecidedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldChangesByTask = `-- name: ListFieldChangesByTask :many
SELECT fc.id, fc.task_id, fc.submitted_by, fc.reason, fc.state, fc.exempt, fc.opinion, fc.resolved, fc.old_name, fc.new_name, fc.old_description, fc.new_description, fc.old_completion_criteria, fc.new_completion_criteria, fc.old_owner_id, fc.new_owner_id, fc.old_end_date, fc.new_end_date, fc.submitted_at, fc.decided_by, fc.decided_at, fc.change_type, fc.old_status, fc.new_status, fc.payload, su.display_name AS submitted_by_name, du.display_name AS decided_by_name
FROM field_change_requests fc
JOIN users su ON su.id = fc.submitted_by
LEFT JOIN users du ON du.id = fc.decided_by
WHERE fc.task_id = $1
ORDER BY fc.id DESC
`

type ListFieldChangesByTaskRow struct {
	ID                    int64
	TaskID                int64
	SubmittedBy           int64
	Reason                string
	State                 string
	Exempt                bool
	Opinion               string
	Resolved              bool
	OldName               pgtype.Text
	NewName               pgtype.Text
	OldDescription        pgtype.Text
	NewDescription        pgtype.Text
	OldCompletionCriteria pgtype.Text
	NewCompletionCriteria pgtype.Text
	OldOwnerID            pgtype.Int8
	NewOwnerID            pgtype.Int8
	OldEndDate            pgtype.Date
	NewEndDate            pgtype.Date
	SubmittedAt           pgtype.Timestamptz
	DecidedBy             pgtype.Int8
	DecidedAt             pgtype.Timestamptz
	ChangeType            string
	OldStatus             pgtype.Text
	NewStatus             pgtype.Text
	Payload               []byte
	SubmittedByName       string
	DecidedByName         pgtype.Text
}

func (q *Queries) ListFieldChangesByTask(ctx context.Context, taskID int64) ([]ListFieldChangesByTaskRow, error) {
	rows, err := q.db.Query(ctx, listFieldChangesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFieldChangesByTaskRow
	for rows.Next() {
		var i ListFieldChangesByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.SubmittedBy,
			&i.Reason,
			&i.State,
			&i.Exempt,
			&i.Opinion,
			&i.Resolved,
			&i.OldName,
			&i.NewName,
			&i.OldDescription,
			&i.NewDescription,
			&i.OldCompletionCriteria,
			&i.NewCompletionCriteria,
			&i.OldOwnerID,
			&i.NewOwnerID,
			&i.OldEndDate,
			&i.NewEndDate,
			&i.SubmittedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.ChangeType,
			&i.OldStatus,
			&i.NewStatus,
			&i.Payload,
			&i.SubmittedByName,
			&i.DecidedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveFieldChange = `-- name: ResolveFieldChange :one
UPDATE field_change_requests
SET resolved = TRUE
WHERE id = $1
RETURNING id, task_id, submitted_by, reason, state, exempt, opinion, resolved, old_name, new_name, old_description, new_description, old_completion_criteria, new_completion_criteria, old_owner_id, new_owner_id, old_end_date, new_end_date, submitted_at, decided_by, decided_at, change_type, old_status, new_status, payload
`

func (q *Queries) ResolveFieldChange(ctx context.Context, id int64) (FieldChangeRequest, error) {
	row := q.db.QueryRow(ctx, resolveFieldChange, id)
	var i FieldChangeRequest
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubmittedBy,
		&i.Reason,
		&i.State,
		&i.Exempt,
		&i.Opinion,
		&i.Resolved,
		&i.OldName,
		&i.NewName,
		&i.OldDescription,
		&i.NewDescription,
		&i.OldCompletionCriteria,
		&i.NewCompletionCriteria,
		&i.OldOwnerID,
		&i.NewOwnerID,
		&i.OldEndDate,
		&i.NewEndDate,
		&i.SubmittedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.ChangeType,
		&i.OldStatus,
		&i.NewStatus,
		&i.Payload,
	)
	return i, err
}

const resolveRejectedFieldChanges = `-- name: ResolveRejectedFieldChanges :execrows
UPDATE field_change_requests
SET resolved = TRUE
WHERE task_id = $1 AND submitted_by = $2 AND state = 'rejected' AND NOT resolved
`

type ResolveRejectedFieldChangesParams struct {
	TaskID      int64
	SubmittedBy int64
}

// 原提交人重新提交时，其此前退回未处理的变更单视为已处理（词汇表「退回待处理事项」）。
func (q *Queries) ResolveRejectedFieldChanges(ctx context.Context, arg ResolveRejectedFieldChangesParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveRejectedFieldChanges, arg.TaskID, arg.SubmittedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
