// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import_records.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImportRecord = `-- name: CreateImportRecord :one
INSERT INTO import_records (
    project_id, operator_id, source_file_name,
    objective_count, key_result_count, task_count, result, failure_summary
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, operator_id, source_file_name, objective_count, key_result_count, task_count, result, failure_summary, imported_at
`

type CreateImportRecordParams struct {
	ProjectID      int64
	OperatorID     int64
	SourceFileName string
	ObjectiveCount int32
	KeyResultCount int32
	TaskCount      int32
	Result         string
	FailureSummary string
}

// 成功的一次随导入同事务写入；失败的一次在事务回滚后单独写入（AC-68）。
func (q *Queries) CreateImportRecord(ctx context.Context, arg CreateImportRecordParams) (ImportRecord, error) {
	row := q.db.QueryRow(ctx, createImportRecord,
		arg.ProjectID,
		arg.OperatorID,
		arg.SourceFileName,
		arg.ObjectiveCount,
		arg.KeyResultCount,
		arg.TaskCount,
		arg.Result,
		arg.FailureSummary,
	)
	var i ImportRecord
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OperatorID,
		&i.SourceFileName,
		&i.ObjectiveCount,
		&i.KeyResultCount,
		&i.TaskCount,
		&i.Result,
		&i.FailureSummary,
		&i.ImportedAt,
	)
	return i, err
}

const listImportRecordsByProject = `-- name: ListImportRecordsByProject :many
SELECT ir.id, ir.project_id, ir.operator_id, ir.source_file_name, ir.objective_count, ir.key_result_count, ir.task_count, ir.result, ir.failure_summary, ir.imported_at, u.display_name AS operator_name
FROM import_records ir
JOIN users u ON u.id = ir.operator_id
WHERE ir.project_id = $1
ORDER BY ir.id DESC
`

type ListImportRecordsByProjectRow struct {
	ID             int64
	ProjectID      int64
	OperatorID     int64
	SourceFileName string
	ObjectiveCount int32
	KeyResultCount int32
	TaskCount      int32
	Result         string
	FailureSummary string
	ImportedAt     pgtype.Timestamptz
	OperatorName   string
}

// 项目设置「导入记录」分节，只读，最新在前。
func (q *Queries) ListImportRecordsByProject(ctx context.Context, projectID int64) ([]ListImportRecordsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listImportRecordsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportRecordsByProjectRow
	for rows.Next() {
		var i ListImportRecordsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OperatorID,
			&i.SourceFileName,
			&i.ObjectiveCount,
			&i.KeyResultCount,
			&i.TaskCount,
			&i.Result,
			&i.FailureSummary,
			&i.ImportedAt,
			&i.OperatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
