// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueMail = `-- name: ClaimDueMail :many
SELECT id, to_address, subject, body, event, status, attempts, last_error, next_attempt_at, created_at, sent_at FROM mail_outbox
WHERE status = 'pending' AND next_attempt_at <= now()
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// 后台协程取到期待发件；SKIP LOCKED 让多实例／重入互不干扰。
func (q *Queries) ClaimDueMail(ctx context.Context, limit int32) ([]MailOutbox, error) {
	rows, err := q.db.Query(ctx, claimDueMail, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailOutbox
	for rows.Next() {
		var i MailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ToAddress,
			&i.Subject,
			&i.Body,
			&i.Event,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMailOutboxByEvent = `-- name: CountMailOutboxByEvent :one
SELECT count(*) FROM mail_outbox WHERE event = $1
`

func (q *Queries) CountMailOutboxByEvent(ctx context.Context, event string) (int64, error) {
	row := q.db.QueryRow(ctx, countMailOutboxByEvent, event)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueMail = `-- name: EnqueueMail :one
INSERT INTO mail_outbox (to_address, subject, body, event)
VALUES ($1, $2, $3, $4)
RETURNING id, to_address, subject, body, event, status, attempts, last_error, next_attempt_at, created_at, sent_at
`

type EnqueueMailParams struct {
	ToAddress string
	Subject   string
	Body      string
	Event     string
}

func (q *Queries) EnqueueMail(ctx context.Context, arg EnqueueMailParams) (MailOutbox, error) {
	row := q.db.QueryRow(ctx, enqueueMail,
		arg.ToAddress,
		arg.Subject,
		arg.Body,
		arg.Event,
	)
	var i MailOutbox
	err := row.Scan(
		&i.ID,
		&i.ToAddress,
		&i.Subject,
		&i.Body,
		&i.Event,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const getMailSettings = `-- name: GetMailSettings :one
SELECT id, host, port, encryption, username, password_enc, from_name, from_address, updated_at, notify_enabled, notify_discussion_mention, notify_discussion_owner, notify_task_invite, notify_upstream_task_assigned, notify_blocker_remind FROM mail_settings WHERE id = 1
`

// #212：单行邮件通道配置；password_enc 是密文，handler 永不回显。
func (q *Queries) GetMailSettings(ctx context.Context) (MailSetting, error) {
	row := q.db.QueryRow(ctx, getMailSettings)
	var i MailSetting
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.Encryption,
		&i.Username,
		&i.PasswordEnc,
		&i.FromName,
		&i.FromAddress,
		&i.UpdatedAt,
		&i.NotifyEnabled,
		&i.NotifyDiscussionMention,
		&i.NotifyDiscussionOwner,
		&i.NotifyTaskInvite,
		&i.NotifyUpstreamTaskAssigned,
		&i.NotifyBlockerRemind,
	)
	return i, err
}

const getUserMailPrefs = `-- name: GetUserMailPrefs :one
SELECT user_id, enabled, notify_discussion_mention, notify_discussion_owner, notify_task_invite, notify_upstream_task_assigned, notify_blocker_remind, updated_at FROM user_mail_prefs WHERE user_id = $1
`

func (q *Queries) GetUserMailPrefs(ctx context.Context, userID int64) (UserMailPref, error) {
	row := q.db.QueryRow(ctx, getUserMailPrefs, userID)
	var i UserMailPref
	err := row.Scan(
		&i.UserID,
		&i.Enabled,
		&i.NotifyDiscussionMention,
		&i.NotifyDiscussionOwner,
		&i.NotifyTaskInvite,
		&i.NotifyUpstreamTaskAssigned,
		&i.NotifyBlockerRemind,
		&i.UpdatedAt,
	)
	return i, err
}

const listMailOutbox = `-- name: ListMailOutbox :many
SELECT id, to_address, subject, event, status, attempts, last_error, created_at, sent_at
FROM mail_outbox ORDER BY id DESC LIMIT $1
`

type ListMailOutboxRow struct {
	ID        int64
	ToAddress string
	Subject   string
	Event     string
	Status    string
	Attempts  int32
	LastError string
	CreatedAt pgtype.Timestamptz
	SentAt    pgtype.Timestamptz
}

// 最近发送记录，最新在前。
func (q *Queries) ListMailOutbox(ctx context.Context, limit int32) ([]ListMailOutboxRow, error) {
	rows, err := q.db.Query(ctx, listMailOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMailOutboxRow
	for rows.Next() {
		var i ListMailOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.ToAddress,
			&i.Subject,
			&i.Event,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMailFailed = `-- name: MarkMailFailed :exec
UPDATE mail_outbox SET status = 'failed', attempts = attempts + 1, last_error = $2 WHERE id = $1
`

type MarkMailFailedParams struct {
	ID        int64
	LastError string
}

func (q *Queries) MarkMailFailed(ctx context.Context, arg MarkMailFailedParams) error {
	_, err := q.db.Exec(ctx, markMailFailed, arg.ID, arg.LastError)
	return err
}

const markMailRetry = `-- name: MarkMailRetry :exec
UPDATE mail_outbox SET attempts = attempts + 1, last_error = $2, next_attempt_at = $3 WHERE id = $1
`

type MarkMailRetryParams struct {
	ID            int64
	LastError     string
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) MarkMailRetry(ctx context.Context, arg MarkMailRetryParams) error {
	_, err := q.db.Exec(ctx, markMailRetry, arg.ID, arg.LastError, arg.NextAttemptAt)
	return err
}

const markMailSent = `-- name: MarkMailSent :exec
UPDATE mail_outbox SET status = 'sent', attempts = attempts + 1, last_error = '', sent_at = now() WHERE id = $1
`

func (q *Queries) MarkMailSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markMailSent, id)
	return err
}

const setMailPassword = `-- name: SetMailPassword :exec
UPDATE mail_settings SET password_enc = $1, updated_at = now() WHERE id = 1
`

func (q *Queries) SetMailPassword(ctx context.Context, passwordEnc string) error {
	_, err := q.db.Exec(ctx, setMailPassword, passwordEnc)
	return err
}

const updateMailNotifySwitches = `-- name: UpdateMailNotifySwitches :one
UPDATE mail_settings
SET notify_enabled = $1, notify_discussion_mention = $2, notify_discussion_owner = $3,
    notify_task_invite = $4, notify_upstream_task_assigned = $5, notify_blocker_remind = $6, updated_at = now()
WHERE id = 1
RETURNING id, host, port, encryption, username, password_enc, from_name, from_address, updated_at, notify_enabled, notify_discussion_mention, notify_discussion_owner, notify_task_invite, notify_upstream_task_assigned, notify_blocker_remind
`

type UpdateMailNotifySwitchesParams struct {
	NotifyEnabled              bool
	NotifyDiscussionMention    bool
	NotifyDiscussionOwner      bool
	NotifyTaskInvite           bool
	NotifyUpstreamTaskAssigned bool
	NotifyBlockerRemind        bool
}

// #213：系统级总开关与五个事件开关。
func (q *Queries) UpdateMailNotifySwitches(ctx context.Context, arg UpdateMailNotifySwitchesParams) (MailSetting, error) {
	row := q.db.QueryRow(ctx, updateMailNotifySwitches,
		arg.NotifyEnabled,
		arg.NotifyDiscussionMention,
		arg.NotifyDiscussionOwner,
		arg.NotifyTaskInvite,
		arg.NotifyUpstreamTaskAssigned,
		arg.NotifyBlockerRemind,
	)
	var i MailSetting
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.Encryption,
		&i.Username,
		&i.PasswordEnc,
		&i.FromName,
		&i.FromAddress,
		&i.UpdatedAt,
		&i.NotifyEnabled,
		&i.NotifyDiscussionMention,
		&i.NotifyDiscussionOwner,
		&i.NotifyTaskInvite,
		&i.NotifyUpstreamTaskAssigned,
		&i.NotifyBlockerRemind,
	)
	return i, err
}

const updateMailSettings = `-- name: UpdateMailSettings :one
UPDATE mail_settings
SET host = $1, port = $2, encryption = $3, username = $4, from_name = $5, from_address = $6, updated_at = now()
WHERE id = 1
RETURNING id, host, port, encryption, username, password_enc, from_name, from_address, updated_at, notify_enabled, notify_discussion_mention, notify_discussion_owner, notify_task_invite, notify_upstream_task_assigned, notify_blocker_remind
`

type UpdateMailSettingsParams struct {
	Host        string
	Port        int32
	Encryption  string
	Username    string
	FromName    string
	FromAddress string
}

// 不含密码：密码留空表示保持原值，由 SetMailPassword 单独写。
func (q *Queries) UpdateMailSettings(ctx context.Context, arg UpdateMailSettingsParams) (MailSetting, error) {
	row := q.db.QueryRow(ctx, updateMailSettings,
		arg.Host,
		arg.Port,
		arg.Encryption,
		arg.Username,
		arg.FromName,
		arg.FromAddress,
	)
	var i MailSetting
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.Encryption,
		&i.Username,
		&i.PasswordEnc,
		&i.FromName,
		&i.FromAddress,
		&i.UpdatedAt,
		&i.NotifyEnabled,
		&i.NotifyDiscussionMention,
		&i.NotifyDiscussionOwner,
		&i.NotifyTaskInvite,
		&i.NotifyUpstreamTaskAssigned,
		&i.NotifyBlockerRemind,
	)
	return i, err
}

const upsertUserMailPrefs = `-- name: UpsertUserMailPrefs :one
INSERT INTO user_mail_prefs (user_id, enabled, notify_discussion_mention, notify_discussion_owner,
    notify_task_invite, notify_upstream_task_assigned, notify_blocker_remind)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    notify_discussion_mention = EXCLUDED.notify_discussion_mention,
    notify_discussion_owner = EXCLUDED.notify_discussion_owner,
    notify_task_invite = EXCLUDED.notify_task_invite,
    notify_upstream_task_assigned = EXCLUDED.notify_upstream_task_assigned,
    notify_blocker_remind = EXCLUDED.notify_blocker_remind,
    updated_at = now()
RETURNING user_id, enabled, notify_discussion_mention, notify_discussion_owner, notify_task_invite, notify_upstream_task_assigned, notify_blocker_remind, updated_at
`

type UpsertUserMailPrefsParams struct {
	UserID                     int64
	Enabled                    bool
	NotifyDiscussionMention    bool
	NotifyDiscussionOwner      bool
	NotifyTaskInvite           bool
	NotifyUpstreamTaskAssigned bool
	NotifyBlockerRemind        bool
}

func (q *Queries) UpsertUserMailPrefs(ctx context.Context, arg UpsertUserMailPrefsParams) (UserMailPref, error) {
	row := q.db.QueryRow(ctx, upsertUserMailPrefs,
		arg.UserID,
		arg.Enabled,
		arg.NotifyDiscussionMention,
		arg.NotifyDiscussionOwner,
		arg.NotifyTaskInvite,
		arg.NotifyUpstreamTaskAssigned,
		arg.NotifyBlockerRemind,
	)
	var i UserMailPref
	err := row.Scan(
		&i.UserID,
		&i.Enabled,
		&i.NotifyDiscussionMention,
		&i.NotifyDiscussionOwner,
		&i.NotifyTaskInvite,
		&i.NotifyUpstreamTaskAssigned,
		&i.NotifyBlockerRemind,
		&i.UpdatedAt,
	)
	return i, err
}
