// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type KeyResult struct {
	ID          int64
	ObjectiveID int64
	Description string
	Metric      string
	OwnerID     pgtype.Int8
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	RiskLevel   string
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
}

type Objective struct {
	ID          int64
	ProjectID   int64
	Title       string
	Description string
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
}

type Project struct {
	ID               int64
	Name             string
	CreatedBy        int64
	CreatedAt        pgtype.Timestamptz
	OwnerID          int64
	Status           string
	Stage            pgtype.Text
	PlannedStartDate pgtype.Date
	PlannedEndDate   pgtype.Date
}

type ProjectMember struct {
	ProjectID int64
	UserID    int64
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	DisplayName  string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
