// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: object_deletions.sql

package store

import (
	"context"
)

const deletePendingObjectDeletion = `-- name: DeletePendingObjectDeletion :exec
DELETE FROM pending_object_deletions WHERE object_key = $1
`

func (q *Queries) DeletePendingObjectDeletion(ctx context.Context, objectKey string) error {
	_, err := q.db.Exec(ctx, deletePendingObjectDeletion, objectKey)
	return err
}

const enqueueObjectDeletion = `-- name: EnqueueObjectDeletion :exec
INSERT INTO pending_object_deletions (object_key, last_error)
VALUES ($1, $2)
ON CONFLICT (object_key) DO UPDATE
SET attempts = pending_object_deletions.attempts + 1,
    last_error = EXCLUDED.last_error,
    last_try_at = now()
`

type EnqueueObjectDeletionParams struct {
	ObjectKey string
	LastError string
}

// 删除失败排队重试（E3）；同一个对象重复失败只累加次数。
func (q *Queries) EnqueueObjectDeletion(ctx context.Context, arg EnqueueObjectDeletionParams) error {
	_, err := q.db.Exec(ctx, enqueueObjectDeletion, arg.ObjectKey, arg.LastError)
	return err
}

const listPendingObjectDeletions = `-- name: ListPendingObjectDeletions :many
SELECT object_key, attempts, last_error, created_at, last_try_at FROM pending_object_deletions
ORDER BY last_try_at
LIMIT $1
`

func (q *Queries) ListPendingObjectDeletions(ctx context.Context, limit int32) ([]PendingObjectDeletion, error) {
	rows, err := q.db.Query(ctx, listPendingObjectDeletions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingObjectDeletion
	for rows.Next() {
		var i PendingObjectDeletion
		if err := rows.Scan(
			&i.ObjectKey,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.LastTryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
