// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completionReviewCountsByProject = `-- name: CompletionReviewCountsByProject :many
SELECT cr.task_id, COUNT(*) AS n
FROM completion_reviews cr
JOIN tasks t ON t.id = cr.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE o.project_id = $1
GROUP BY cr.task_id
`

type CompletionReviewCountsByProjectRow struct {
	TaskID int64
	N      int64
}

func (q *Queries) CompletionReviewCountsByProject(ctx context.Context, projectID int64) ([]CompletionReviewCountsByProjectRow, error) {
	rows, err := q.db.Query(ctx, completionReviewCountsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompletionReviewCountsByProjectRow
	for rows.Next() {
		var i CompletionReviewCountsByProjectRow
		if err := rows.Scan(&i.TaskID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPackage = `-- name: CreatePackage :one
INSERT INTO artifact_packages (project_id, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, created_by, created_at
`

type CreatePackageParams struct {
	ProjectID int64
	Name      string
	CreatedBy int64
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (ArtifactPackage, error) {
	row := q.db.QueryRow(ctx, createPackage, arg.ProjectID, arg.Name, arg.CreatedBy)
	var i ArtifactPackage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createPackageItem = `-- name: CreatePackageItem :exec
INSERT INTO artifact_package_items (package_id, deliverable_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreatePackageItemParams struct {
	PackageID     int64
	DeliverableID int64
}

func (q *Queries) CreatePackageItem(ctx context.Context, arg CreatePackageItemParams) error {
	_, err := q.db.Exec(ctx, createPackageItem, arg.PackageID, arg.DeliverableID)
	return err
}

const getPackageInProject = `-- name: GetPackageInProject :one
SELECT id, project_id, name, created_by, created_at FROM artifact_packages
WHERE id = $1 AND project_id = $2
`

type GetPackageInProjectParams struct {
	ID        int64
	ProjectID int64
}

func (q *Queries) GetPackageInProject(ctx context.Context, arg GetPackageInProjectParams) (ArtifactPackage, error) {
	row := q.db.QueryRow(ctx, getPackageInProject, arg.ID, arg.ProjectID)
	var i ArtifactPackage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDeliverableFilesByProject = `-- name: ListDeliverableFilesByProject :many
SELECT df.id, df.deliverable_id, df.state, df.file_name, df.file_type, df.file_size, df.object_key, df.uploaded_by, df.uploaded_at, df.effective_at, u.display_name AS uploaded_by_name
FROM deliverable_files df
JOIN deliverables d ON d.id = df.deliverable_id
JOIN tasks t ON t.id = d.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
JOIN users u ON u.id = df.uploaded_by
WHERE o.project_id = $1
ORDER BY df.id
`

type ListDeliverableFilesByProjectRow struct {
	ID             int64
	DeliverableID  int64
	State          string
	FileName       string
	FileType       string
	FileSize       int64
	ObjectKey      string
	UploadedBy     int64
	UploadedAt     pgtype.Timestamptz
	EffectiveAt    pgtype.Timestamptz
	UploadedByName string
}

func (q *Queries) ListDeliverableFilesByProject(ctx context.Context, projectID int64) ([]ListDeliverableFilesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listDeliverableFilesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliverableFilesByProjectRow
	for rows.Next() {
		var i ListDeliverableFilesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliverableID,
			&i.State,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.ObjectKey,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.EffectiveAt,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliverablesByProject = `-- name: ListDeliverablesByProject :many
SELECT d.id, d.task_id, d.name, d.created_by, d.created_at, t.name AS task_name, t.status AS task_status, t.key_result_id, k.objective_id
FROM deliverables d
JOIN tasks t ON t.id = d.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE o.project_id = $1
ORDER BY d.id
`

type ListDeliverablesByProjectRow struct {
	ID          int64
	TaskID      int64
	Name        string
	CreatedBy   int64
	CreatedAt   pgtype.Timestamptz
	TaskName    string
	TaskStatus  string
	KeyResultID int64
	ObjectiveID int64
}

// 归档视角（AC-17）：项目全部交付物项与任务/KR/O 归属。
func (q *Queries) ListDeliverablesByProject(ctx context.Context, projectID int64) ([]ListDeliverablesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listDeliverablesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliverablesByProjectRow
	for rows.Next() {
		var i ListDeliverablesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.TaskName,
			&i.TaskStatus,
			&i.KeyResultID,
			&i.ObjectiveID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageItems = `-- name: ListPackageItems :many
SELECT i.deliverable_id, d.name AS deliverable_name, t.name AS task_name,
    cf.id AS file_id, cf.file_name, cf.object_key, cf.effective_at
FROM artifact_package_items i
JOIN deliverables d ON d.id = i.deliverable_id
JOIN tasks t ON t.id = d.task_id
LEFT JOIN deliverable_files cf ON cf.deliverable_id = d.id AND cf.state = 'current'
WHERE i.package_id = $1
ORDER BY i.deliverable_id
`

type ListPackageItemsRow struct {
	DeliverableID   int64
	DeliverableName string
	TaskName        string
	FileID          pgtype.Int8
	FileName        pgtype.Text
	ObjectKey       pgtype.Text
	EffectiveAt     pgtype.Timestamptz
}

// 目录项解析当前内容（被覆盖后自动指向新内容；退回删除后无当前内容则 file 为空）。
func (q *Queries) ListPackageItems(ctx context.Context, packageID int64) ([]ListPackageItemsRow, error) {
	rows, err := q.db.Query(ctx, listPackageItems, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackageItemsRow
	for rows.Next() {
		var i ListPackageItemsRow
		if err := rows.Scan(
			&i.DeliverableID,
			&i.DeliverableName,
			&i.TaskName,
			&i.FileID,
			&i.FileName,
			&i.ObjectKey,
			&i.EffectiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesByProject = `-- name: ListPackagesByProject :many
SELECT p.id, p.project_id, p.name, p.created_by, p.created_at, u.display_name AS created_by_name
FROM artifact_packages p
JOIN users u ON u.id = p.created_by
WHERE p.project_id = $1
ORDER BY p.id DESC
`

type ListPackagesByProjectRow struct {
	ID            int64
	ProjectID     int64
	Name          string
	CreatedBy     int64
	CreatedAt     pgtype.Timestamptz
	CreatedByName string
}

func (q *Queries) ListPackagesByProject(ctx context.Context, projectID int64) ([]ListPackagesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listPackagesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackagesByProjectRow
	for rows.Next() {
		var i ListPackagesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
