// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receivers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearTaskReceivers = `-- name: ClearTaskReceivers :execrows
DELETE FROM task_receivers WHERE task_id = $1
`

func (q *Queries) ClearTaskReceivers(ctx context.Context, taskID int64) (int64, error) {
	result, err := q.db.Exec(ctx, clearTaskReceivers, taskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const confirmTaskReceipt = `-- name: ConfirmTaskReceipt :one
UPDATE task_receipts
SET confirmed_at = now()
WHERE id = $1 AND confirmed_at IS NULL
RETURNING id, task_id, user_id, generated_at, confirmed_at
`

func (q *Queries) ConfirmTaskReceipt(ctx context.Context, id int64) (TaskReceipt, error) {
	row := q.db.QueryRow(ctx, confirmTaskReceipt, id)
	var i TaskReceipt
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.GeneratedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const createTaskReceipt = `-- name: CreateTaskReceipt :exec
INSERT INTO task_receipts (task_id, user_id)
VALUES ($1, $2)
ON CONFLICT (task_id, user_id) DO NOTHING
`

type CreateTaskReceiptParams struct {
	TaskID int64
	UserID int64
}

// 终审通过时逐人生成待接收项；同一任务同一人只生成一次（重复终审不重复记账）。
func (q *Queries) CreateTaskReceipt(ctx context.Context, arg CreateTaskReceiptParams) error {
	_, err := q.db.Exec(ctx, createTaskReceipt, arg.TaskID, arg.UserID)
	return err
}

const getTaskReceipt = `-- name: GetTaskReceipt :one
SELECT tr.id, tr.task_id, tr.user_id, tr.generated_at, tr.confirmed_at, u.display_name
FROM task_receipts tr
JOIN users u ON u.id = tr.user_id
WHERE tr.task_id = $1 AND tr.user_id = $2
`

type GetTaskReceiptParams struct {
	TaskID int64
	UserID int64
}

type GetTaskReceiptRow struct {
	ID          int64
	TaskID      int64
	UserID      int64
	GeneratedAt pgtype.Timestamptz
	ConfirmedAt pgtype.Timestamptz
	DisplayName string
}

func (q *Queries) GetTaskReceipt(ctx context.Context, arg GetTaskReceiptParams) (GetTaskReceiptRow, error) {
	row := q.db.QueryRow(ctx, getTaskReceipt, arg.TaskID, arg.UserID)
	var i GetTaskReceiptRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.GeneratedAt,
		&i.ConfirmedAt,
		&i.DisplayName,
	)
	return i, err
}

const listReceiptsByProject = `-- name: ListReceiptsByProject :many
SELECT tr.id, tr.task_id, tr.user_id, tr.generated_at, tr.confirmed_at, t.name AS task_name, u.display_name
FROM task_receipts tr
JOIN tasks t ON t.id = tr.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
JOIN users u ON u.id = tr.user_id
WHERE o.project_id = $1
ORDER BY tr.id
`

type ListReceiptsByProjectRow struct {
	ID          int64
	TaskID      int64
	UserID      int64
	GeneratedAt pgtype.Timestamptz
	ConfirmedAt pgtype.Timestamptz
	TaskName    string
	DisplayName string
}

// 项目内全部待接收项与接收记录（我的工作分组用），含任务名。
func (q *Queries) ListReceiptsByProject(ctx context.Context, projectID int64) ([]ListReceiptsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listReceiptsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceiptsByProjectRow
	for rows.Next() {
		var i ListReceiptsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.GeneratedAt,
			&i.ConfirmedAt,
			&i.TaskName,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiversByProject = `-- name: ListReceiversByProject :many
SELECT tr.task_id, tr.user_id, u.display_name
FROM task_receivers tr
JOIN tasks t ON t.id = tr.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
JOIN users u ON u.id = tr.user_id
WHERE o.project_id = $1
ORDER BY tr.task_id, tr.user_id
`

type ListReceiversByProjectRow struct {
	TaskID      int64
	UserID      int64
	DisplayName string
}

// 项目内全部任务的接收方名单（任务列表派生字段用）。
func (q *Queries) ListReceiversByProject(ctx context.Context, projectID int64) ([]ListReceiversByProjectRow, error) {
	rows, err := q.db.Query(ctx, listReceiversByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceiversByProjectRow
	for rows.Next() {
		var i ListReceiversByProjectRow
		if err := rows.Scan(&i.TaskID, &i.UserID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskReceipts = `-- name: ListTaskReceipts :many
SELECT tr.id, tr.task_id, tr.user_id, tr.generated_at, tr.confirmed_at, u.display_name
FROM task_receipts tr
JOIN users u ON u.id = tr.user_id
WHERE tr.task_id = $1
ORDER BY tr.user_id
`

type ListTaskReceiptsRow struct {
	ID          int64
	TaskID      int64
	UserID      int64
	GeneratedAt pgtype.Timestamptz
	ConfirmedAt pgtype.Timestamptz
	DisplayName string
}

func (q *Queries) ListTaskReceipts(ctx context.Context, taskID int64) ([]ListTaskReceiptsRow, error) {
	rows, err := q.db.Query(ctx, listTaskReceipts, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskReceiptsRow
	for rows.Next() {
		var i ListTaskReceiptsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.GeneratedAt,
			&i.ConfirmedAt,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskReceivers = `-- name: ListTaskReceivers :many
SELECT tr.user_id, u.display_name
FROM task_receivers tr
JOIN users u ON u.id = tr.user_id
WHERE tr.task_id = $1
ORDER BY tr.user_id
`

type ListTaskReceiversRow struct {
	UserID      int64
	DisplayName string
}

func (q *Queries) ListTaskReceivers(ctx context.Context, taskID int64) ([]ListTaskReceiversRow, error) {
	rows, err := q.db.Query(ctx, listTaskReceivers, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskReceiversRow
	for rows.Next() {
		var i ListTaskReceiversRow
		if err := rows.Scan(&i.UserID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskReceiver = `-- name: SetTaskReceiver :exec
INSERT INTO task_receivers (task_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SetTaskReceiverParams struct {
	TaskID int64
	UserID int64
}

func (q *Queries) SetTaskReceiver(ctx context.Context, arg SetTaskReceiverParams) error {
	_, err := q.db.Exec(ctx, setTaskReceiver, arg.TaskID, arg.UserID)
	return err
}

const setTaskReceiverScope = `-- name: SetTaskReceiverScope :one
UPDATE tasks
SET receiver_scope = $2, updated_at = now()
WHERE id = $1
RETURNING id, key_result_id, name, owner_id, start_date, end_date, status, created_by, created_at, progress, cancel_reason, description, completion_criteria, updated_at, receiver_scope
`

type SetTaskReceiverScopeParams struct {
	ID            int64
	ReceiverScope string
}

func (q *Queries) SetTaskReceiverScope(ctx context.Context, arg SetTaskReceiverScopeParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskReceiverScope, arg.ID, arg.ReceiverScope)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Progress,
		&i.CancelReason,
		&i.Description,
		&i.CompletionCriteria,
		&i.UpdatedAt,
		&i.ReceiverScope,
	)
	return i, err
}
