// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminds.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRemindLog = `-- name: CreateRemindLog :one
INSERT INTO remind_logs (task_id, sender_id, target_key, remind_date)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, sender_id, target_key, remind_date, created_at
`

type CreateRemindLogParams struct {
	TaskID     int64
	SenderID   int64
	TargetKey  string
	RemindDate pgtype.Date
}

func (q *Queries) CreateRemindLog(ctx context.Context, arg CreateRemindLogParams) (RemindLog, error) {
	row := q.db.QueryRow(ctx, createRemindLog,
		arg.TaskID,
		arg.SenderID,
		arg.TargetKey,
		arg.RemindDate,
	)
	var i RemindLog
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SenderID,
		&i.TargetKey,
		&i.RemindDate,
		&i.CreatedAt,
	)
	return i, err
}

const getLastRemind = `-- name: GetLastRemind :one
SELECT id, task_id, sender_id, target_key, remind_date, created_at FROM remind_logs
WHERE task_id = $1 AND sender_id = $2
ORDER BY id DESC
LIMIT 1
`

type GetLastRemindParams struct {
	TaskID   int64
	SenderID int64
}

// 同一人对同一任务最近一次提醒（冷却判定用）。
func (q *Queries) GetLastRemind(ctx context.Context, arg GetLastRemindParams) (RemindLog, error) {
	row := q.db.QueryRow(ctx, getLastRemind, arg.TaskID, arg.SenderID)
	var i RemindLog
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SenderID,
		&i.TargetKey,
		&i.RemindDate,
		&i.CreatedAt,
	)
	return i, err
}
