// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOtherUserSessions = `-- name: DeleteOtherUserSessions :execrows
DELETE FROM sessions WHERE user_id = $1 AND token <> $2
`

type DeleteOtherUserSessionsParams struct {
	UserID int64
	Token  string
}

// 改密码后吊销本人其余会话（S3）：当前会话保留，免得改完自己被踢出去。
func (q *Queries) DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherUserSessions, arg.UserID, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :execrows
DELETE FROM sessions WHERE user_id = $1
`

// #204：停用账号时吊销其全部会话。
func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSession = `-- name: GetSession :one
SELECT token, user_id, expires_at, created_at, last_active_at FROM sessions WHERE token = $1 AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.username, u.display_name, u.password_hash, u.created_at, u.is_system_admin, u.email, u.must_change_password, u.disabled_at, u.last_login_at FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = $1 AND s.expires_at > now()
`

func (q *Queries) GetSessionUser(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRow(ctx, getSessionUser, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsSystemAdmin,
		&i.Email,
		&i.MustChangePassword,
		&i.DisabledAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT token, created_at, last_active_at, expires_at FROM sessions
WHERE user_id = $1 AND expires_at > now()
ORDER BY last_active_at DESC, created_at DESC
`

type ListUserSessionsRow struct {
	Token        string
	CreatedAt    pgtype.Timestamptz
	LastActiveAt pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

// #208：本人活跃会话（未过期），最新活动在前。
func (q *Queries) ListUserSessions(ctx context.Context, userID int64) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSessionsRow
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.Token,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionExpiry = `-- name: UpdateSessionExpiry :exec
UPDATE sessions SET expires_at = $2, last_active_at = now() WHERE token = $1
`

type UpdateSessionExpiryParams struct {
	Token     string
	ExpiresAt pgtype.Timestamptz
}

// 滑动续期时一并记最近活动时间（#208）。
func (q *Queries) UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) error {
	_, err := q.db.Exec(ctx, updateSessionExpiry, arg.Token, arg.ExpiresAt)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = $2 WHERE id = $1
`

type UpdateUserLastLoginParams struct {
	ID          int64
	LastLoginAt pgtype.Timestamptz
}

// #208：登录成功记录最近登录时间。
func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, arg.ID, arg.LastLoginAt)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, must_change_password = false WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

// 本人改密同时清除「须改密码」标记（#203）；管理员重置走另一条查询（置真）。
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
