// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_settings.sql

package store

import (
	"context"
)

const getSystemSettings = `-- name: GetSystemSettings :one
SELECT id, system_name, subtitle, login_hint, base_url, updated_at FROM system_settings WHERE id = 1
`

// #210：单行系统配置；行在迁移里预置。
func (q *Queries) GetSystemSettings(ctx context.Context) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSettings)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.SystemName,
		&i.Subtitle,
		&i.LoginHint,
		&i.BaseUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSystemSettings = `-- name: UpdateSystemSettings :one
UPDATE system_settings
SET system_name = $1, subtitle = $2, login_hint = $3, base_url = $4, updated_at = now()
WHERE id = 1
RETURNING id, system_name, subtitle, login_hint, base_url, updated_at
`

type UpdateSystemSettingsParams struct {
	SystemName string
	Subtitle   string
	LoginHint  string
	BaseUrl    string
}

func (q *Queries) UpdateSystemSettings(ctx context.Context, arg UpdateSystemSettingsParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, updateSystemSettings,
		arg.SystemName,
		arg.Subtitle,
		arg.LoginHint,
		arg.BaseUrl,
	)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.SystemName,
		&i.Subtitle,
		&i.LoginHint,
		&i.BaseUrl,
		&i.UpdatedAt,
	)
	return i, err
}
