// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyTaskKeyFields = `-- name: ApplyTaskKeyFields :one
UPDATE tasks
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    completion_criteria = COALESCE($3, completion_criteria),
    owner_id = COALESCE($4, owner_id),
    end_date = COALESCE($5, end_date),
    updated_at = now()
WHERE id = $6
RETURNING id, key_result_id, name, owner_id, start_date, end_date, status, created_by, created_at, progress, cancel_reason, description, completion_criteria, updated_at, receiver_scope, code_seq, result_update
`

type ApplyTaskKeyFieldsParams struct {
	Name               pgtype.Text
	Description        pgtype.Text
	CompletionCriteria pgtype.Text
	OwnerID            pgtype.Int8
	EndDate            pgtype.Date
	ID                 int64
}

// 关键字段直接修改生效（#172 裁决）：仅覆盖传入的字段（NULL 表示未修改）。
func (q *Queries) ApplyTaskKeyFields(ctx context.Context, arg ApplyTaskKeyFieldsParams) (Task, error) {
	row := q.db.QueryRow(ctx, applyTaskKeyFields,
		arg.Name,
		arg.Description,
		arg.CompletionCriteria,
		arg.OwnerID,
		arg.EndDate,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Progress,
		&i.CancelReason,
		&i.Description,
		&i.CompletionCriteria,
		&i.UpdatedAt,
		&i.ReceiverScope,
		&i.CodeSeq,
		&i.ResultUpdate,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (key_result_id, name, owner_id, start_date, end_date, status, created_by,
    description, completion_criteria, code_seq)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
    (SELECT COALESCE(MAX(code_seq), 0) + 1 FROM tasks WHERE key_result_id = $1))
RETURNING id, key_result_id, name, owner_id, start_date, end_date, status, created_by, created_at, progress, cancel_reason, description, completion_criteria, updated_at, receiver_scope, code_seq, result_update
`

type CreateTaskParams struct {
	KeyResultID        int64
	Name               string
	OwnerID            int64
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	Status             string
	CreatedBy          int64
	Description        string
	CompletionCriteria string
}

// code_seq 取所属 KR 下历史最大值加一，不复用被删任务的序号（AC-64）；
// 批量创建在同一事务内串行执行，MAX+1 不会互相踩踏。
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.KeyResultID,
		arg.Name,
		arg.OwnerID,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.CreatedBy,
		arg.Description,
		arg.CompletionCriteria,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Progress,
		&i.CancelReason,
		&i.Description,
		&i.CompletionCriteria,
		&i.UpdatedAt,
		&i.ReceiverScope,
		&i.CodeSeq,
		&i.ResultUpdate,
	)
	return i, err
}

const getKeyResultInProject = `-- name: GetKeyResultInProject :one
SELECT k.id, k.objective_id, k.description, k.metric, k.sort_order, k.created_at, k.code_seq, k.created_by, o.project_id, o.code_seq AS objective_code_seq
FROM key_results k
JOIN objectives o ON o.id = k.objective_id
WHERE k.id = $1 AND o.project_id = $2
`

type GetKeyResultInProjectParams struct {
	ID        int64
	ProjectID int64
}

type GetKeyResultInProjectRow struct {
	ID               int64
	ObjectiveID      int64
	Description      string
	Metric           string
	SortOrder        int32
	CreatedAt        pgtype.Timestamptz
	CodeSeq          int32
	CreatedBy        pgtype.Int8
	ProjectID        int64
	ObjectiveCodeSeq int32
}

// KR 连同项目归属与所属 O 的编号序号（任务创建时校验归属；邀请通知要拼 KR 编号）。
func (q *Queries) GetKeyResultInProject(ctx context.Context, arg GetKeyResultInProjectParams) (GetKeyResultInProjectRow, error) {
	row := q.db.QueryRow(ctx, getKeyResultInProject, arg.ID, arg.ProjectID)
	var i GetKeyResultInProjectRow
	err := row.Scan(
		&i.ID,
		&i.ObjectiveID,
		&i.Description,
		&i.Metric,
		&i.SortOrder,
		&i.CreatedAt,
		&i.CodeSeq,
		&i.CreatedBy,
		&i.ProjectID,
		&i.ObjectiveCodeSeq,
	)
	return i, err
}

const getTaskInProject = `-- name: GetTaskInProject :one
SELECT t.id, t.key_result_id, t.name, t.owner_id, t.start_date, t.end_date, t.status, t.created_by, t.created_at, t.progress, t.cancel_reason, t.description, t.completion_criteria, t.updated_at, t.receiver_scope, t.code_seq, t.result_update, o.project_id
FROM tasks t
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE t.id = $1 AND o.project_id = $2
`

type GetTaskInProjectParams struct {
	ID        int64
	ProjectID int64
}

type GetTaskInProjectRow struct {
	ID                 int64
	KeyResultID        int64
	Name               string
	OwnerID            int64
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	Status             string
	CreatedBy          int64
	CreatedAt          pgtype.Timestamptz
	Progress           pgtype.Int4
	CancelReason       string
	Description        string
	CompletionCriteria string
	UpdatedAt          pgtype.Timestamptz
	ReceiverScope      string
	CodeSeq            int32
	ResultUpdate       string
	ProjectID          int64
}

// 任务连同项目归属（用于权限判定与项目内寻址；裁决 12 #183 后 KR 无负责人）。
func (q *Queries) GetTaskInProject(ctx context.Context, arg GetTaskInProjectParams) (GetTaskInProjectRow, error) {
	row := q.db.QueryRow(ctx, getTaskInProject, arg.ID, arg.ProjectID)
	var i GetTaskInProjectRow
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Progress,
		&i.CancelReason,
		&i.Description,
		&i.CompletionCriteria,
		&i.UpdatedAt,
		&i.ReceiverScope,
		&i.CodeSeq,
		&i.ResultUpdate,
		&i.ProjectID,
	)
	return i, err
}

const listProjectTasks = `-- name: ListProjectTasks :many
SELECT t.id, t.key_result_id, t.name, t.owner_id, t.start_date, t.end_date, t.status, t.created_by, t.created_at, t.progress, t.cancel_reason, t.description, t.completion_criteria, t.updated_at, t.receiver_scope, t.code_seq, t.result_update, u.display_name AS owner_name, cu.display_name AS creator_name,
    k.code_seq AS kr_code_seq, o.code_seq AS objective_code_seq
FROM tasks t
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
JOIN users u ON u.id = t.owner_id
JOIN users cu ON cu.id = t.created_by
WHERE o.project_id = $1
ORDER BY t.id
`

type ListProjectTasksRow struct {
	ID                 int64
	KeyResultID        int64
	Name               string
	OwnerID            int64
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	Status             string
	CreatedBy          int64
	CreatedAt          pgtype.Timestamptz
	Progress           pgtype.Int4
	CancelReason       string
	Description        string
	CompletionCriteria string
	UpdatedAt          pgtype.Timestamptz
	ReceiverScope      string
	CodeSeq            int32
	ResultUpdate       string
	OwnerName          string
	CreatorName        string
	KrCodeSeq          int32
	ObjectiveCodeSeq   int32
}

// 项目全部任务，含负责人／创建人姓名（派生动作标志与待行动人在 domain 判定；裁决 12 后 KR 无负责人）。
func (q *Queries) ListProjectTasks(ctx context.Context, projectID int64) ([]ListProjectTasksRow, error) {
	rows, err := q.db.Query(ctx, listProjectTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectTasksRow
	for rows.Next() {
		var i ListProjectTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyResultID,
			&i.Name,
			&i.OwnerID,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Progress,
			&i.CancelReason,
			&i.Description,
			&i.CompletionCriteria,
			&i.UpdatedAt,
			&i.ReceiverScope,
			&i.CodeSeq,
			&i.ResultUpdate,
			&i.OwnerName,
			&i.CreatorName,
			&i.KrCodeSeq,
			&i.ObjectiveCodeSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskProgressByProject = `-- name: ListTaskProgressByProject :many
SELECT t.key_result_id, t.status, t.progress
FROM tasks t
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE o.project_id = $1
`

type ListTaskProgressByProjectRow struct {
	KeyResultID int64
	Status      string
	Progress    pgtype.Int4
}

// KR 层进度覆盖度的原始事实（状态与可选进度），聚合规则在 domain。
func (q *Queries) ListTaskProgressByProject(ctx context.Context, projectID int64) ([]ListTaskProgressByProjectRow, error) {
	rows, err := q.db.Query(ctx, listTaskProgressByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskProgressByProjectRow
	for rows.Next() {
		var i ListTaskProgressByProjectRow
		if err := rows.Scan(&i.KeyResultID, &i.Status, &i.Progress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskInProject = `-- name: LockTaskInProject :one
SELECT t.id, t.key_result_id, t.name, t.owner_id, t.start_date, t.end_date, t.status, t.created_by, t.created_at, t.progress, t.cancel_reason, t.description, t.completion_criteria, t.updated_at, t.receiver_scope, t.code_seq, t.result_update, o.project_id
FROM tasks t
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE t.id = $1 AND o.project_id = $2
FOR UPDATE OF t
`

type LockTaskInProjectParams struct {
	ID        int64
	ProjectID int64
}

type LockTaskInProjectRow struct {
	ID                 int64
	KeyResultID        int64
	Name               string
	OwnerID            int64
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	Status             string
	CreatedBy          int64
	CreatedAt          pgtype.Timestamptz
	Progress           pgtype.Int4
	CancelReason       string
	Description        string
	CompletionCriteria string
	UpdatedAt          pgtype.Timestamptz
	ReceiverScope      string
	CodeSeq            int32
	ResultUpdate       string
	ProjectID          int64
}

// 与 GetTaskInProject 同形，但对任务行加写锁：三道审批的决策必须在锁内重读状态、重跑规则，
// 否则并发决策（如或签一人通过、一人退回）会各自基于过期事实写库。
func (q *Queries) LockTaskInProject(ctx context.Context, arg LockTaskInProjectParams) (LockTaskInProjectRow, error) {
	row := q.db.QueryRow(ctx, lockTaskInProject, arg.ID, arg.ProjectID)
	var i LockTaskInProjectRow
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Progress,
		&i.CancelReason,
		&i.Description,
		&i.CompletionCriteria,
		&i.UpdatedAt,
		&i.ReceiverScope,
		&i.CodeSeq,
		&i.ResultUpdate,
		&i.ProjectID,
	)
	return i, err
}

const setTaskResultUpdate = `-- name: SetTaskResultUpdate :one
UPDATE tasks
SET result_update = $2, updated_at = now()
WHERE id = $1
RETURNING id, key_result_id, name, owner_id, start_date, end_date, status, created_by, created_at, progress, cancel_reason, description, completion_criteria, updated_at, receiver_scope, code_seq, result_update
`

type SetTaskResultUpdateParams struct {
	ID           int64
	ResultUpdate string
}

// 成果更新进程流转（AC-66）：发起→open，提交完成申请→reviewing，终审通过或退回→”。
// 任务生命周期状态不在这里动。
func (q *Queries) SetTaskResultUpdate(ctx context.Context, arg SetTaskResultUpdateParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskResultUpdate, arg.ID, arg.ResultUpdate)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Progress,
		&i.CancelReason,
		&i.Description,
		&i.CompletionCriteria,
		&i.UpdatedAt,
		&i.ReceiverScope,
		&i.CodeSeq,
		&i.ResultUpdate,
	)
	return i, err
}

const updateTaskProgress = `-- name: UpdateTaskProgress :one
UPDATE tasks
SET progress = $2, updated_at = now()
WHERE id = $1
RETURNING id, key_result_id, name, owner_id, start_date, end_date, status, created_by, created_at, progress, cancel_reason, description, completion_criteria, updated_at, receiver_scope, code_seq, result_update
`

type UpdateTaskProgressParams struct {
	ID       int64
	Progress pgtype.Int4
}

func (q *Queries) UpdateTaskProgress(ctx context.Context, arg UpdateTaskProgressParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskProgress, arg.ID, arg.Progress)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Progress,
		&i.CancelReason,
		&i.Description,
		&i.CompletionCriteria,
		&i.UpdatedAt,
		&i.ReceiverScope,
		&i.CodeSeq,
		&i.ResultUpdate,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, key_result_id, name, owner_id, start_date, end_date, status, created_by, created_at, progress, cancel_reason, description, completion_criteria, updated_at, receiver_scope, code_seq, result_update
`

type UpdateTaskStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Progress,
		&i.CancelReason,
		&i.Description,
		&i.CompletionCriteria,
		&i.UpdatedAt,
		&i.ReceiverScope,
		&i.CodeSeq,
		&i.ResultUpdate,
	)
	return i, err
}

const updateTaskStatusWithReason = `-- name: UpdateTaskStatusWithReason :one
UPDATE tasks
SET status = $2, cancel_reason = $3, updated_at = now()
WHERE id = $1
RETURNING id, key_result_id, name, owner_id, start_date, end_date, status, created_by, created_at, progress, cancel_reason, description, completion_criteria, updated_at, receiver_scope, code_seq, result_update
`

type UpdateTaskStatusWithReasonParams struct {
	ID           int64
	Status       string
	CancelReason string
}

func (q *Queries) UpdateTaskStatusWithReason(ctx context.Context, arg UpdateTaskStatusWithReasonParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatusWithReason, arg.ID, arg.Status, arg.CancelReason)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Progress,
		&i.CancelReason,
		&i.Description,
		&i.CompletionCriteria,
		&i.UpdatedAt,
		&i.ReceiverScope,
		&i.CodeSeq,
		&i.ResultUpdate,
	)
	return i, err
}
