// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPoolReview = `-- name: CreatePoolReview :one
INSERT INTO pool_reviews (task_id, submitted_by, status, exempt, opinion, decided_by, decided_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, task_id, submitted_by, status, exempt, opinion, submitted_at, decided_by, decided_at
`

type CreatePoolReviewParams struct {
	TaskID      int64
	SubmittedBy int64
	Status      string
	Exempt      bool
	Opinion     string
	DecidedBy   pgtype.Int8
	DecidedAt   pgtype.Timestamptz
}

func (q *Queries) CreatePoolReview(ctx context.Context, arg CreatePoolReviewParams) (PoolReview, error) {
	row := q.db.QueryRow(ctx, createPoolReview,
		arg.TaskID,
		arg.SubmittedBy,
		arg.Status,
		arg.Exempt,
		arg.Opinion,
		arg.DecidedBy,
		arg.DecidedAt,
	)
	var i PoolReview
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubmittedBy,
		&i.Status,
		&i.Exempt,
		&i.Opinion,
		&i.SubmittedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (key_result_id, name, owner_id, start_date, end_date, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, key_result_id, name, owner_id, start_date, end_date, status, created_by, created_at
`

type CreateTaskParams struct {
	KeyResultID int64
	Name        string
	OwnerID     int64
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Status      string
	CreatedBy   int64
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.KeyResultID,
		arg.Name,
		arg.OwnerID,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const decidePoolReview = `-- name: DecidePoolReview :one
UPDATE pool_reviews
SET status = $2, opinion = $3, decided_by = $4, decided_at = now()
WHERE id = $1
RETURNING id, task_id, submitted_by, status, exempt, opinion, submitted_at, decided_by, decided_at
`

type DecidePoolReviewParams struct {
	ID        int64
	Status    string
	Opinion   string
	DecidedBy pgtype.Int8
}

func (q *Queries) DecidePoolReview(ctx context.Context, arg DecidePoolReviewParams) (PoolReview, error) {
	row := q.db.QueryRow(ctx, decidePoolReview,
		arg.ID,
		arg.Status,
		arg.Opinion,
		arg.DecidedBy,
	)
	var i PoolReview
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubmittedBy,
		&i.Status,
		&i.Exempt,
		&i.Opinion,
		&i.SubmittedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const getKeyResultInProject = `-- name: GetKeyResultInProject :one
SELECT k.id, k.objective_id, k.description, k.metric, k.owner_id, k.start_date, k.end_date, k.risk_level, k.sort_order, k.created_at, o.project_id
FROM key_results k
JOIN objectives o ON o.id = k.objective_id
WHERE k.id = $1 AND o.project_id = $2
`

type GetKeyResultInProjectParams struct {
	ID        int64
	ProjectID int64
}

type GetKeyResultInProjectRow struct {
	ID          int64
	ObjectiveID int64
	Description string
	Metric      string
	OwnerID     pgtype.Int8
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	RiskLevel   string
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
	ProjectID   int64
}

// KR 连同项目归属（任务创建时校验所属 KR 属于本项目）。
func (q *Queries) GetKeyResultInProject(ctx context.Context, arg GetKeyResultInProjectParams) (GetKeyResultInProjectRow, error) {
	row := q.db.QueryRow(ctx, getKeyResultInProject, arg.ID, arg.ProjectID)
	var i GetKeyResultInProjectRow
	err := row.Scan(
		&i.ID,
		&i.ObjectiveID,
		&i.Description,
		&i.Metric,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.RiskLevel,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ProjectID,
	)
	return i, err
}

const getLatestPoolReview = `-- name: GetLatestPoolReview :one
SELECT id, task_id, submitted_by, status, exempt, opinion, submitted_at, decided_by, decided_at FROM pool_reviews
WHERE task_id = $1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestPoolReview(ctx context.Context, taskID int64) (PoolReview, error) {
	row := q.db.QueryRow(ctx, getLatestPoolReview, taskID)
	var i PoolReview
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SubmittedBy,
		&i.Status,
		&i.Exempt,
		&i.Opinion,
		&i.SubmittedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const getTaskInProject = `-- name: GetTaskInProject :one
SELECT t.id, t.key_result_id, t.name, t.owner_id, t.start_date, t.end_date, t.status, t.created_by, t.created_at, k.owner_id AS kr_owner_id, o.project_id
FROM tasks t
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
WHERE t.id = $1 AND o.project_id = $2
`

type GetTaskInProjectParams struct {
	ID        int64
	ProjectID int64
}

type GetTaskInProjectRow struct {
	ID          int64
	KeyResultID int64
	Name        string
	OwnerID     int64
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Status      string
	CreatedBy   int64
	CreatedAt   pgtype.Timestamptz
	KrOwnerID   pgtype.Int8
	ProjectID   int64
}

// 任务连同所属 KR 负责人与项目归属（用于权限判定与项目内寻址）。
func (q *Queries) GetTaskInProject(ctx context.Context, arg GetTaskInProjectParams) (GetTaskInProjectRow, error) {
	row := q.db.QueryRow(ctx, getTaskInProject, arg.ID, arg.ProjectID)
	var i GetTaskInProjectRow
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.KrOwnerID,
		&i.ProjectID,
	)
	return i, err
}

const latestPoolReviewsByProject = `-- name: LatestPoolReviewsByProject :many
SELECT DISTINCT ON (pr.task_id) pr.id, pr.task_id, pr.submitted_by, pr.status, pr.exempt, pr.opinion, pr.submitted_at, pr.decided_by, pr.decided_at,
    su.display_name AS submitted_by_name,
    du.display_name AS decided_by_name
FROM pool_reviews pr
JOIN tasks t ON t.id = pr.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
JOIN users su ON su.id = pr.submitted_by
LEFT JOIN users du ON du.id = pr.decided_by
WHERE o.project_id = $1
ORDER BY pr.task_id, pr.id DESC
`

type LatestPoolReviewsByProjectRow struct {
	ID              int64
	TaskID          int64
	SubmittedBy     int64
	Status          string
	Exempt          bool
	Opinion         string
	SubmittedAt     pgtype.Timestamptz
	DecidedBy       pgtype.Int8
	DecidedAt       pgtype.Timestamptz
	SubmittedByName string
	DecidedByName   pgtype.Text
}

// 每个任务最近一次入池审批单，连同提交人／处理人姓名（列表展示用）。
func (q *Queries) LatestPoolReviewsByProject(ctx context.Context, projectID int64) ([]LatestPoolReviewsByProjectRow, error) {
	rows, err := q.db.Query(ctx, latestPoolReviewsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestPoolReviewsByProjectRow
	for rows.Next() {
		var i LatestPoolReviewsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.SubmittedBy,
			&i.Status,
			&i.Exempt,
			&i.Opinion,
			&i.SubmittedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.SubmittedByName,
			&i.DecidedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasks = `-- name: ListProjectTasks :many
SELECT t.id, t.key_result_id, t.name, t.owner_id, t.start_date, t.end_date, t.status, t.created_by, t.created_at, u.display_name AS owner_name, k.owner_id AS kr_owner_id
FROM tasks t
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
JOIN users u ON u.id = t.owner_id
WHERE o.project_id = $1
ORDER BY t.id
`

type ListProjectTasksRow struct {
	ID          int64
	KeyResultID int64
	Name        string
	OwnerID     int64
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Status      string
	CreatedBy   int64
	CreatedAt   pgtype.Timestamptz
	OwnerName   string
	KrOwnerID   pgtype.Int8
}

// 项目全部任务，含负责人姓名与 KR 负责人（派生动作标志在 domain 判定）。
func (q *Queries) ListProjectTasks(ctx context.Context, projectID int64) ([]ListProjectTasksRow, error) {
	rows, err := q.db.Query(ctx, listProjectTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectTasksRow
	for rows.Next() {
		var i ListProjectTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyResultID,
			&i.Name,
			&i.OwnerID,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.OwnerName,
			&i.KrOwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2
WHERE id = $1
RETURNING id, key_result_id, name, owner_id, start_date, end_date, status, created_by, created_at
`

type UpdateTaskStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.KeyResultID,
		&i.Name,
		&i.OwnerID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
