// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_files.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitTaskFile = `-- name: CommitTaskFile :one
UPDATE task_files
SET state = 'ready', file_size = $2, uploaded_at = now()
WHERE id = $1 AND state = 'uploading'
RETURNING id, task_id, kind, state, file_name, file_type, file_size, object_key, note, uploaded_by, uploaded_at
`

type CommitTaskFileParams struct {
	ID       int64
	FileSize int64
}

// 确认上传：uploading → ready，并按对象存储的真实大小回填。
func (q *Queries) CommitTaskFile(ctx context.Context, arg CommitTaskFileParams) (TaskFile, error) {
	row := q.db.QueryRow(ctx, commitTaskFile, arg.ID, arg.FileSize)
	var i TaskFile
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.State,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.ObjectKey,
		&i.Note,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const createTaskFile = `-- name: CreateTaskFile :one
INSERT INTO task_files (task_id, kind, state, file_name, file_type, file_size, object_key, note, uploaded_by)
VALUES ($1, $2, 'uploading', $3, $4, $5, $6, $7, $8)
RETURNING id, task_id, kind, state, file_name, file_type, file_size, object_key, note, uploaded_by, uploaded_at
`

type CreateTaskFileParams struct {
	TaskID     int64
	Kind       string
	FileName   string
	FileType   string
	FileSize   int64
	ObjectKey  string
	Note       string
	UploadedBy int64
}

// 两阶段提交第一步：先落 uploading 记录，确认写入对象存储后才转 ready。
func (q *Queries) CreateTaskFile(ctx context.Context, arg CreateTaskFileParams) (TaskFile, error) {
	row := q.db.QueryRow(ctx, createTaskFile,
		arg.TaskID,
		arg.Kind,
		arg.FileName,
		arg.FileType,
		arg.FileSize,
		arg.ObjectKey,
		arg.Note,
		arg.UploadedBy,
	)
	var i TaskFile
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.State,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.ObjectKey,
		&i.Note,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const deleteStaleUploadingTaskFiles = `-- name: DeleteStaleUploadingTaskFiles :many
DELETE FROM task_files
WHERE state = 'uploading' AND uploaded_at < now() - $1::interval
RETURNING object_key
`

// 清理迟迟未确认的待上传记录（预签名地址已过期，客户端不会再来 commit）。
func (q *Queries) DeleteStaleUploadingTaskFiles(ctx context.Context, dollar_1 pgtype.Interval) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteStaleUploadingTaskFiles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTaskFile = `-- name: DeleteTaskFile :execrows
DELETE FROM task_files WHERE id = $1
`

func (q *Queries) DeleteTaskFile(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskFile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskFileInProject = `-- name: GetTaskFileInProject :one
SELECT tf.id, tf.task_id, tf.kind, tf.state, tf.file_name, tf.file_type, tf.file_size, tf.object_key, tf.note, tf.uploaded_by, tf.uploaded_at, u.display_name AS uploaded_by_name, t.owner_id AS task_owner_id,
    t.created_by AS task_created_by, t.status AS task_status
FROM task_files tf
JOIN tasks t ON t.id = tf.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
JOIN users u ON u.id = tf.uploaded_by
WHERE tf.id = $1 AND o.project_id = $2
`

type GetTaskFileInProjectParams struct {
	ID        int64
	ProjectID int64
}

type GetTaskFileInProjectRow struct {
	ID             int64
	TaskID         int64
	Kind           string
	State          string
	FileName       string
	FileType       string
	FileSize       int64
	ObjectKey      string
	Note           string
	UploadedBy     int64
	UploadedAt     pgtype.Timestamptz
	UploadedByName string
	TaskOwnerID    int64
	TaskCreatedBy  int64
	TaskStatus     string
}

func (q *Queries) GetTaskFileInProject(ctx context.Context, arg GetTaskFileInProjectParams) (GetTaskFileInProjectRow, error) {
	row := q.db.QueryRow(ctx, getTaskFileInProject, arg.ID, arg.ProjectID)
	var i GetTaskFileInProjectRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.State,
		&i.FileName,
		&i.FileType,
		&i.FileSize,
		&i.ObjectKey,
		&i.Note,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.UploadedByName,
		&i.TaskOwnerID,
		&i.TaskCreatedBy,
		&i.TaskStatus,
	)
	return i, err
}

const listTaskFilesByProject = `-- name: ListTaskFilesByProject :many
SELECT tf.id, tf.task_id, tf.kind, tf.state, tf.file_name, tf.file_type, tf.file_size, tf.object_key, tf.note, tf.uploaded_by, tf.uploaded_at, u.display_name AS uploaded_by_name
FROM task_files tf
JOIN tasks t ON t.id = tf.task_id
JOIN key_results k ON k.id = t.key_result_id
JOIN objectives o ON o.id = k.objective_id
JOIN users u ON u.id = tf.uploaded_by
WHERE o.project_id = $1 AND tf.state = 'ready'
ORDER BY tf.id
`

type ListTaskFilesByProjectRow struct {
	ID             int64
	TaskID         int64
	Kind           string
	State          string
	FileName       string
	FileType       string
	FileSize       int64
	ObjectKey      string
	Note           string
	UploadedBy     int64
	UploadedAt     pgtype.Timestamptz
	UploadedByName string
}

func (q *Queries) ListTaskFilesByProject(ctx context.Context, projectID int64) ([]ListTaskFilesByProjectRow, error) {
	rows, err := q.db.Query(ctx, listTaskFilesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskFilesByProjectRow
	for rows.Next() {
		var i ListTaskFilesByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.State,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.ObjectKey,
			&i.Note,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskFilesByTask = `-- name: ListTaskFilesByTask :many
SELECT tf.id, tf.task_id, tf.kind, tf.state, tf.file_name, tf.file_type, tf.file_size, tf.object_key, tf.note, tf.uploaded_by, tf.uploaded_at, u.display_name AS uploaded_by_name
FROM task_files tf
JOIN users u ON u.id = tf.uploaded_by
WHERE tf.task_id = $1 AND tf.state = 'ready'
ORDER BY tf.id
`

type ListTaskFilesByTaskRow struct {
	ID             int64
	TaskID         int64
	Kind           string
	State          string
	FileName       string
	FileType       string
	FileSize       int64
	ObjectKey      string
	Note           string
	UploadedBy     int64
	UploadedAt     pgtype.Timestamptz
	UploadedByName string
}

// 已确认写入的过程文件与外部材料；uploading 记录不参与任何展示。
func (q *Queries) ListTaskFilesByTask(ctx context.Context, taskID int64) ([]ListTaskFilesByTaskRow, error) {
	rows, err := q.db.Query(ctx, listTaskFilesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskFilesByTaskRow
	for rows.Next() {
		var i ListTaskFilesByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.State,
			&i.FileName,
			&i.FileType,
			&i.FileSize,
			&i.ObjectKey,
			&i.Note,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
