// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, password_hash, is_system_admin, email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, display_name, password_hash, created_at, is_system_admin, email
`

type CreateUserParams struct {
	Username      string
	DisplayName   string
	PasswordHash  string
	IsSystemAdmin bool
	Email         string
}

// email 由调用方先经 domain.NormalizeEmail／ValidateEmail；重复由唯一索引兜底（#202）。
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsSystemAdmin,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsSystemAdmin,
		&i.Email,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, display_name, password_hash, created_at, is_system_admin, email FROM users WHERE lower(email) = lower($1)
`

// #202：邮箱大小写不敏感（唯一索引建在 lower(email) 上）。
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsSystemAdmin,
		&i.Email,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, password_hash, created_at, is_system_admin, email FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsSystemAdmin,
		&i.Email,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, created_at, is_system_admin, email FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsSystemAdmin,
		&i.Email,
	)
	return i, err
}

const listSystemUsers = `-- name: ListSystemUsers :many
SELECT id, username, display_name, email, is_system_admin, created_at FROM users ORDER BY id
`

type ListSystemUsersRow struct {
	ID            int64
	Username      string
	DisplayName   string
	Email         string
	IsSystemAdmin bool
	CreatedAt     pgtype.Timestamptz
}

// #201：系统设置 → 用户管理列表（仅系统管理员）。
func (q *Queries) ListSystemUsers(ctx context.Context) ([]ListSystemUsersRow, error) {
	rows, err := q.db.Query(ctx, listSystemUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSystemUsersRow
	for rows.Next() {
		var i ListSystemUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.IsSystemAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, email FROM users ORDER BY id
`

type ListUsersRow struct {
	ID          int64
	Username    string
	DisplayName string
	Email       string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserSystemAdmin = `-- name: SetUserSystemAdmin :one
UPDATE users SET is_system_admin = $2 WHERE id = $1
RETURNING id, username, display_name, password_hash, created_at, is_system_admin, email
`

type SetUserSystemAdminParams struct {
	ID            int64
	IsSystemAdmin bool
}

// #200：设／撤系统管理员标记（CLI usermod；界面入口见 #205）。
func (q *Queries) SetUserSystemAdmin(ctx context.Context, arg SetUserSystemAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserSystemAdmin, arg.ID, arg.IsSystemAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsSystemAdmin,
		&i.Email,
	)
	return i, err
}
