//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DeliverableFileState.
const (
	Candidate DeliverableFileState = "candidate"
	Current   DeliverableFileState = "current"
)

// Valid indicates whether the value is a known member of the DeliverableFileState enum.
func (e DeliverableFileState) Valid() bool {
	switch e {
	case Candidate:
		return true
	case Current:
		return true
	default:
		return false
	}
}

// Defines values for FieldChangeDecisionRequestDecision.
const (
	FieldChangeDecisionRequestDecisionApproved FieldChangeDecisionRequestDecision = "approved"
	FieldChangeDecisionRequestDecisionRejected FieldChangeDecisionRequestDecision = "rejected"
)

// Valid indicates whether the value is a known member of the FieldChangeDecisionRequestDecision enum.
func (e FieldChangeDecisionRequestDecision) Valid() bool {
	switch e {
	case FieldChangeDecisionRequestDecisionApproved:
		return true
	case FieldChangeDecisionRequestDecisionRejected:
		return true
	default:
		return false
	}
}

// Defines values for FieldChangeState.
const (
	FieldChangeStateApproved FieldChangeState = "approved"
	FieldChangeStatePending  FieldChangeState = "pending"
	FieldChangeStateRejected FieldChangeState = "rejected"
)

// Valid indicates whether the value is a known member of the FieldChangeState enum.
func (e FieldChangeState) Valid() bool {
	switch e {
	case FieldChangeStateApproved:
		return true
	case FieldChangeStatePending:
		return true
	case FieldChangeStateRejected:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MemberRole.
const (
	Admin  MemberRole = "admin"
	Member MemberRole = "member"
	Viewer MemberRole = "viewer"
)

// Valid indicates whether the value is a known member of the MemberRole enum.
func (e MemberRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for PoolReviewDecisionRequestDecision.
const (
	PoolReviewDecisionRequestDecisionApproved PoolReviewDecisionRequestDecision = "approved"
	PoolReviewDecisionRequestDecisionRejected PoolReviewDecisionRequestDecision = "rejected"
)

// Valid indicates whether the value is a known member of the PoolReviewDecisionRequestDecision enum.
func (e PoolReviewDecisionRequestDecision) Valid() bool {
	switch e {
	case PoolReviewDecisionRequestDecisionApproved:
		return true
	case PoolReviewDecisionRequestDecisionRejected:
		return true
	default:
		return false
	}
}

// Defines values for PoolReviewStatus.
const (
	PoolReviewStatusApproved PoolReviewStatus = "approved"
	PoolReviewStatusPending  PoolReviewStatus = "pending"
	PoolReviewStatusRejected PoolReviewStatus = "rejected"
)

// Valid indicates whether the value is a known member of the PoolReviewStatus enum.
func (e PoolReviewStatus) Valid() bool {
	switch e {
	case PoolReviewStatusApproved:
		return true
	case PoolReviewStatusPending:
		return true
	case PoolReviewStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for ProjectStatus.
const (
	ProjectStatusArchived   ProjectStatus = "archived"
	ProjectStatusCompleted  ProjectStatus = "completed"
	ProjectStatusInProgress ProjectStatus = "in_progress"
	ProjectStatusNotStarted ProjectStatus = "not_started"
)

// Valid indicates whether the value is a known member of the ProjectStatus enum.
func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusArchived:
		return true
	case ProjectStatusCompleted:
		return true
	case ProjectStatusInProgress:
		return true
	case ProjectStatusNotStarted:
		return true
	default:
		return false
	}
}

// Defines values for RiskLevel.
const (
	HighRisk RiskLevel = "high_risk"
	Normal   RiskLevel = "normal"
	Warning  RiskLevel = "warning"
)

// Valid indicates whether the value is a known member of the RiskLevel enum.
func (e RiskLevel) Valid() bool {
	switch e {
	case HighRisk:
		return true
	case Normal:
		return true
	case Warning:
		return true
	default:
		return false
	}
}

// Defines values for TaskInviteState.
const (
	TaskInviteStateCompleted TaskInviteState = "completed"
	TaskInviteStatePending   TaskInviteState = "pending"
	TaskInviteStateRevoked   TaskInviteState = "revoked"
)

// Valid indicates whether the value is a known member of the TaskInviteState enum.
func (e TaskInviteState) Valid() bool {
	switch e {
	case TaskInviteStateCompleted:
		return true
	case TaskInviteStatePending:
		return true
	case TaskInviteStateRevoked:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusCancelled                 TaskStatus = "cancelled"
	TaskStatusCompleted                 TaskStatus = "completed"
	TaskStatusDraft                     TaskStatus = "draft"
	TaskStatusInProgress                TaskStatus = "in_progress"
	TaskStatusNotStarted                TaskStatus = "not_started"
	TaskStatusPendingFinalReview        TaskStatus = "pending_final_review"
	TaskStatusPendingIntermediateReview TaskStatus = "pending_intermediate_review"
	TaskStatusPendingPoolReview         TaskStatus = "pending_pool_review"
	TaskStatusWaitingInput              TaskStatus = "waiting_input"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusCancelled:
		return true
	case TaskStatusCompleted:
		return true
	case TaskStatusDraft:
		return true
	case TaskStatusInProgress:
		return true
	case TaskStatusNotStarted:
		return true
	case TaskStatusPendingFinalReview:
		return true
	case TaskStatusPendingIntermediateReview:
		return true
	case TaskStatusPendingPoolReview:
		return true
	case TaskStatusWaitingInput:
		return true
	default:
		return false
	}
}

// Defines values for UpdateTaskStatusRequestStatus.
const (
	UpdateTaskStatusRequestStatusCancelled  UpdateTaskStatusRequestStatus = "cancelled"
	UpdateTaskStatusRequestStatusInProgress UpdateTaskStatusRequestStatus = "in_progress"
)

// Valid indicates whether the value is a known member of the UpdateTaskStatusRequestStatus enum.
func (e UpdateTaskStatusRequestStatus) Valid() bool {
	switch e {
	case UpdateTaskStatusRequestStatusCancelled:
		return true
	case UpdateTaskStatusRequestStatusInProgress:
		return true
	default:
		return false
	}
}

// AddProjectMemberRequest defines model for AddProjectMemberRequest.
type AddProjectMemberRequest struct {
	// Role 成员角色（项目管理员／普通成员／只读成员），见词汇表「成员角色」
	Role   MemberRole `json:"role"`
	UserId int64      `json:"userId"`
}

// CreateDeliverableRequest defines model for CreateDeliverableRequest.
type CreateDeliverableRequest struct {
	Name string `json:"name"`
}

// CreateDiscussionRequest defines model for CreateDiscussionRequest.
type CreateDiscussionRequest struct {
	Content string `json:"content"`

	// MentionUserIds 被 @ 的项目成员
	MentionUserIds *[]int64 `json:"mentionUserIds,omitempty"`
}

// CreateKeyResultInput defines model for CreateKeyResultInput.
type CreateKeyResultInput struct {
	Description string              `json:"description"`
	EndDate     *openapi_types.Date `json:"endDate,omitempty"`
	Metric      *string             `json:"metric,omitempty"`

	// OwnerId KR 负责人，必须是项目成员
	OwnerId   *int64              `json:"ownerId,omitempty"`
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
}

// CreateOkrBatchItem 二选一：填 title（可带 description）新建 O，或填 objectiveId 向已有 O 追加 KR（此时 keyResults 至少一条）
type CreateOkrBatchItem struct {
	Description *string                 `json:"description,omitempty"`
	KeyResults  *[]CreateKeyResultInput `json:"keyResults,omitempty"`
	ObjectiveId *int64                  `json:"objectiveId,omitempty"`
	Title       *string                 `json:"title,omitempty"`
}

// CreateOkrBatchRequest defines model for CreateOkrBatchRequest.
type CreateOkrBatchRequest struct {
	Items []CreateOkrBatchItem `json:"items"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Name             string              `json:"name"`
	OwnerId          int64               `json:"ownerId"`
	PlannedEndDate   *openapi_types.Date `json:"plannedEndDate,omitempty"`
	PlannedStartDate *openapi_types.Date `json:"plannedStartDate,omitempty"`
	Stage            *string             `json:"stage,omitempty"`
}

// CreateTaskBatchRequest defines model for CreateTaskBatchRequest.
type CreateTaskBatchRequest struct {
	Items []CreateTaskItem `json:"items"`

	// SubmitForReview true 时保存后立即提交各自所属 KR 的入池审批（原型「提交入池审批」按钮）；KR 负责人本人创建的任务始终免审直接进入未开始
	SubmitForReview bool `json:"submitForReview"`

	// TaskInviteId 通过任务创建邀请响应时携带（AC-03）；须为发给当前用户的待处理邀请，且本批至少一项任务属于邀请指定的 KR 并提交入池，成功后邀请变为已完成
	TaskInviteId *int64 `json:"taskInviteId,omitempty"`
}

// CreateTaskInvitesRequest defines model for CreateTaskInvitesRequest.
type CreateTaskInvitesRequest struct {
	// InviteeIds 受邀成员（可多选；须为非只读项目成员，不能邀请自己）
	InviteeIds  []int64 `json:"inviteeIds"`
	KeyResultId int64   `json:"keyResultId"`

	// Note 邀请说明，随站内通知一同展示
	Note *string `json:"note,omitempty"`
}

// CreateTaskItem defines model for CreateTaskItem.
type CreateTaskItem struct {
	EndDate openapi_types.Date `json:"endDate"`

	// ExpectedDeliverable 预期交付物名称（选填，原型创建弹窗列）；随任务创建对应交付物项
	ExpectedDeliverable *string `json:"expectedDeliverable,omitempty"`
	KeyResultId         int64   `json:"keyResultId"`
	Name                string  `json:"name"`

	// OwnerId 任务负责人，必须是项目成员
	OwnerId   int64              `json:"ownerId"`
	StartDate openapi_types.Date `json:"startDate"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	DisplayName string `json:"displayName"`
	Id          int64  `json:"id"`
	Username    string `json:"username"`
}

// Deliverable 交付物项：至多一份当前内容与一份候选内容，无版本号与历史（PRD §5.3）
type Deliverable struct {
	// Candidate 交付物内容（词汇表「交付物」；当前已生效或候选审核中）
	Candidate *DeliverableFile `json:"candidate,omitempty"`

	// Current 交付物内容（词汇表「交付物」；当前已生效或候选审核中）
	Current *DeliverableFile `json:"current,omitempty"`
	Id      int64            `json:"id"`
	Name    string           `json:"name"`
	TaskId  int64            `json:"taskId"`
}

// DeliverableFile 交付物内容（词汇表「交付物」；当前已生效或候选审核中）
type DeliverableFile struct {
	// EffectiveAt 当前内容的生效时间（终审通过时刻）
	EffectiveAt *time.Time `json:"effectiveAt,omitempty"`
	FileName    string     `json:"fileName"`

	// FileSize 字节数
	FileSize   *int64               `json:"fileSize,omitempty"`
	FileType   *string              `json:"fileType,omitempty"`
	Id         int64                `json:"id"`
	State      DeliverableFileState `json:"state"`
	UploadedAt *time.Time           `json:"uploadedAt,omitempty"`

	// UploadedByName 提交人姓名（派生字段）
	UploadedByName *string `json:"uploadedByName,omitempty"`
}

// DeliverableFileState defines model for DeliverableFile.State.
type DeliverableFileState string

// Discussion 任务讨论意见（词汇表「任务讨论」）；提交后不可编辑或删除
type Discussion struct {
	AuthorId   int64     `json:"authorId"`
	AuthorName string    `json:"authorName"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"createdAt"`
	Id         int64     `json:"id"`

	// MentionNames 被 @ 成员姓名（派生字段）
	MentionNames *[]string `json:"mentionNames,omitempty"`
	TaskId       int64     `json:"taskId"`
}

// DownloadUrlResponse defines model for DownloadUrlResponse.
type DownloadUrlResponse struct {
	// Url MinIO 预签名 GET 地址（预览/下载）
	Url string `json:"url"`
}

// Error defines model for Error.
type Error struct {
	// Code 机器可读错误码
	Code string `json:"code"`

	// Message 面向用户的错误说明
	Message string `json:"message"`
}

// FieldChange 关键字段变更单（词汇表）；rejected 且 resolved=false 即「退回待处理事项」
type FieldChange struct {
	// CanAbandon 当前用户能否放弃本次变更（派生字段；退回未处理且为提交人／可编辑项目者）
	CanAbandon *bool `json:"canAbandon,omitempty"`

	// CanDecide 当前用户能否处理本变更单（派生字段；仅所属 KR 负责人且待审批）
	CanDecide     *bool             `json:"canDecide,omitempty"`
	Changes       []FieldChangeDiff `json:"changes"`
	DecidedAt     *time.Time        `json:"decidedAt,omitempty"`
	DecidedByName *string           `json:"decidedByName,omitempty"`

	// Exempt KR 负责人本人修改免审即时生效时由系统标记
	Exempt bool  `json:"exempt"`
	Id     int64 `json:"id"`

	// Opinion 审批意见
	Opinion *string `json:"opinion,omitempty"`

	// Reason 修改原因
	Reason string `json:"reason"`

	// Resolved 退回后是否已处理（重新提交或放弃）
	Resolved        bool             `json:"resolved"`
	State           FieldChangeState `json:"state"`
	SubmittedAt     *time.Time       `json:"submittedAt,omitempty"`
	SubmittedById   *int64           `json:"submittedById,omitempty"`
	SubmittedByName *string          `json:"submittedByName,omitempty"`
}

// FieldChangeDecisionRequest defines model for FieldChangeDecisionRequest.
type FieldChangeDecisionRequest struct {
	Decision FieldChangeDecisionRequestDecision `json:"decision"`
	Opinion  *string                            `json:"opinion,omitempty"`
}

// FieldChangeDecisionRequestDecision defines model for FieldChangeDecisionRequest.Decision.
type FieldChangeDecisionRequestDecision string

// FieldChangeDiff 单个关键字段的修改前后差异（展示用字符串）
type FieldChangeDiff struct {
	// Field 字段名（name／description／completionCriteria／ownerId／endDate）
	Field string `json:"field"`

	// Label 中文字段名（派生字段）
	Label    string `json:"label"`
	NewValue string `json:"newValue"`
	OldValue string `json:"oldValue"`
}

// FieldChangeState defines model for FieldChangeState.
type FieldChangeState string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// KeyResult defines model for KeyResult.
type KeyResult struct {
	// Description KR 描述
	Description string `json:"description"`

	// EndDate 周期截止日期
	EndDate *openapi_types.Date `json:"endDate,omitempty"`
	Id      int64               `json:"id"`

	// Metric 量化指标，选填
	Metric      *string `json:"metric,omitempty"`
	ObjectiveId int64   `json:"objectiveId"`

	// OwnerId KR 负责人（项目成员，选填；工作职责而非权限级别）
	OwnerId *int64 `json:"ownerId,omitempty"`

	// OwnerName KR 负责人姓名（派生字段）
	OwnerName *string `json:"ownerName,omitempty"`

	// ProgressSummary KR 层进度数据覆盖度（词汇表「进度数据覆盖度」）；只统计已入池且未取消的任务，平均值任务等权
	ProgressSummary *ProgressSummary `json:"progressSummary,omitempty"`

	// RiskLevel 风险等级（正常／预警／高风险），见词汇表「风险等级」；不由任务生命周期状态自动推导
	RiskLevel RiskLevel `json:"riskLevel"`
	SortOrder int       `json:"sortOrder"`

	// StartDate 周期开始日期
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// MemberRole 成员角色（项目管理员／普通成员／只读成员），见词汇表「成员角色」
type MemberRole string

// Notification 站内通知（词汇表「站内通知」）
type Notification struct {
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`

	// Kind 通知类型（discussion_mention／discussion_owner 等）
	Kind      string     `json:"kind"`
	ProjectId *int64     `json:"projectId,omitempty"`
	ReadAt    *time.Time `json:"readAt,omitempty"`
	TaskId    *int64     `json:"taskId,omitempty"`
}

// Objective defines model for Objective.
type Objective struct {
	// Description O 说明，选填
	Description *string     `json:"description,omitempty"`
	Id          int64       `json:"id"`
	KeyResults  []KeyResult `json:"keyResults"`
	ProjectId   int64       `json:"projectId"`
	SortOrder   int         `json:"sortOrder"`

	// Title O 标题
	Title string `json:"title"`
}

// PoolReview 任务最近一次入池审批单
type PoolReview struct {
	DecidedAt *time.Time `json:"decidedAt,omitempty"`

	// DecidedByName 处理人姓名（派生字段）
	DecidedByName *string `json:"decidedByName,omitempty"`

	// Exempt KR 负责人本人创建免审时由系统自动生成并标记（AC-26）
	Exempt bool `json:"exempt"`

	// Opinion 审批意见；免审时为系统记录的免审原因
	Opinion *string `json:"opinion,omitempty"`

	// Status 入池审批单状态（词汇表「入池审批单」）；未提交即无审批单
	Status      PoolReviewStatus `json:"status"`
	SubmittedAt *time.Time       `json:"submittedAt,omitempty"`

	// SubmittedByName 提交人姓名（派生字段）
	SubmittedByName *string `json:"submittedByName,omitempty"`
}

// PoolReviewDecisionRequest defines model for PoolReviewDecisionRequest.
type PoolReviewDecisionRequest struct {
	Decision PoolReviewDecisionRequestDecision `json:"decision"`
	Opinion  *string                           `json:"opinion,omitempty"`
}

// PoolReviewDecisionRequestDecision defines model for PoolReviewDecisionRequest.Decision.
type PoolReviewDecisionRequestDecision string

// PoolReviewStatus 入池审批单状态（词汇表「入池审批单」）；未提交即无审批单
type PoolReviewStatus string

// ProgressSummary KR 层进度数据覆盖度（词汇表「进度数据覆盖度」）；只统计已入池且未取消的任务，平均值任务等权
type ProgressSummary struct {
	// AverageProgress 已填写任务的等权平均（四舍五入）；无已填任务时不返回
	AverageProgress *int `json:"averageProgress,omitempty"`
	FilledTasks     int  `json:"filledTasks"`
	TotalTasks      int  `json:"totalTasks"`
}

// Project defines model for Project.
type Project struct {
	// CanEdit 当前用户能否编辑本项目（派生字段，按成员角色与项目负责人身份在 domain 层判定）
	CanEdit bool `json:"canEdit"`

	// CanManageMembers 当前用户能否管理本项目成员和权限（派生字段，同上）
	CanManageMembers bool      `json:"canManageMembers"`
	CreatedAt        time.Time `json:"createdAt"`
	Id               int64     `json:"id"`
	Name             string    `json:"name"`

	// OwnerId 项目负责人（单人；与项目管理员为独立角色）
	OwnerId int64 `json:"ownerId"`

	// OwnerName 项目负责人姓名（派生字段，前端直接展示）
	OwnerName        string              `json:"ownerName"`
	PlannedEndDate   *openapi_types.Date `json:"plannedEndDate,omitempty"`
	PlannedStartDate *openapi_types.Date `json:"plannedStartDate,omitempty"`

	// Stage 业务里程碑标签，自由文本，选填
	Stage *string `json:"stage,omitempty"`

	// Status 项目状态（未开始／进行中／已完成／已归档），与自由文本“阶段”正交
	Status ProjectStatus `json:"status"`
}

// ProjectMember defines model for ProjectMember.
type ProjectMember struct {
	DisplayName string `json:"displayName"`

	// Role 成员角色（项目管理员／普通成员／只读成员），见词汇表「成员角色」
	Role     MemberRole `json:"role"`
	UserId   int64      `json:"userId"`
	Username string     `json:"username"`
}

// ProjectStatus 项目状态（未开始／进行中／已完成／已归档），与自由文本“阶段”正交
type ProjectStatus string

// RiskLevel 风险等级（正常／预警／高风险），见词汇表「风险等级」；不由任务生命周期状态自动推导
type RiskLevel string

// SubmitFieldChangeRequest defines model for SubmitFieldChangeRequest.
type SubmitFieldChangeRequest struct {
	// Changes 拟议值；至少一项。草稿任务直接生效；KR 负责人改本人 KR 下任务免审即时生效
	Changes struct {
		CompletionCriteria *string             `json:"completionCriteria,omitempty"`
		Description        *string             `json:"description,omitempty"`
		EndDate            *openapi_types.Date `json:"endDate,omitempty"`
		Name               *string             `json:"name,omitempty"`
		OwnerId            *int64              `json:"ownerId,omitempty"`
	} `json:"changes"`

	// Reason 修改原因；进入审批（含免审留痕）时必填，草稿直接完善可不填
	Reason *string `json:"reason,omitempty"`
}

// Task defines model for Task.
type Task struct {
	// CanCancel 当前用户能否取消本任务（派生字段；负责人／创建人／可编辑项目者，非终态）
	CanCancel bool `json:"canCancel"`

	// CanDecidePoolReview 当前用户能否处理本任务的入池审批（派生字段；仅所属 KR 负责人）
	CanDecidePoolReview bool `json:"canDecidePoolReview"`

	// CanManageDeliverables 当前用户能否配置任务交付物项（派生字段；负责人／创建人／可编辑项目者，非终态）
	CanManageDeliverables *bool `json:"canManageDeliverables,omitempty"`

	// CanProposeFieldChange 当前用户能否编辑任务／提交关键字段修改（派生字段）
	CanProposeFieldChange bool `json:"canProposeFieldChange"`

	// CanStart 当前用户能否开始执行本任务（派生字段；负责人／可编辑项目者，未开始或等待输入时）
	CanStart bool `json:"canStart"`

	// CanSubmitPoolReview 当前用户能否提交本任务入池（派生字段；草稿且为创建人／负责人／可编辑项目者）
	CanSubmitPoolReview bool `json:"canSubmitPoolReview"`

	// CanUpdateProgress 当前用户能否更新本任务进度（派生字段；负责人／可编辑项目者，执行中状态）
	CanUpdateProgress bool `json:"canUpdateProgress"`

	// CanUploadCandidate 当前用户能否登记候选交付物内容（派生字段；负责人，执行类状态）
	CanUploadCandidate *bool `json:"canUploadCandidate,omitempty"`

	// CancelReason 取消原因（已取消任务保留，PRD §5.1）
	CancelReason *string `json:"cancelReason,omitempty"`

	// CompletionCriteria 完成标准，选填
	CompletionCriteria *string `json:"completionCriteria,omitempty"`

	// CurrentStage 当前环节（词汇表「当前环节」；中文标签，派生字段）
	CurrentStage string `json:"currentStage"`

	// DeliverableNames 交付物项名称列表（列表「预期交付物」列展示用，派生字段）
	DeliverableNames *[]string `json:"deliverableNames,omitempty"`

	// Description 任务说明，选填
	Description *string            `json:"description,omitempty"`
	EndDate     openapi_types.Date `json:"endDate"`

	// FieldChange 关键字段变更单（词汇表）；rejected 且 resolved=false 即「退回待处理事项」
	FieldChange *FieldChange `json:"fieldChange,omitempty"`
	Id          int64        `json:"id"`
	KeyResultId int64        `json:"keyResultId"`
	Name        string       `json:"name"`

	// OwnerId 任务负责人
	OwnerId int64 `json:"ownerId"`

	// OwnerName 任务负责人姓名（派生字段）
	OwnerName string `json:"ownerName"`

	// PendingActorId 待行动人（词汇表「待行动人」；派生字段，无待行动人时不返回）
	PendingActorId   *int64  `json:"pendingActorId,omitempty"`
	PendingActorName *string `json:"pendingActorName,omitempty"`

	// PoolReview 任务最近一次入池审批单
	PoolReview *PoolReview `json:"poolReview,omitempty"`

	// Progress 可选进度百分比（词汇表「任务进度」）；未填写时不返回，前端只展示状态
	Progress  *int               `json:"progress,omitempty"`
	StartDate openapi_types.Date `json:"startDate"`

	// Status 任务生命周期状态（词汇表「任务生命周期状态」）；页面主状态汇总，审批原始状态在审批单中
	Status TaskStatus `json:"status"`
}

// TaskDetail 任务详情抽屉数据（AC-31／AC-34）：任务事实、O／KR 归属与全部审核记录
type TaskDetail struct {
	// Deliverables 交付物项列表（含当前内容与候选审核提示，AC-32／AC-33）
	Deliverables []Deliverable `json:"deliverables"`

	// Discussions 任务讨论意见，按时间正序（AC-35／AC-36）
	Discussions []Discussion `json:"discussions"`

	// FieldChanges 关键字段变更单记录，最新在前（词汇表「关键字段变更单」）
	FieldChanges []FieldChange `json:"fieldChanges"`

	// KrDescription 所属 KR 描述（派生字段）
	KrDescription string `json:"krDescription"`

	// ObjectiveTitle 所属 O 标题（派生字段）
	ObjectiveTitle string `json:"objectiveTitle"`

	// PoolReviews 入池审批记录，最新在前（词汇表「审核记录」）
	PoolReviews []PoolReview `json:"poolReviews"`
	Task        Task         `json:"task"`
}

// TaskInvite defines model for TaskInvite.
type TaskInvite struct {
	// CanHandle 当前用户能否响应本邀请（派生字段；受邀人且待处理）
	CanHandle bool `json:"canHandle"`

	// CanRevoke 当前用户能否撤回本邀请（派生字段；邀请人／项目管理员／项目负责人且待处理）
	CanRevoke bool      `json:"canRevoke"`
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`
	InviteeId int64     `json:"inviteeId"`

	// InviteeName 受邀成员姓名（派生字段）
	InviteeName string `json:"inviteeName"`
	InviterId   int64  `json:"inviterId"`

	// InviterName 邀请人姓名（派生字段）
	InviterName string `json:"inviterName"`
	KeyResultId int64  `json:"keyResultId"`

	// Note 邀请说明
	Note *string `json:"note,omitempty"`

	// State 任务创建邀请状态（词汇表「任务创建邀请」）
	State TaskInviteState `json:"state"`
}

// TaskInviteState 任务创建邀请状态（词汇表「任务创建邀请」）
type TaskInviteState string

// TaskStatus 任务生命周期状态（词汇表「任务生命周期状态」）；页面主状态汇总，审批原始状态在审批单中
type TaskStatus string

// UpdateProjectMemberRoleRequest defines model for UpdateProjectMemberRoleRequest.
type UpdateProjectMemberRoleRequest struct {
	// Role 成员角色（项目管理员／普通成员／只读成员），见词汇表「成员角色」
	Role MemberRole `json:"role"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Name             string              `json:"name"`
	OwnerId          int64               `json:"ownerId"`
	PlannedEndDate   *openapi_types.Date `json:"plannedEndDate,omitempty"`
	PlannedStartDate *openapi_types.Date `json:"plannedStartDate,omitempty"`
	Stage            *string             `json:"stage,omitempty"`

	// Status 项目状态（未开始／进行中／已完成／已归档），与自由文本“阶段”正交
	Status ProjectStatus `json:"status"`
}

// UpdateTaskProgressRequest defines model for UpdateTaskProgressRequest.
type UpdateTaskProgressRequest struct {
	// Progress 省略或 null 表示清除进度，回到只展示状态
	Progress *int `json:"progress,omitempty"`
}

// UpdateTaskStatusRequest defines model for UpdateTaskStatusRequest.
type UpdateTaskStatusRequest struct {
	// Reason 取消原因；status 为 cancelled 时必填
	Reason *string `json:"reason,omitempty"`

	// Status 手工流转目标：开始执行（未开始／等待输入 → 进行中）或取消（非终态 → 已取消，需原因）
	Status UpdateTaskStatusRequestStatus `json:"status"`
}

// UpdateTaskStatusRequestStatus 手工流转目标：开始执行（未开始／等待输入 → 进行中）或取消（非终态 → 已取消，需原因）
type UpdateTaskStatusRequestStatus string

// UploadCandidateRequest defines model for UploadCandidateRequest.
type UploadCandidateRequest struct {
	FileName string  `json:"fileName"`
	FileSize *int64  `json:"fileSize,omitempty"`
	FileType *string `json:"fileType,omitempty"`
}

// UploadCandidateResponse defines model for UploadCandidateResponse.
type UploadCandidateResponse struct {
	// File 交付物内容（词汇表「交付物」；当前已生效或候选审核中）
	File DeliverableFile `json:"file"`

	// UploadUrl MinIO 预签名 PUT 地址，客户端直接上传文件内容
	UploadUrl string `json:"uploadUrl"`
}

// UserSummary defines model for UserSummary.
type UserSummary struct {
	DisplayName string `json:"displayName"`
	Id          int64  `json:"id"`
	Username    string `json:"username"`
}

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// AddProjectMemberJSONRequestBody defines body for AddProjectMember for application/json ContentType.
type AddProjectMemberJSONRequestBody = AddProjectMemberRequest

// UpdateProjectMemberRoleJSONRequestBody defines body for UpdateProjectMemberRole for application/json ContentType.
type UpdateProjectMemberRoleJSONRequestBody = UpdateProjectMemberRoleRequest

// CreateOkrBatchJSONRequestBody defines body for CreateOkrBatch for application/json ContentType.
type CreateOkrBatchJSONRequestBody = CreateOkrBatchRequest

// CreateTaskInvitesJSONRequestBody defines body for CreateTaskInvites for application/json ContentType.
type CreateTaskInvitesJSONRequestBody = CreateTaskInvitesRequest

// CreateTaskBatchJSONRequestBody defines body for CreateTaskBatch for application/json ContentType.
type CreateTaskBatchJSONRequestBody = CreateTaskBatchRequest

// CreateDeliverableJSONRequestBody defines body for CreateDeliverable for application/json ContentType.
type CreateDeliverableJSONRequestBody = CreateDeliverableRequest

// UploadCandidateJSONRequestBody defines body for UploadCandidate for application/json ContentType.
type UploadCandidateJSONRequestBody = UploadCandidateRequest

// CreateDiscussionJSONRequestBody defines body for CreateDiscussion for application/json ContentType.
type CreateDiscussionJSONRequestBody = CreateDiscussionRequest

// SubmitFieldChangeJSONRequestBody defines body for SubmitFieldChange for application/json ContentType.
type SubmitFieldChangeJSONRequestBody = SubmitFieldChangeRequest

// DecideFieldChangeJSONRequestBody defines body for DecideFieldChange for application/json ContentType.
type DecideFieldChangeJSONRequestBody = FieldChangeDecisionRequest

// DecideTaskPoolReviewJSONRequestBody defines body for DecideTaskPoolReview for application/json ContentType.
type DecideTaskPoolReviewJSONRequestBody = PoolReviewDecisionRequest

// UpdateTaskProgressJSONRequestBody defines body for UpdateTaskProgress for application/json ContentType.
type UpdateTaskProgressJSONRequestBody = UpdateTaskProgressRequest

// UpdateTaskStatusJSONRequestBody defines body for UpdateTaskStatus for application/json ContentType.
type UpdateTaskStatusJSONRequestBody = UpdateTaskStatusRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login 登录，成功后通过 HttpOnly Cookie 建立会话
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout 退出登录，销毁当前会话
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// GetCurrentUser 当前登录用户
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// GetHealthz 健康检查
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// ListNotifications 当前用户的站内通知（最新在前）
	// (GET /notifications)
	ListNotifications(w http.ResponseWriter, r *http.Request)
	// MarkAllNotificationsRead 将当前用户全部通知标记为已读
	// (POST /notifications/read-all)
	MarkAllNotificationsRead(w http.ResponseWriter, r *http.Request)
	// ListProjects 当前用户可见的项目列表
	// (GET /projects)
	ListProjects(w http.ResponseWriter, r *http.Request)
	// CreateProject 创建项目
	// (POST /projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// GetProject 单个项目详情（项目内页面外壳用）
	// (GET /projects/{projectId})
	GetProject(w http.ResponseWriter, r *http.Request, projectId int64)
	// UpdateProject 更新项目（全量字段）
	// (PUT /projects/{projectId})
	UpdateProject(w http.ResponseWriter, r *http.Request, projectId int64)
	// GetFileDownloadUrl 取得交付物内容的预签名下载地址（全体项目成员可查看／下载当前与候选内容，§3.3）
	// (GET /projects/{projectId}/files/{fileId}/download-url)
	GetFileDownloadUrl(w http.ResponseWriter, r *http.Request, projectId int64, fileId int64)
	// ListProjectMembers 项目成员列表（含成员角色）
	// (GET /projects/{projectId}/members)
	ListProjectMembers(w http.ResponseWriter, r *http.Request, projectId int64)
	// AddProjectMember 将用户加入项目并赋予成员角色（仅项目管理员／项目负责人）
	// (POST /projects/{projectId}/members)
	AddProjectMember(w http.ResponseWriter, r *http.Request, projectId int64)
	// RemoveProjectMember 将成员移出项目（仅项目管理员／项目负责人）
	// (DELETE /projects/{projectId}/members/{userId})
	RemoveProjectMember(w http.ResponseWriter, r *http.Request, projectId int64, userId int64)
	// UpdateProjectMemberRole 调整成员角色（仅项目管理员／项目负责人）
	// (PUT /projects/{projectId}/members/{userId})
	UpdateProjectMemberRole(w http.ResponseWriter, r *http.Request, projectId int64, userId int64)
	// ListObjectives 项目的 O／KR 层级列表（O 含下属 KR，按排序返回）
	// (GET /projects/{projectId}/objectives)
	ListObjectives(w http.ResponseWriter, r *http.Request, projectId int64)
	// CreateOkrBatch 表格式批量创建 O／KR（仅项目管理员／项目负责人；整批一个事务，全部成功或全部失败）
	// (POST /projects/{projectId}/objectives)
	CreateOkrBatch(w http.ResponseWriter, r *http.Request, projectId int64)
	// ListTaskInvites 项目内全部任务创建邀请（含派生动作标志）
	// (GET /projects/{projectId}/task-invites)
	ListTaskInvites(w http.ResponseWriter, r *http.Request, projectId int64)
	// CreateTaskInvites 邀请成员为某个 KR 创建任务（KR 负责人／项目管理员／项目负责人；可多选受邀成员）
	// (POST /projects/{projectId}/task-invites)
	CreateTaskInvites(w http.ResponseWriter, r *http.Request, projectId int64)
	// RevokeTaskInvite 撤回待处理的任务创建邀请（邀请人／项目管理员／项目负责人）
	// (POST /projects/{projectId}/task-invites/{inviteId}/revoke)
	RevokeTaskInvite(w http.ResponseWriter, r *http.Request, projectId int64, inviteId int64)
	// ListTasks 项目全部任务（含派生动作标志与最近一次入池审批单）
	// (GET /projects/{projectId}/tasks)
	ListTasks(w http.ResponseWriter, r *http.Request, projectId int64)
	// CreateTaskBatch 表格式批量创建任务草稿（可选一并提交入池；KR 负责人本人创建免审直接进入未开始，AC-26）
	// (POST /projects/{projectId}/tasks)
	CreateTaskBatch(w http.ResponseWriter, r *http.Request, projectId int64)
	// GetTaskDetail 任务详情（AC-31／AC-34；全体项目成员可查看，操作按钮按派生权限标志出现）
	// (GET /projects/{projectId}/tasks/{taskId})
	GetTaskDetail(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64)
	// CreateDeliverable 为任务新增交付物项（任务负责人／创建人／可编辑项目者；非终态任务）
	// (POST /projects/{projectId}/tasks/{taskId}/deliverables)
	CreateDeliverable(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64)
	// UploadCandidate 登记候选交付物内容并取得预签名上传地址（任务负责人；重复调用覆盖未提交审核的候选）
	// (POST /projects/{projectId}/tasks/{taskId}/deliverables/{deliverableId}/candidate)
	UploadCandidate(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64, deliverableId int64)
	// CreateDiscussion 提交任务讨论意见（全体项目成员含只读；提交后不可编辑或删除；通知任务负责人与被 @ 成员）
	// (POST /projects/{projectId}/tasks/{taskId}/discussions)
	CreateDiscussion(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64)
	// SubmitFieldChange 编辑任务／提交关键字段修改（AC-23；草稿直接完善，KR 负责人本人免审即时生效，其余进入审批且旧值继续生效）
	// (POST /projects/{projectId}/tasks/{taskId}/field-changes)
	SubmitFieldChange(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64)
	// AbandonFieldChange 放弃已退回的本次变更（清除退回待处理事项）
	// (POST /projects/{projectId}/tasks/{taskId}/field-changes/{changeId}/abandon)
	AbandonFieldChange(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64, changeId int64)
	// DecideFieldChange 所属 KR 负责人通过或退回关键字段修改（AC-23；通过后拟议值生效，退回后拟议值作废）
	// (POST /projects/{projectId}/tasks/{taskId}/field-changes/{changeId}/decision)
	DecideFieldChange(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64, changeId int64)
	// DecideTaskPoolReview 所属 KR 负责人通过或退回入池审批（AC-04；管理员不能替代 KR 负责人）
	// (POST /projects/{projectId}/tasks/{taskId}/pool-review-decision)
	DecideTaskPoolReview(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64)
	// UpdateTaskProgress 更新或清除任务的可选进度百分比（AC-12；系统不产生虚构百分比）
	// (PUT /projects/{projectId}/tasks/{taskId}/progress)
	UpdateTaskProgress(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64)
	// SubmitTaskPoolReview 将草稿任务提交所属 KR 负责人入池审批（AC-04；退回后可修改重新提交）
	// (POST /projects/{projectId}/tasks/{taskId}/submit-pool-review)
	SubmitTaskPoolReview(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64)
	// UpdateTaskStatus 手工流转任务状态：开始执行或取消（AC-12；完成走三道审批，不在此端点）
	// (POST /projects/{projectId}/tasks/{taskId}/update-status)
	UpdateTaskStatus(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64)
	// ListUsers 全部用户（用于人员选择）
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNotifications operation middleware
func (siw *ServerInterfaceWrapper) ListNotifications(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNotifications(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkAllNotificationsRead operation middleware
func (siw *ServerInterfaceWrapper) MarkAllNotificationsRead(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkAllNotificationsRead(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFileDownloadUrl operation middleware
func (siw *ServerInterfaceWrapper) GetFileDownloadUrl(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "fileId" -------------
	var fileId int64

	err = runtime.BindStyledParameterWithOptions("simple", "fileId", r.PathValue("fileId"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fileId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFileDownloadUrl(w, r, projectId, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectMembers operation middleware
func (siw *ServerInterfaceWrapper) ListProjectMembers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectMembers(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddProjectMember operation middleware
func (siw *ServerInterfaceWrapper) AddProjectMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddProjectMember(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveProjectMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveProjectMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId int64

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveProjectMember(w, r, projectId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProjectMemberRole operation middleware
func (siw *ServerInterfaceWrapper) UpdateProjectMemberRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId int64

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProjectMemberRole(w, r, projectId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListObjectives operation middleware
func (siw *ServerInterfaceWrapper) ListObjectives(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListObjectives(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOkrBatch operation middleware
func (siw *ServerInterfaceWrapper) CreateOkrBatch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOkrBatch(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTaskInvites operation middleware
func (siw *ServerInterfaceWrapper) ListTaskInvites(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTaskInvites(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTaskInvites operation middleware
func (siw *ServerInterfaceWrapper) CreateTaskInvites(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTaskInvites(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeTaskInvite operation middleware
func (siw *ServerInterfaceWrapper) RevokeTaskInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "inviteId" -------------
	var inviteId int64

	err = runtime.BindStyledParameterWithOptions("simple", "inviteId", r.PathValue("inviteId"), &inviteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "inviteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeTaskInvite(w, r, projectId, inviteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTasks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTasks(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTaskBatch operation middleware
func (siw *ServerInterfaceWrapper) CreateTaskBatch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTaskBatch(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTaskDetail operation middleware
func (siw *ServerInterfaceWrapper) GetTaskDetail(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTaskDetail(w, r, projectId, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDeliverable operation middleware
func (siw *ServerInterfaceWrapper) CreateDeliverable(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDeliverable(w, r, projectId, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadCandidate operation middleware
func (siw *ServerInterfaceWrapper) UploadCandidate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	// ------------- Path parameter "deliverableId" -------------
	var deliverableId int64

	err = runtime.BindStyledParameterWithOptions("simple", "deliverableId", r.PathValue("deliverableId"), &deliverableId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deliverableId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadCandidate(w, r, projectId, taskId, deliverableId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDiscussion operation middleware
func (siw *ServerInterfaceWrapper) CreateDiscussion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDiscussion(w, r, projectId, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitFieldChange operation middleware
func (siw *ServerInterfaceWrapper) SubmitFieldChange(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitFieldChange(w, r, projectId, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AbandonFieldChange operation middleware
func (siw *ServerInterfaceWrapper) AbandonFieldChange(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	// ------------- Path parameter "changeId" -------------
	var changeId int64

	err = runtime.BindStyledParameterWithOptions("simple", "changeId", r.PathValue("changeId"), &changeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "changeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AbandonFieldChange(w, r, projectId, taskId, changeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DecideFieldChange operation middleware
func (siw *ServerInterfaceWrapper) DecideFieldChange(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	// ------------- Path parameter "changeId" -------------
	var changeId int64

	err = runtime.BindStyledParameterWithOptions("simple", "changeId", r.PathValue("changeId"), &changeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "changeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DecideFieldChange(w, r, projectId, taskId, changeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DecideTaskPoolReview operation middleware
func (siw *ServerInterfaceWrapper) DecideTaskPoolReview(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DecideTaskPoolReview(w, r, projectId, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTaskProgress operation middleware
func (siw *ServerInterfaceWrapper) UpdateTaskProgress(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTaskProgress(w, r, projectId, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitTaskPoolReview operation middleware
func (siw *ServerInterfaceWrapper) SubmitTaskPoolReview(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitTaskPoolReview(w, r, projectId, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTaskStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateTaskStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTaskStatus(w, r, projectId, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects", wrapper.ListProjects)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects", wrapper.CreateProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}", wrapper.GetProject)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/projects/{projectId}", wrapper.UpdateProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/members", wrapper.ListProjectMembers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/members", wrapper.AddProjectMember)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/projects/{projectId}/members/{userId}", wrapper.RemoveProjectMember)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/projects/{projectId}/members/{userId}", wrapper.UpdateProjectMemberRole)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/objectives", wrapper.ListObjectives)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/objectives", wrapper.CreateOkrBatch)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/tasks", wrapper.ListTasks)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks", wrapper.CreateTaskBatch)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}/submit-pool-review", wrapper.SubmitTaskPoolReview)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}/pool-review-decision", wrapper.DecideTaskPoolReview)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}", wrapper.GetTaskDetail)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}/update-status", wrapper.UpdateTaskStatus)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}/progress", wrapper.UpdateTaskProgress)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}/field-changes", wrapper.SubmitFieldChange)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}/field-changes/{changeId}/decision", wrapper.DecideFieldChange)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}/field-changes/{changeId}/abandon", wrapper.AbandonFieldChange)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}/deliverables", wrapper.CreateDeliverable)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}/deliverables/{deliverableId}/candidate", wrapper.UploadCandidate)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/files/{fileId}/download-url", wrapper.GetFileDownloadUrl)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}/discussions", wrapper.CreateDiscussion)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/notifications", wrapper.ListNotifications)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/notifications/read-all", wrapper.MarkAllNotificationsRead)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/task-invites", wrapper.ListTaskInvites)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/task-invites", wrapper.CreateTaskInvites)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/task-invites/{inviteId}/revoke", wrapper.RevokeTaskInvite)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users", wrapper.ListUsers)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1tUxPZ1uhfSeXebxcH1Dmn6lp1q67jnDnHmhctnDlf5lpTLWm0jyHN0wl6PBZVUcEkkDedAEKCEAVh",
	"QAIoAyEJUvX8lGPv3Z1P+Qu39kt3dnfvTjpCwPH4SUw6u9de72vttda+7x+Qh4blkBiKhP0X7vsVMTws",
	"h8Ii/s8lOTQYlAYi6O8BORQRQ/hPYXg4KA0IEUkO9f4jLIfQZ+GBW+KQgP76n4o46L/g/x+9zYV7ybfh",
	"3r8oiqz4R0dHe/wBMTygSMNoEf8Fv1pOa+ktWEjov4/BSlab2IXRB+DxG23tgX+0x/+NrNyQAgEx1H1I",
	"wMGvIJHScqswvgdnFuH8I5hY0YtJfXMZTKyqB4VGLU7+gPOP6rNZmEzAeBY8eaavPNUTb0Bh1ReQhwQp",
	"5APbD7XqglqOgvgSKM01agm0lR/kyDfySCjQ/Z0QVKrlFNh4Bgqr6OU/yvL3Quhev/hfI2KYELy7MGiz",
	"VXAwBZa29Z1l+LoIp7b0wxhYmmvUknDuIZzZrc9m69EFBNtPIWEkcktWpH+JJ4AcWFgjsMH4tFqb0zfn",
	"wd4b/TAGCxiYvwtBKYBfSFboPrE29+D2Q/B4HJT2YWGtHp1DwCwW62tJP3qaLoDWvxgIXFXkf4gDke/F",
	"oRuiQqmJvhpW5GFRiUhEfBU5KLYDiC6Bnhzt8Y+EReUyxv6grAwJEf8FvxSK/PlLf48/cm9YJP8Vb4oK",
	"hkkR/2tEUhC1fjZ+2UNeet18Xr6BAEVrX1JEISJ+LQalO6Ii3AiKrnCHhCEM95Dwz+/E0M3ILf+Fs319",
	"Pf4hKWT+33xBOKJIoZsOePAaLcCQwgMj4bAkh1yhYOjNAHKury0kPf4hMYTI+hPGCV7MRuwX677/69Pm",
	"xurFfS1fIvrD3+OXIuJQ2BP2zU8ERRHuOXZvwO6OgG/Fe/1ieCQYuRwaHuHs3gKwHQNtESCGAl8LEdGy",
	"lQD6gIusiCIN8OjteFS+GzL404rQb/t9+s6CvvNSrVQatSQ4HK8Xq/DZpg2/HtAajghKxCPsNqSzILkj",
	"/spt5SshMnDrckQccm5ErSTr0YRajjZqc6C47otIkaCILE5mE5Rf+ZiHG7UEnN4C1YrvClKm8Wn0OHmZ",
	"dEe8HPCB7BOw9wYWEr4rPv3wAEws+r7tb9TicGMJzuz6bhsMEPbpsbdg64lajsL5IrJSPZ554U9cMjWX",
	"Ro+bTN1KDXGZ0sHlPX5mg17lBGHQA3eNtqWYq6Ywd9jBVi1sMIoF6jL59dk2sk1e4s5g1DYcr3a1yJ4H",
	"rA8HhVBIDPylAz1Af3KtAwHE4npTdDClJ+PQ3JI7Ln8UwrePn/ZoVQ907/GHR24MSZFvZKVfvCOJd53q",
	"IqKMiD44s6seziMnL5vW1idB6i3MZNXKEsiO6bE1mIiC7ee+b/uRvQHjy3B7EZSKMLGPtEp6ATyffB9N",
	"0h8w376PpmAyUX9aatQSjVqeVbCw8FqtVEA8D6oVbW5MrVbBRBGsTGrVOBhPgVJRy+/A9LJ+mEcLFtZA",
	"LQpWJpvUuyHLQVEIYeFEmAjdkSIiT6sTJ4iuj19XfxjVN/fArylQycGZXZitgPKrRi1+8dKZvvME0nqx",
	"qpYrIPNEq86yvjza/btxsDSmZR+TZRq1pFrOwcJrmNg3VWC9uE9fuP1craTJkzAZA6U5bW4MoRHs77Lo",
	"wso3CyYWQJY+DTLPEAR7b0AJfeXF7nBF3En/1oxKEBl2Z1X8vcj1SEBmpv4wSgwlNTdLc/VoE6H1+ecg",
	"s6ZvVlmTijGY0h8dkI3rsTWwt00sSCeuTEsZMI2JZ90TkonysDETAXFzBz5LN2rJ+lxGW58Fj8fr0Tlt",
	"YRlFadkk2J7Slir+nnYmzkYuFsQeFs1t6EU9ACuVOnGdxH8OiwMRMcA41ZyNvxiDhQW1sqRWn2mJ30A2",
	"pa1sNWrxejQBiuvIW8JagAgYqO1razMgPkOFaS7Dih/Y3AeVnLlUvbhvxdXZ1u6Adwo6TdS5zkyUzavC",
	"ezh9D9HKKDYrxK7c9KC5LDSiKGIogsILjuMuhYeDwr0fKAodSJK8EgFFdCH+KnZ1hYA3H++xgMCDvyW7",
	"stzVqM0hxbw0p5ajavWAqHMSI6vlNP0wOos4GX+IdPHMopaIw8JrkNlTy2mQfgwybxq1+NX+r33/vfKn",
	"L87zHNwBIRSQApSkrew3A/k3EgmZBwgxPuCXUqfi4KAlNp8fFK5jktGf97gHy3ao3allECCub6bgdkwv",
	"rr6PJs1v30dTjVqe0m/vjZZbgFNxFLMQ4pWKcLGsljd4tBEHB4nHfzHCMVsMR2hzY3Tdmd36zE6jFkcO",
	"SalIUykzuyBeJS+wCO2ZiDTEVa6DUlB0lSL05TXpXxyMgI0ZfeIhnNrypk3QQj/iT48iq+EIZV4xNDKE",
	"EwCUK3sY3r7O2eTIcFAWAmKAINcbYozffGUqGVtqDXtHyEVc+RVkUyjk3Hmn5RbAxgws/U5I4EGhkD0x",
	"dOAyqJnHcdX6pVW9VIFjGX3lgZ09mQcwhyKTZ/jOabWcAplNrTatv3uCWDW+WJ9dcrAnyVl6tmzkcVe2",
	"YnJOzu+w49ARpTzzD01YIbhc01XERragqenyOfWUzac7Lr1lIt+C2CYaWaRxuUe+G0K8/JMS7KfnHk6D",
	"OqIEnSj5XgpdvuKrvxjTNt6BbMr317/86AOFLTAfRZ7VizF9Jd6rlif1gwMv/I5ewYPPzD3bM5MBntgV",
	"KmB2FWQ2kZOem9U3N7XFB/yEWzhMo2abpzj/AmSfmOESWYR4zG23gGFqrs3bzTeSGAxcuiWEeO8G42/r",
	"uRJhJ5B5BvM7IDXFyiuRTkX8B/Z4fWo551PEsBy8Iwb+z6AQDIs+kHr7PpqsR6Mg/9wM9dTKZL2Iolme",
	"0b94QwgFeKqDDRz1Rwcg+wrm3oHaIxQsvi4S+BwykCevRhEveXU5p5YrpjZs1DKmPiFepx4dt3AHExgP",
	"CKGvxQGJR2cnbOR12OdpIs4Gm1odb2YCTE9YLecQpmg+wAUUTDHvOQ6GzF9Lg4M8+Q/grXWkyuhPvnJ3",
	"bMV/ikPDkda5YZK6UA9LMLdPchUg9RbO7JqOg5bb1t5WteoCXIzppS0uQjxrVXlYCnEtE0E4sUm8zSqi",
	"EOZaNAJ4egHkF/m/IwLBS6Vgqcim4bNNxDF7bwjTIG0VS8HpLcKmMD5NGN2NGUxHwyMHXMPPm6msDu2X",
	"+aOv7nm2sMxvfvAevRjOBsU8g0qTsZqS0Ea5IcFtebIUoA+wDpswPKzI5H2GjuM6bAxPdZakMF/aDnok",
	"s06OTU2p5TVWSWtzY5QdEymQTYO9Eqg9bNTiJIei5VbBxoz2+pVafsPz6gfRC7nOM9L/2MFAQUmjlrEc",
	"eWQQtwVF9J9LihQRFUlo1DI0gm7UMjRq5trcHn9QuCFybLla3oDTMfbVbf3VHn9IvPt3ITjCV0VyMOD2",
	"pY0qBA8GaMwvmTe0Idg1u+8/LIYC6F09npnqb6IQRGxkZ1QkFSNhdm35NmcB257or3hgmwc8bQ8cHToc",
	"ZjL64Za/9WGjjZuerMLCAoyvwY0XcGYZFhbswd8RnWbj4NKma2MZkJyGyRhcjDVqSZJn472p88Msjweg",
	"cVuS1kj15cHesnpQ0B8k9Z2XejRZn39Oili0ygqIr9ui4zZg8IM/FhDv8R9WDzcVMRy+NjI0JCj32pmY",
	"q7bHEQtK4dvfiXeIhLf6bb/5IDIXshK5ogRIJq1Nso/HXeRwwyt38UwPywXWqhB2TyykPMn6Tr4puVuc",
	"YSEcvisrVjYzP2ybWGVTgZ0UYTA5QfNlPOCZIhRnWMMUV5mcrZWKWvYxZu4MnC3Vo3MGr2fIKYXx30Sj",
	"ltRXHrBRP7sgiQtMGxwYkkI4iEHg+Hv8dyTxrgXfTZT8IEekQVoD5ASaPVqwJR3Yr0jSwRmZnFIW4LYU",
	"4p/CaQvL2nYVPJ9s1OIBM+PyC80aICPd/BDrBp+2kXAXdER2zypPEYWOdnvE3ALGgfcMwhVDeDs0aFd8",
	"zZMoV/vgnXCdF1w0LTEnPuuURm2UqFmCYccBXIzVXzzzpiabMBkLsu+14IBHqKuyHHQ7RSd5QFiI6oe4",
	"CuZ1kT0JB6kpTkXM0QNYmzWh2YqOjKb3kJee3+GQlw1z9dgamFhF4W88C/Z3SdRLDtTP/dktCPQU1yJv",
	"w3idWq7Q15W2wMEULkTAwbdrJNv0PFt6ASZRr5HnjyHQ7FZOm+7IJFprJv0DxpAOYnByfBapIkXeNvNo",
	"e6aZli+s0cx86i2csYjmh8c9V51Op0OQwPZD/TAPKq/g1BZMlfRXj7X8NKi8ssHNfcaEHmTWMPcXwd4b",
	"skNcebIGMtNwN24W0TRqSbD/FszHQLRGPtE2EnD+kfPU4Y6oCDdFA34OqvfegOI6eDxLl5kbIyuR5VGY",
	"ns/r8ZRayYHxZYrhmUXyK6oOkdim9MMcyD93O7kKioEfhfDtsIvalyNC0PV7G2sxD1uX5rIasQWczLgQ",
	"+ktAinhJmtKDncJr4lE6JDppK+xXy2matTU0q15ZV6sH1oL/Zqm/S1b3eyEk3BSJwxv2BCd2dU046SnM",
	"0yQJ3Jxgg2xSLU+4QtBF99H1mNo1arUhFLFlagr/kTfRbbr6yIhMvtbWJ41Y4OjBqu39Lro9iSiyvkmq",
	"2kh6y823PemqR3siaw5MFOuxpLY6qb14Ahdj2sY7FADF1rTcNpyOwcLrlg6nR6tLpM8wuTxnzVHa0iRC",
	"T9MSNpmxx5RcjpC00ADkkc6LYLraGdFJ6YzZNuFSPtOin8JKBhfeNm2sWYfZqGX0w7xeTOJ6i4xZpkj/",
	"PngKiy9J3KyW0yzn/DtaqD/bhaXf/x2dhxsv1coSY3tDcuQXnCsRSQncL0Y+B8dSOGeLvxGUgVvSHRdz",
	"3M9mcGy7eZmuz/6mbSS0ygquYX8JyuVGLVN/MaZvvEJ/rD8jz3BjfvbnpBZFLae03Da1jrkF8OSA5HMI",
	"wohbDNOrYLNm2aUyJAT9Pf67ghIirsYt6eatXxQpfJu7o2ukgLOZrHXvNmmestk8z8kFvVQC0Vqjlmer",
	"VN9HH+qphLZ6SPeAtRM5x7LX6+b2SRDg+7bfp5YnaUWf4/iLk4ewJ9u5zTCcUKdF70jfEdtFjl4b6CUv",
	"4JA2L0dyiEK46LlZYJ1dpyXRU7PazFSjloAzu+BwnBReEvpRu1JKgukxkNlUyyminTtzzVudTSFHiusr",
	"XRJCAzxp4xwxY0cVsRF1VO3ny4wRz5Bg0/3IO1mff65V41gxtTn+bhW2tzgIN71eW8G7p0Pxtt4bUxXn",
	"yYWrj6e0gxKByVre2HUsXlXkYTksti69cPGNDVJnjHL35uEf4fpWUbAVDOzeeKIgSafjjluv3MbDjWnu",
	"YHxa20iAd+P6u18RM8zstgITq+vOeI4enBuwGk0BDoiJrsYlISxl2+3EFdafhgOk2cctAnRCmt+B01sm",
	"pCRi/RDcYuqo5Q3DuWgBY1AWApfY6tq2rDdb1UtbpC7UWVzqDiqFStuutoVqQAz2u2hzouYMbR5HDhH+",
	"hMru4bw2NduoJY1i4rMucQDfcNpzZcjrgosxEHvc0imnpZzX+D4/xWB6U594aE+lMF8ZTs8G8uWMuMBD",
	"hjHQVHUuxYGsQiO9BSA+g+u14uQP5H5ZWxDeR1MgPmMWCnAh8V5M2DLPTlm9fa69Exdk0KpNPZbCfFhG",
	"/3L3om9bV8SRo2nbeh2d/pLU3cWBiMwFFenvYhJMrJIsgYXLma8Il9vzODOL7DNsXstzDoGFzzWoHLbY",
	"DW95a/bom6eONuvRBFHU2uw7EH8MN3P8Imb8DJstJek/625pJgNk1qjwYVVJfE1pCMU4Rico+V/fUftf",
	"vKYUkIfaKp/QpnHGll1wNNGwOQdWm7q5SIzPwrO1PYzvzPcb+B6sm2/+tRgRpKC78noFH43DiQOwnSD5",
	"ZXI+c/5so5ZB/36JaT5n+JeToPT8ffTBlUYt822/Dxw8BdvP1XIajK/WH62SVgtyDMM51Wrl11oUvani",
	"s+u2rhy2pQNmsjhZlkRgnqPgnrcpeI9dM1zVbx47h72V/+OkLm4PgRsvQSVDMfknCtqfOwGt2XnAgYwx",
	"EWGPxc6EKNh3jcLpLVBYBYmU43SE80OziqDT8lwe4LeVr1vZ02a4ROqxvKl3s8TlR/5JMF3VOBD2aDNM",
	"wWpz1OQJsYxcdIZPqy7ndTp4UX7O8xD0oQNzdvpYsWBjux6rQFvFxU0XkSZibrbgb0IoEPRWkE4atAuv",
	"jUZru+NO2o2bBei0FtnVZe8X78i3Pb0aPl3CNfiuryafk/DGWUxkOxHwBF4Xj1TMXuLOnncpMWB6vDtx",
	"zsiiSodAuB25GOjvBIJu9IC7OSuiF3ElUkKL29s7LE0MWrHDEthKvGZFuu2QhAohKxWtRdksD+ZZR3aq",
	"Avc43vmYqR2dx+5sol/BsPHz/Iy35wKXMyPPhcv5mOkB14u/1+dfqGWaDoDbMRitIg+YFA6kF8DKJJ0y",
	"V1g1qwnU8gazs4AiDCK00x3+gnTtL4rh4VmPPO4KUgQ9I+HJNfYjEGMFxKHKkBiQhIjYXMn4dlAKCcwL",
	"WHSStEXQBaGmf8oMBZNbDNjq9PjLxuGuR1IWOD4PoDn2s1XexAC3UntCCyRqRtziXh3sGoBqhQfa1DKM",
	"T/tCI8GgTy+uaksVWB6vzy4Z6cMkyD8H8a2jxJSjLcEnuHDnZU+pvDzBlE8tV3ymLPnMw5j2xy0sAe3O",
	"6yTYW4a/P9APXmv5Ei76n2Pz2LbTVzYd7fv346c+5jg2AePTBPBGLW7m9/FTZi6yUUvWC1FjY6wmth27",
	"tlAZ3js2bClcVzKw3fIdHs2xvfQddsy3n+llbbZp0Unu2KhbP/CgFPyQORGka/4nL83EV39qNhMnQekF",
	"jO+Z9SdqeUKtLcLpmFrdJTG338u2/SwA3O2HRYUpg/uDzRRB4ikOjChS5N41RALj/Fq+LYkXR0hrk4RQ",
	"TT4yckgX/GGRhPDNyG1Y+la8RyZ0SqFB2Umta8PiwJlBSQlHfCC3qZajYPmJVnkFK9n30Yf/L/RX2ae+",
	"W9Fyqz5ZGJbODMgB8aYY8pESW19YVO6Iig+ml0HmpVpOw9UiLqs3aozQz4bFEPolAoi81/e/zA8HxcjA",
	"LboYKckHyWmTRRq1PP0q8ZtaTsHEJMztY6hIaZC+Mgbis0hVF1bxsLBNs3QtOQ5Kz7X0VqOW1KaS9fkX",
	"IJOqv4qj7b2bhLtxfWcfFl6TrZJ0ojY3xrru+DVmbfYFP0hlQDZJY6u9ZTC+57t49bK/x39HVEjhqr/v",
	"i7Nf9JGCVLw7/wX/+S/6vjiP20UitzANe4WRyK3eoHxTwjp+WCbKB3En7r1ADgFpfvETBhLDka/kwL1j",
	"m9hqaawZtbJpRBkRSdttc2byub6+Y3s3O+jHdbgumT6G0Phl31m3FU0Qey1jdtGPzv3v9j+yzw1mBc5/",
	"4efrPf6woTsoVJaxaHgCi+9vkcjwlVDwnu8SFkIfqFa09UkyfBdPdbgZxlXMSF6vozeYtJfphFI34svY",
	"5baR4UtuVWw9GgWxCtmACTL50AS8novCzQckt9AWPKLMboocyP4qRlgKnh6jsGmSD2QUC77oehhfdFUu",
	"gm7hvtJ/tULQ3+gjXUQO7W7lDoFOgYkiKSZrydPgwTKo7MGXUbiwzGw1fC8cEYfoZkNMR1jYdcvfSeHI",
	"D5Ynj7hzT0lKS7eac3iwAzGk54tk+Y+RYYzJIrb2OGteNsEg2JKxdGK5VxGFwBkhGHTXDt8Lyu2LwaAF",
	"5f2iEPCqL+gciOPAwdZjFg3kPIbggLyEDI3UN6stEUD7oFpz2FXjoZNgLqMa3wtf4fRqd/gKZDb1lQfm",
	"UG36kiYqTcRdx4cHPGaxDNDtkj/BHdLrya84e2wwmBTjmAqc6juyT3Gu/Y/sI/ZtlCUpR0xKPhFZYei9",
	"b7YHjrayNk3SDguKMCRGcBPGzzQ4QE5nMzRgGw6tpOlh0Ny+mPR6F01bC0LSkwx8ePzhhCRasfWPzBst",
	"bBTEI0NYMMz2baT8cX4WLE2Dl29xDVDCVVRHOLS0ZBpPnpzHrxa4qdMTDjdacBOtHTyiWug73/5Hzate",
	"Oue/Y9E8ZKtmVxiy07GM5XjKuy7qHZSCYrj3PvoH/TdAB86doUPl3PTUN1JQZIbTddM75s3A46kTIztF",
	"ElOno1Ey0+DdjK0qFBl8AzYycc+cwwfGV9WDXy19c5lNuLCsFSYbtQx9mER5Zt2KMUf2v1fOG7NiDXpH",
	"SD/i6Elqmx7u6oSdjqrIXJl2qNmd2M7DNHq0TtDPpD1fHrxNSvOjeJtHY1gL6zElU9aZJu6W7ySNGt8j",
	"tt811CWn2O1Ko9Pxiw0O43jHe2/AxCIYX/6obWCfh4yeebXbMbnrW49pFIbRQ928/V3990m1ErfN8FGr",
	"420rbzo3tVRr9d4nPZWjtKJRJAe5VrbuF4fkO6KTsz0kBLSVKk4gfqz0t5OF4J5AbTo1R6LA6du/5mVj",
	"R9R5bUMLpgriBPx+Z+nG6UQALRWgvvUITu184kEA2eSJ6C2zxLO1w3Wl+dhJOFvNwVYeHK0rvlN3srS5",
	"MZ9R8r79EM8zpP7WFR/IrqvlSVK3TGvA009BJcM2gRgUk28rH4vvZb0orKvpSPsVZ13wu46f69hUZaOW",
	"JNSkLjc+UdDmxkApCad2TM44Kpf+IVRXcRUu1kAtAxP79RhtI6YY8KzE8kj7JfbVclQtr6mVSTqcCJ9Z",
	"EIzD+DRtKcGXu/KkyFXloUj6DCl3ba30mGutTkTrMRXwXk4zyHVfp636wONxQglnsS4NN0mZBrm0eDEG",
	"DmeciQ2THB+V8rPTv1v6j3N92mmpwM5YEFcFPgGxSmsFeEyc+kdQf/TGPuy5qeUKXMiq5TV8bx/pujcm",
	"ClgnPmS86ETzVjzrbXktRMmTBuy9L9ErEEd7FbPR5bRjLAOmbgk4aV5guL2LYQ0rU1wZIl1Dn1BSx3qi",
	"gXdnNjI17+y0WoqOOqM+nO3bW/yTs/VeVKyBq9O28oyJdzPrajndYort6Z9meLD23Y91HHf6nqalP944",
	"55hY9Q8b5dCWbzxqh9xiSy5Td1zZm289IZl7gTFpYzenItvEqLXK671PxpK3LE5hRgF02RbSt7gqu1Os",
	"GmEBcM45yLc80k3CX1NIF+J7q2EyQRQkGZRKFCSIVXCN+8d5rGvea9edY10rJ/bapz18GrtvbWHYeRLd",
	"tDHMe07pKNMyOYMfN2KF9/kg06Z/ytSKwOkt8OK5bVyf4yLptlP68mYXn+G6HcF6WGS29z7zP/Sl5Rbj",
	"T0Ka+Utbtt0tfWEfXdet0z9ud+UJ6wq31ke+3iAT+iydiblVn9ld6NPyO2aH4mftYtUuLaYbgv1dUt/G",
	"VLNNqLVFs5rNoXvy9VgKLKX0rUdabpXcOdC8JQHPs0GBAX7XEbWOdczSf4Sj0Jzu1FU/wXzNabkJzBQr",
	"fmYMs9OnXvJLbnfh3RfOCTiy6+SOsbaXheMrgee0hWWb6KrlNHuldruWJy8iigc/nWGGiH/aQuqYq94l",
	"KXWd337CdTl0RBj/+GcGD6eieSHzLis4vWVOzgHZdXOMPFyM0QssPttmq232PPT64qUz586bM53Z+e2N",
	"WpKTWXJM2sdH6bvqwSw7Ll4t5+DMCojWtOqKVt0wnjyK4bZohd775A/0hdC8+PwTDhSM/XatOJpg0a6G",
	"Tl4HGHd2u+qAT/ZkC2+ctvWTkRS2G/rxrCJ6+7lxAKZWJnE43xXRYi9m+yxbHyxbZHhu9y18i3vbPyIb",
	"TwdQ/ifI9/E49M5bPcgQEhifpsqglWEnz4Js2vSaTLtNf818pR4UQGXhaNpkWJaDZ8jgvzOfnAJpI+N4",
	"RB07OrsbYu5+s+ZnKf+kpdxy/c/FS2f6vmzU8sydgin90QHMH6rVl7w7gD5UnJmBip+MCLv3yrBDJrva",
	"JsObZvnxyC9pHP8svx122sP4NPHSm5d2uVx7cfHSmbPnkPjiu6TVckqtrGi5BX12Dj4fYx48iuiSm6DP",
	"MAb5PyWbxrHDpyBDOOvSqDHXmowvo8CNUeSfxcjR5MneBEkvJHPaRhdjaHq0ILNJPOF6LIXkkpLiKNI0",
	"gtX2mebo3E9bkOxDi7tuDK2zkT8iU4inIX82hR24ss0h0tQO0uS9ZZQ0Ox7asIbkIjn99y21nKg/+NWQ",
	"76RaToHCKtxY0tY3tYct0l0j4XbDPn4Kn9SMD3YMsYfSWDpz4PjmyeEia7JqoxbXcqtqJY1U55Nn9WgC",
	"Tv5mxSLB3PVR2+hI6+Thn68jhUEG/xKth4f/+HuFYan3zlk/+pYu6Bi/jh0dc6K6MbOYTJ1EGs4+zvI1",
	"KGzpO69AZo8M51TLaTLAtFGL3xhQ7uFZwrY5rGRLdG08vNO5MjtS7330ATuczbyoHcRjMPWiUYuDpTny",
	"ie/vZ3168hHI71jeYTZFO99j6eBFniAZEVtOw4VlfRMtbtb9EhhIUW7fWcsL5NsKZ206fTJfwkNe4yxV",
	"zQFkzHwBHnhNDxW/HGGCsalqOW2ztylQKhqW9n30AVM+zJgj9xfZ+jPQMvjYydv9HMwrzNYMtzeRQ2+1",
	"nLZN5sSXYxHIz1shZ4+pR6+P/v8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
