//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MemberRole.
const (
	Admin  MemberRole = "admin"
	Member MemberRole = "member"
	Viewer MemberRole = "viewer"
)

// Valid indicates whether the value is a known member of the MemberRole enum.
func (e MemberRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for PoolReviewDecisionRequestDecision.
const (
	PoolReviewDecisionRequestDecisionApproved PoolReviewDecisionRequestDecision = "approved"
	PoolReviewDecisionRequestDecisionRejected PoolReviewDecisionRequestDecision = "rejected"
)

// Valid indicates whether the value is a known member of the PoolReviewDecisionRequestDecision enum.
func (e PoolReviewDecisionRequestDecision) Valid() bool {
	switch e {
	case PoolReviewDecisionRequestDecisionApproved:
		return true
	case PoolReviewDecisionRequestDecisionRejected:
		return true
	default:
		return false
	}
}

// Defines values for PoolReviewStatus.
const (
	PoolReviewStatusApproved PoolReviewStatus = "approved"
	PoolReviewStatusPending  PoolReviewStatus = "pending"
	PoolReviewStatusRejected PoolReviewStatus = "rejected"
)

// Valid indicates whether the value is a known member of the PoolReviewStatus enum.
func (e PoolReviewStatus) Valid() bool {
	switch e {
	case PoolReviewStatusApproved:
		return true
	case PoolReviewStatusPending:
		return true
	case PoolReviewStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for ProjectStatus.
const (
	ProjectStatusArchived   ProjectStatus = "archived"
	ProjectStatusCompleted  ProjectStatus = "completed"
	ProjectStatusInProgress ProjectStatus = "in_progress"
	ProjectStatusNotStarted ProjectStatus = "not_started"
)

// Valid indicates whether the value is a known member of the ProjectStatus enum.
func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusArchived:
		return true
	case ProjectStatusCompleted:
		return true
	case ProjectStatusInProgress:
		return true
	case ProjectStatusNotStarted:
		return true
	default:
		return false
	}
}

// Defines values for RiskLevel.
const (
	HighRisk RiskLevel = "high_risk"
	Normal   RiskLevel = "normal"
	Warning  RiskLevel = "warning"
)

// Valid indicates whether the value is a known member of the RiskLevel enum.
func (e RiskLevel) Valid() bool {
	switch e {
	case HighRisk:
		return true
	case Normal:
		return true
	case Warning:
		return true
	default:
		return false
	}
}

// Defines values for TaskInviteState.
const (
	TaskInviteStateCompleted TaskInviteState = "completed"
	TaskInviteStatePending   TaskInviteState = "pending"
	TaskInviteStateRevoked   TaskInviteState = "revoked"
)

// Valid indicates whether the value is a known member of the TaskInviteState enum.
func (e TaskInviteState) Valid() bool {
	switch e {
	case TaskInviteStateCompleted:
		return true
	case TaskInviteStatePending:
		return true
	case TaskInviteStateRevoked:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusCancelled                 TaskStatus = "cancelled"
	TaskStatusCompleted                 TaskStatus = "completed"
	TaskStatusDraft                     TaskStatus = "draft"
	TaskStatusInProgress                TaskStatus = "in_progress"
	TaskStatusNotStarted                TaskStatus = "not_started"
	TaskStatusPendingFinalReview        TaskStatus = "pending_final_review"
	TaskStatusPendingIntermediateReview TaskStatus = "pending_intermediate_review"
	TaskStatusPendingPoolReview         TaskStatus = "pending_pool_review"
	TaskStatusWaitingInput              TaskStatus = "waiting_input"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusCancelled:
		return true
	case TaskStatusCompleted:
		return true
	case TaskStatusDraft:
		return true
	case TaskStatusInProgress:
		return true
	case TaskStatusNotStarted:
		return true
	case TaskStatusPendingFinalReview:
		return true
	case TaskStatusPendingIntermediateReview:
		return true
	case TaskStatusPendingPoolReview:
		return true
	case TaskStatusWaitingInput:
		return true
	default:
		return false
	}
}

// AddProjectMemberRequest defines model for AddProjectMemberRequest.
type AddProjectMemberRequest struct {
	// Role 成员角色（项目管理员／普通成员／只读成员），见词汇表「成员角色」
	Role   MemberRole `json:"role"`
	UserId int64      `json:"userId"`
}

// CreateKeyResultInput defines model for CreateKeyResultInput.
type CreateKeyResultInput struct {
	Description string              `json:"description"`
	EndDate     *openapi_types.Date `json:"endDate,omitempty"`
	Metric      *string             `json:"metric,omitempty"`

	// OwnerId KR 负责人，必须是项目成员
	OwnerId   *int64              `json:"ownerId,omitempty"`
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
}

// CreateOkrBatchItem 二选一：填 title（可带 description）新建 O，或填 objectiveId 向已有 O 追加 KR（此时 keyResults 至少一条）
type CreateOkrBatchItem struct {
	Description *string                 `json:"description,omitempty"`
	KeyResults  *[]CreateKeyResultInput `json:"keyResults,omitempty"`
	ObjectiveId *int64                  `json:"objectiveId,omitempty"`
	Title       *string                 `json:"title,omitempty"`
}

// CreateOkrBatchRequest defines model for CreateOkrBatchRequest.
type CreateOkrBatchRequest struct {
	Items []CreateOkrBatchItem `json:"items"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Name             string              `json:"name"`
	OwnerId          int64               `json:"ownerId"`
	PlannedEndDate   *openapi_types.Date `json:"plannedEndDate,omitempty"`
	PlannedStartDate *openapi_types.Date `json:"plannedStartDate,omitempty"`
	Stage            *string             `json:"stage,omitempty"`
}

// CreateTaskBatchRequest defines model for CreateTaskBatchRequest.
type CreateTaskBatchRequest struct {
	Items []CreateTaskItem `json:"items"`

	// SubmitForReview true 时保存后立即提交各自所属 KR 的入池审批（原型「提交入池审批」按钮）；KR 负责人本人创建的任务始终免审直接进入未开始
	SubmitForReview bool `json:"submitForReview"`

	// TaskInviteId 通过任务创建邀请响应时携带（AC-03）；须为发给当前用户的待处理邀请，且本批至少一项任务属于邀请指定的 KR 并提交入池，成功后邀请变为已完成
	TaskInviteId *int64 `json:"taskInviteId,omitempty"`
}

// CreateTaskInvitesRequest defines model for CreateTaskInvitesRequest.
type CreateTaskInvitesRequest struct {
	// InviteeIds 受邀成员（可多选；须为非只读项目成员，不能邀请自己）
	InviteeIds  []int64 `json:"inviteeIds"`
	KeyResultId int64   `json:"keyResultId"`

	// Note 邀请说明，随站内通知一同展示
	Note *string `json:"note,omitempty"`
}

// CreateTaskItem defines model for CreateTaskItem.
type CreateTaskItem struct {
	EndDate     openapi_types.Date `json:"endDate"`
	KeyResultId int64              `json:"keyResultId"`
	Name        string             `json:"name"`

	// OwnerId 任务负责人，必须是项目成员
	OwnerId   int64              `json:"ownerId"`
	StartDate openapi_types.Date `json:"startDate"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	DisplayName string `json:"displayName"`
	Id          int64  `json:"id"`
	Username    string `json:"username"`
}

// Error defines model for Error.
type Error struct {
	// Code 机器可读错误码
	Code string `json:"code"`

	// Message 面向用户的错误说明
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// KeyResult defines model for KeyResult.
type KeyResult struct {
	// Description KR 描述
	Description string `json:"description"`

	// EndDate 周期截止日期
	EndDate *openapi_types.Date `json:"endDate,omitempty"`
	Id      int64               `json:"id"`

	// Metric 量化指标，选填
	Metric      *string `json:"metric,omitempty"`
	ObjectiveId int64   `json:"objectiveId"`

	// OwnerId KR 负责人（项目成员，选填；工作职责而非权限级别）
	OwnerId *int64 `json:"ownerId,omitempty"`

	// OwnerName KR 负责人姓名（派生字段）
	OwnerName *string `json:"ownerName,omitempty"`

	// RiskLevel 风险等级（正常／预警／高风险），见词汇表「风险等级」；不由任务生命周期状态自动推导
	RiskLevel RiskLevel `json:"riskLevel"`
	SortOrder int       `json:"sortOrder"`

	// StartDate 周期开始日期
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// MemberRole 成员角色（项目管理员／普通成员／只读成员），见词汇表「成员角色」
type MemberRole string

// Objective defines model for Objective.
type Objective struct {
	// Description O 说明，选填
	Description *string     `json:"description,omitempty"`
	Id          int64       `json:"id"`
	KeyResults  []KeyResult `json:"keyResults"`
	ProjectId   int64       `json:"projectId"`
	SortOrder   int         `json:"sortOrder"`

	// Title O 标题
	Title string `json:"title"`
}

// PoolReview 任务最近一次入池审批单
type PoolReview struct {
	DecidedAt *time.Time `json:"decidedAt,omitempty"`

	// DecidedByName 处理人姓名（派生字段）
	DecidedByName *string `json:"decidedByName,omitempty"`

	// Exempt KR 负责人本人创建免审时由系统自动生成并标记（AC-26）
	Exempt bool `json:"exempt"`

	// Opinion 审批意见；免审时为系统记录的免审原因
	Opinion *string `json:"opinion,omitempty"`

	// Status 入池审批单状态（词汇表「入池审批单」）；未提交即无审批单
	Status      PoolReviewStatus `json:"status"`
	SubmittedAt *time.Time       `json:"submittedAt,omitempty"`

	// SubmittedByName 提交人姓名（派生字段）
	SubmittedByName *string `json:"submittedByName,omitempty"`
}

// PoolReviewDecisionRequest defines model for PoolReviewDecisionRequest.
type PoolReviewDecisionRequest struct {
	Decision PoolReviewDecisionRequestDecision `json:"decision"`
	Opinion  *string                           `json:"opinion,omitempty"`
}

// PoolReviewDecisionRequestDecision defines model for PoolReviewDecisionRequest.Decision.
type PoolReviewDecisionRequestDecision string

// PoolReviewStatus 入池审批单状态（词汇表「入池审批单」）；未提交即无审批单
type PoolReviewStatus string

// Project defines model for Project.
type Project struct {
	// CanEdit 当前用户能否编辑本项目（派生字段，按成员角色与项目负责人身份在 domain 层判定）
	CanEdit bool `json:"canEdit"`

	// CanManageMembers 当前用户能否管理本项目成员和权限（派生字段，同上）
	CanManageMembers bool      `json:"canManageMembers"`
	CreatedAt        time.Time `json:"createdAt"`
	Id               int64     `json:"id"`
	Name             string    `json:"name"`

	// OwnerId 项目负责人（单人；与项目管理员为独立角色）
	OwnerId int64 `json:"ownerId"`

	// OwnerName 项目负责人姓名（派生字段，前端直接展示）
	OwnerName        string              `json:"ownerName"`
	PlannedEndDate   *openapi_types.Date `json:"plannedEndDate,omitempty"`
	PlannedStartDate *openapi_types.Date `json:"plannedStartDate,omitempty"`

	// Stage 业务里程碑标签，自由文本，选填
	Stage *string `json:"stage,omitempty"`

	// Status 项目状态（未开始／进行中／已完成／已归档），与自由文本“阶段”正交
	Status ProjectStatus `json:"status"`
}

// ProjectMember defines model for ProjectMember.
type ProjectMember struct {
	DisplayName string `json:"displayName"`

	// Role 成员角色（项目管理员／普通成员／只读成员），见词汇表「成员角色」
	Role     MemberRole `json:"role"`
	UserId   int64      `json:"userId"`
	Username string     `json:"username"`
}

// ProjectStatus 项目状态（未开始／进行中／已完成／已归档），与自由文本“阶段”正交
type ProjectStatus string

// RiskLevel 风险等级（正常／预警／高风险），见词汇表「风险等级」；不由任务生命周期状态自动推导
type RiskLevel string

// Task defines model for Task.
type Task struct {
	// CanDecidePoolReview 当前用户能否处理本任务的入池审批（派生字段；仅所属 KR 负责人）
	CanDecidePoolReview bool `json:"canDecidePoolReview"`

	// CanSubmitPoolReview 当前用户能否提交本任务入池（派生字段；草稿且为创建人／负责人／可编辑项目者）
	CanSubmitPoolReview bool               `json:"canSubmitPoolReview"`
	EndDate             openapi_types.Date `json:"endDate"`
	Id                  int64              `json:"id"`
	KeyResultId         int64              `json:"keyResultId"`
	Name                string             `json:"name"`

	// OwnerId 任务负责人
	OwnerId int64 `json:"ownerId"`

	// OwnerName 任务负责人姓名（派生字段）
	OwnerName string `json:"ownerName"`

	// PoolReview 任务最近一次入池审批单
	PoolReview *PoolReview        `json:"poolReview,omitempty"`
	StartDate  openapi_types.Date `json:"startDate"`

	// Status 任务生命周期状态（词汇表「任务生命周期状态」）；页面主状态汇总，审批原始状态在审批单中
	Status TaskStatus `json:"status"`
}

// TaskInvite defines model for TaskInvite.
type TaskInvite struct {
	// CanHandle 当前用户能否响应本邀请（派生字段；受邀人且待处理）
	CanHandle bool `json:"canHandle"`

	// CanRevoke 当前用户能否撤回本邀请（派生字段；邀请人／项目管理员／项目负责人且待处理）
	CanRevoke bool      `json:"canRevoke"`
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`
	InviteeId int64     `json:"inviteeId"`

	// InviteeName 受邀成员姓名（派生字段）
	InviteeName string `json:"inviteeName"`
	InviterId   int64  `json:"inviterId"`

	// InviterName 邀请人姓名（派生字段）
	InviterName string `json:"inviterName"`
	KeyResultId int64  `json:"keyResultId"`

	// Note 邀请说明
	Note *string `json:"note,omitempty"`

	// State 任务创建邀请状态（词汇表「任务创建邀请」）
	State TaskInviteState `json:"state"`
}

// TaskInviteState 任务创建邀请状态（词汇表「任务创建邀请」）
type TaskInviteState string

// TaskStatus 任务生命周期状态（词汇表「任务生命周期状态」）；页面主状态汇总，审批原始状态在审批单中
type TaskStatus string

// UpdateProjectMemberRoleRequest defines model for UpdateProjectMemberRoleRequest.
type UpdateProjectMemberRoleRequest struct {
	// Role 成员角色（项目管理员／普通成员／只读成员），见词汇表「成员角色」
	Role MemberRole `json:"role"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Name             string              `json:"name"`
	OwnerId          int64               `json:"ownerId"`
	PlannedEndDate   *openapi_types.Date `json:"plannedEndDate,omitempty"`
	PlannedStartDate *openapi_types.Date `json:"plannedStartDate,omitempty"`
	Stage            *string             `json:"stage,omitempty"`

	// Status 项目状态（未开始／进行中／已完成／已归档），与自由文本“阶段”正交
	Status ProjectStatus `json:"status"`
}

// UserSummary defines model for UserSummary.
type UserSummary struct {
	DisplayName string `json:"displayName"`
	Id          int64  `json:"id"`
	Username    string `json:"username"`
}

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// AddProjectMemberJSONRequestBody defines body for AddProjectMember for application/json ContentType.
type AddProjectMemberJSONRequestBody = AddProjectMemberRequest

// UpdateProjectMemberRoleJSONRequestBody defines body for UpdateProjectMemberRole for application/json ContentType.
type UpdateProjectMemberRoleJSONRequestBody = UpdateProjectMemberRoleRequest

// CreateOkrBatchJSONRequestBody defines body for CreateOkrBatch for application/json ContentType.
type CreateOkrBatchJSONRequestBody = CreateOkrBatchRequest

// CreateTaskInvitesJSONRequestBody defines body for CreateTaskInvites for application/json ContentType.
type CreateTaskInvitesJSONRequestBody = CreateTaskInvitesRequest

// CreateTaskBatchJSONRequestBody defines body for CreateTaskBatch for application/json ContentType.
type CreateTaskBatchJSONRequestBody = CreateTaskBatchRequest

// DecideTaskPoolReviewJSONRequestBody defines body for DecideTaskPoolReview for application/json ContentType.
type DecideTaskPoolReviewJSONRequestBody = PoolReviewDecisionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login 登录，成功后通过 HttpOnly Cookie 建立会话
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout 退出登录，销毁当前会话
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// GetCurrentUser 当前登录用户
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// GetHealthz 健康检查
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// ListProjects 当前用户可见的项目列表
	// (GET /projects)
	ListProjects(w http.ResponseWriter, r *http.Request)
	// CreateProject 创建项目
	// (POST /projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// GetProject 单个项目详情（项目内页面外壳用）
	// (GET /projects/{projectId})
	GetProject(w http.ResponseWriter, r *http.Request, projectId int64)
	// UpdateProject 更新项目（全量字段）
	// (PUT /projects/{projectId})
	UpdateProject(w http.ResponseWriter, r *http.Request, projectId int64)
	// ListProjectMembers 项目成员列表（含成员角色）
	// (GET /projects/{projectId}/members)
	ListProjectMembers(w http.ResponseWriter, r *http.Request, projectId int64)
	// AddProjectMember 将用户加入项目并赋予成员角色（仅项目管理员／项目负责人）
	// (POST /projects/{projectId}/members)
	AddProjectMember(w http.ResponseWriter, r *http.Request, projectId int64)
	// RemoveProjectMember 将成员移出项目（仅项目管理员／项目负责人）
	// (DELETE /projects/{projectId}/members/{userId})
	RemoveProjectMember(w http.ResponseWriter, r *http.Request, projectId int64, userId int64)
	// UpdateProjectMemberRole 调整成员角色（仅项目管理员／项目负责人）
	// (PUT /projects/{projectId}/members/{userId})
	UpdateProjectMemberRole(w http.ResponseWriter, r *http.Request, projectId int64, userId int64)
	// ListObjectives 项目的 O／KR 层级列表（O 含下属 KR，按排序返回）
	// (GET /projects/{projectId}/objectives)
	ListObjectives(w http.ResponseWriter, r *http.Request, projectId int64)
	// CreateOkrBatch 表格式批量创建 O／KR（仅项目管理员／项目负责人；整批一个事务，全部成功或全部失败）
	// (POST /projects/{projectId}/objectives)
	CreateOkrBatch(w http.ResponseWriter, r *http.Request, projectId int64)
	// ListTaskInvites 项目内全部任务创建邀请（含派生动作标志）
	// (GET /projects/{projectId}/task-invites)
	ListTaskInvites(w http.ResponseWriter, r *http.Request, projectId int64)
	// CreateTaskInvites 邀请成员为某个 KR 创建任务（KR 负责人／项目管理员／项目负责人；可多选受邀成员）
	// (POST /projects/{projectId}/task-invites)
	CreateTaskInvites(w http.ResponseWriter, r *http.Request, projectId int64)
	// RevokeTaskInvite 撤回待处理的任务创建邀请（邀请人／项目管理员／项目负责人）
	// (POST /projects/{projectId}/task-invites/{inviteId}/revoke)
	RevokeTaskInvite(w http.ResponseWriter, r *http.Request, projectId int64, inviteId int64)
	// ListTasks 项目全部任务（含派生动作标志与最近一次入池审批单）
	// (GET /projects/{projectId}/tasks)
	ListTasks(w http.ResponseWriter, r *http.Request, projectId int64)
	// CreateTaskBatch 表格式批量创建任务草稿（可选一并提交入池；KR 负责人本人创建免审直接进入未开始，AC-26）
	// (POST /projects/{projectId}/tasks)
	CreateTaskBatch(w http.ResponseWriter, r *http.Request, projectId int64)
	// DecideTaskPoolReview 所属 KR 负责人通过或退回入池审批（AC-04；管理员不能替代 KR 负责人）
	// (POST /projects/{projectId}/tasks/{taskId}/pool-review-decision)
	DecideTaskPoolReview(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64)
	// SubmitTaskPoolReview 将草稿任务提交所属 KR 负责人入池审批（AC-04；退回后可修改重新提交）
	// (POST /projects/{projectId}/tasks/{taskId}/submit-pool-review)
	SubmitTaskPoolReview(w http.ResponseWriter, r *http.Request, projectId int64, taskId int64)
	// ListUsers 全部用户（用于人员选择）
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectMembers operation middleware
func (siw *ServerInterfaceWrapper) ListProjectMembers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectMembers(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddProjectMember operation middleware
func (siw *ServerInterfaceWrapper) AddProjectMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddProjectMember(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveProjectMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveProjectMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId int64

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveProjectMember(w, r, projectId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProjectMemberRole operation middleware
func (siw *ServerInterfaceWrapper) UpdateProjectMemberRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId int64

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProjectMemberRole(w, r, projectId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListObjectives operation middleware
func (siw *ServerInterfaceWrapper) ListObjectives(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListObjectives(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOkrBatch operation middleware
func (siw *ServerInterfaceWrapper) CreateOkrBatch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOkrBatch(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTaskInvites operation middleware
func (siw *ServerInterfaceWrapper) ListTaskInvites(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTaskInvites(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTaskInvites operation middleware
func (siw *ServerInterfaceWrapper) CreateTaskInvites(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTaskInvites(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeTaskInvite operation middleware
func (siw *ServerInterfaceWrapper) RevokeTaskInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "inviteId" -------------
	var inviteId int64

	err = runtime.BindStyledParameterWithOptions("simple", "inviteId", r.PathValue("inviteId"), &inviteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "inviteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeTaskInvite(w, r, projectId, inviteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTasks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTasks(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTaskBatch operation middleware
func (siw *ServerInterfaceWrapper) CreateTaskBatch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTaskBatch(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DecideTaskPoolReview operation middleware
func (siw *ServerInterfaceWrapper) DecideTaskPoolReview(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DecideTaskPoolReview(w, r, projectId, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitTaskPoolReview operation middleware
func (siw *ServerInterfaceWrapper) SubmitTaskPoolReview(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "taskId" -------------
	var taskId int64

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", r.PathValue("taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitTaskPoolReview(w, r, projectId, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects", wrapper.ListProjects)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects", wrapper.CreateProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}", wrapper.GetProject)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/projects/{projectId}", wrapper.UpdateProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/members", wrapper.ListProjectMembers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/members", wrapper.AddProjectMember)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/projects/{projectId}/members/{userId}", wrapper.RemoveProjectMember)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/projects/{projectId}/members/{userId}", wrapper.UpdateProjectMemberRole)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/objectives", wrapper.ListObjectives)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/objectives", wrapper.CreateOkrBatch)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/tasks", wrapper.ListTasks)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks", wrapper.CreateTaskBatch)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}/submit-pool-review", wrapper.SubmitTaskPoolReview)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/tasks/{taskId}/pool-review-decision", wrapper.DecideTaskPoolReview)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/task-invites", wrapper.ListTaskInvites)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/task-invites", wrapper.CreateTaskInvites)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/task-invites/{inviteId}/revoke", wrapper.RevokeTaskInvite)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users", wrapper.ListUsers)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7HxtU9vG2v9X8ej/f3c7haS9z8ydd+nTaSbtoUPa86Z3pqPYG9DBlnwkmR5OhhmTQGyDn0gJJLYJOEBw",
	"eTKkFIxtwnc50a7kV/4K96xWliVZsuWAIe30nR+k3Wuvh9/1sNfuQ8rHBUMcC1hRoG4+pHgghDhWAOqX",
	"zzj2QYDxifizj2NFwKof6VAowPhokeHYgX8IHIt/E3yjIEjjT/+fBw+om9T/G2gNPED+FQa+4HmOpyYn",
	"J72UHwg+ngnhQaiblFROyal9lI8rv02jSkaePUKRKfjkjbw1RU16qS85/j7j9wO2/5TA059hPCkvFFHs",
	"GC2touXHKL6pFBJKaQPOFqXTfKMWIx/Q8uP6iwxKxFEsA+efK5tPlfgbmC96/FyQZlgPPHgkV1ekcgTG",
	"1uFetlGL46X8jRO/5MKsv/8rIayUykm4+xzmi3jy7zjuG5qdGAb/DAOBCLy/NMgvqvD0GVw/UA430E4B",
	"PdtXzqJwPduoJVD2EVo6qr/I1CMrmLbvWTosjnI8829wCcxB+S1CG4otSrWsUlqGx2+UsyjKq8T8nQ4w",
	"fnVCMkL/hVU6RgeP4JMZuHeC8lv1SBYTs1qobyUo/LQ2AB7/lt//Lc/9A/jEb0DwPuA1aeK/QjwXArzI",
	"EPPluQDoRpA2BH5y0kuFBcDfVrn/gOODtEjdpBhW/MsnlJcSJ0KAfAUjgFdp4sE/wwyPpfVD800vmfSe",
	"/jx3HxOKx/6MB7QI7oCJYSCEA+JtNhS2odnElYdUkP7X14AdEUepmzcGB71UkGGb36/rcwgiz7AjeA7A",
	"+j+nRWBagB//YPNsEIg847NMch1P0vYo9xPb5ItZaneGPcrhinK4JlUqjVoCns3UC1X0vFQvnMi5PYIL",
	"lLc7M72UINK86JJ2C+uNJDkzfmiM/5QWfaO3RRBsX4hUSdQjcakcadSysLDtERkxADDSpUuw/NpjeLhR",
	"i6PFfViteIawEccW8eNkMmYc3PZ7YGYeHr9B+bhnyKOcncLZVc+d4UYthnbX0dKRZ6ypAIJHif4K9+el",
	"cgQtFzA6el3rwn/biqk1NH6cEUFQ6Kb+tko5qY9N8zw9oWpAa4GurMNLqRx0oV2TXSXmaN/6CntYqkkN",
	"JlWDuk3evm5dtUXNyCTOCqZhkiO1LB205UcXkzbYnguuhwI0ywL/Fz3ggPbK3R4MUDXXEdCmlN0sVWVB",
	"a0nOvPyOFsYuXvZ4VBdy91JC+H6QEb/k+GEwzoCf2uFC5MPAg5aOpLNlHFxkUvL2HEz+itIZqbIOM9NK",
	"dAvFI/DgpefOsEfOTsOZDXSwCvcKKH6CUSW1Al/OvYsktBcM/76LJFEiXn+616jFG7WcEWBRfkeqVGAs",
	"B6sVOTstVatwtgA35+RqDM4k4V5Bzh2i1IZylsMD5rdgLQI351rSu89xAUCzqnFiTrDjjAjsUJ04X218",
	"dbr6o4hSOoY/J2FlAS0doUwFll83arFbn10b/JhQWi9UpXIFpufl6gtjDIlX/3YGrk/LmSdkmEYtIZUX",
	"UH4HxU90CKwXTrQJD15KlRR5EiWicC8rZ6cxG+HJkZFdKvhm4OwKzGhPw/RzTMHxG7iH/3Ljd2xNvF3+",
	"nRWVMFJwVlX1f3Db3w7qFEwv1R9FiKPU3M16th5pMbS+/BKmt5RS1ehSVQ4mlcenZOFKdAseHxAPopuD",
	"C7DoaAO6M3GNPSxHwMOiTITE0iF6nmrUEvVsWt5+AZ/M1CNZeWUDZweZBDx4Jq9XKG83F2cRl5FEr5HN",
	"XeSlRQBmKfUSOr0Hb9rB/0Zv4G+JV1RbufrYyywCC74bR27FprbCCfM8YMXvBcDbhMSMEArQE3/TWNjG",
	"JMatEHCMztqPYgUCTLz+uNdEgh39epJkptzH+W0sAuUr8EURpkvYqhdeKKWSvDplH6ELguZmLTa1/Apm",
	"5nV8JYMQE+sqMZWm1th2q/kK0AGskdblCCIthjVjCQfxYNyYYQCHCbW37CbS486ueVBb2oHSaeVsn+qc",
	"A1mwdr6I8isotoV2X6GlDZzpervbumvtauVTFmFF0zCxiBJRtBrFABiJw8K23Uy9x9gu87KYxXcQEhq1",
	"HDzekE7zylRCOVxTIon68ktS05ErmzC2TRyKWzKa5ulMCNz8GWaSOBM6fCsvrMDdJbT3G5mkjRc8I4x9",
	"DcZBoFtkN6w/iIGM48Uh3k9ApAvO2ekGiZjc6oYdZhhlaC5xGNdkpNTOLr7mRhjWMZ4I0YLwE8eblUT/",
	"satPMaJgx0dtKhwaHOqT2RFvqKi0Q5+hUqjrpbxXkDNPVNVMoxd79Ui2qalpEvo0v8YbtYSyOaWUkugg",
	"qhSKOIA2DPguklTdDIEm2h9kWBXoMDmUl8KRnInfLZYMNaXWIw4NeVpxjaNZuwaQ90jfWwBqk7OHSELq",
	"Gk26WI+e0Ft5gFaj9VfP3dlHi6bmgMZ5TTyw061vOS7glJORkAjlI8qZWlPZKRjzKph8ZlNf8TF+4L8l",
	"tsU910QmaOsNtFc+nbCHO5Lm9Ih14F8gGBI7Y6cx9yPJHlo6khcO5F+rcnUFJwCzRXlhBZvDyRFajSp7",
	"+yQ9u/EX06yGHJALMaytVhOGoem0sjmFnURzOqlc0abb24enz9S0Fv+Fs9ncqkOVQAsYOilxS6h3yfN6",
	"Bi72Jhz9JSfxkPyxJ/HYBzO60Dor6efAxwgM5wzlfu0BY0xFh0I8Nw7UWjLAYwK/LWgZ5Ndb2qRP2pn4",
	"u7rwLOphtiqyVdWoxYywbHnmXSRJigQov6Xl8Mlf0ZLJNJvLDwHWj6n2umaEVnizCb9p9gs/Y2NZxvqE",
	"8vgUZl7LtUXl7TzK7xCX1KYZCcs2l1ROkSd1C1Uq21L11Lz91dr4sjNAH81+Q7P0CCAeU3BFp+ordToJ",
	"SfBpgsRt7WTDTEIqzzpSoObEPdkY02vG6z6ntTC0UYvB5DP1Q05ntx4rYDCa25G355rBxPljVcv8DhiR",
	"wBLZLpFaGylcOOD6pddirVvKWThbqEcTcnFOfjWPVqPy7lscQUW35IUDtBhF+Z2OgYtL9CbW14RuO6ff",
	"VhZoCcHbQtSWMnp1y7UxElvQMm4H9l5A6Os+YS9lB30T0aH00GF30SwGB93WsVqvDjdqaeUspxQSUnkX",
	"x9vN4qn2+fQpKqyRwFsqp4ya859Ivv78CO399p/IMtpdkyrrBgxnOfFHNdkCpDD3Y4jnRnggqGLmgqEA",
	"IP/QvG+UGXeA9WFjCmhZzVqq/uIXeTcuVzbVnbU1WC43aun6q2ll9zX+sP2cPGObNBhfV11TTion5YUD",
	"EkFiW58/JQkhYRgJr1CqCEs10yr5II2TuZ9oniUua5QZGf0R53m2K/qOFsZsvdTnalTZKbht9wQk1MRx",
	"IaG6bZPBDFs5qTrT2pIwgKyjb7qrRlO9EUWcu05Us1JvpUVJxuXimVRekMpaTKuSkjaQlYbpEnHKGixH",
	"Zpxo7aVy23sydrt/Ds9SxD23A7OM10sOEjKJ2V203mvp2K1HwWbSyZ10qTlbnEtb/dnocmy03GtrkHaQ",
	"29r7sTXqr2jWb5cw25gy2VfL7zT3x6z2QnaJpEpFKi/om2kdTHcYjHNjrqZGT9dh7mWHqcnvxCTbyzWW",
	"kMkVeX2MOfUtoN6ed8jlDVtzvZgSGZTvkQinmLTJ/l4o6MfWnZM5AzfWTKzkrvq4C5NucdDMHaOAzcJr",
	"0tIWRWpGaLSKzqZ8V7StD7dvhtvmve2PkdTXNr81RkK8SpvfMWxwiuucQhZbutof0xPzeuG3+vIrqVwl",
	"v6ODKIpUcbJDMvTUCtyc05pS80U9bZfKu4aV+Xn6AWa7tsIfsU/5kW+iqjkm/IlmRPwMozYcWWPE5ghY",
	"Q/kg8DO0CFojNf99wLC0YQIjO3006wOBgANDvw/5W/06rcD+wvoILRruGLOb6Pizb+jCk0+77Winrcjv",
	"BcDfDQeDND/xO9yBxgwDvjDPiBN3MWua28/cGANuhcleLoPxgvzUDJtuUgIQBLI71dw9CDF3wATp0GXY",
	"B1w75NwNAd+1BwwviB64UJLKEbgxL1deo0rmXeTR/7J/5TzS2015oejh6BBzzcf5wQhgPaQ47REAPw54",
	"D0ptwPSaVE6hYgG+nGtVVfBrIcDiNzFBZF7Pf+k/PgCib1QbTD6owpdzMLEI916h2LG8XWrUctpf8V+k",
	"chLF59DCiUoVKYYom9Mw9gKmtzCIZVLydkkv1iVm4N5LObXfqCXkZ4n68iuYTtZfx/Dy3s6ho5hyeILy",
	"O2SpytkCzL2Us9NGX6xOo+9q3KRgMg0zCS1YOt6AM8eeW9/eprzUOOBJyZca/Oj6R4OklKuujrpJffzR",
	"4Ecfqzts4qgqwwE6LI4OBLgRRq30hjgCEVg71f5rbOFkv5AiCgQE8VPOP3FhHdumvchJs5qKfBioPxjO",
	"TNwYHLywuY1tIY7N9aQLDLPxk8HrTiPqJA6Y2uzxSzf+p/tL1nMDRoOjbv5wz0sJTezQqDK1p6n9dJ6v",
	"RDE0xAYmPJ+pRuiB1Yq8PUea77Hi0COCWv/H9noPz6DLntM6xZ2Ez6k+1CKGT2xC2uM39UgERitkATrJ",
	"5Eed8PpCBJWmSLLQlTwCZiPAhrK/AtEowatTFGPe856KYuKXNp7KL21UWwaNqo00/+7EoK+0R/rIHK2d",
	"x/YQSBLOFkj5rKNOw6kNWDlGaxG0smFYqjAhiCCoLVbb2hUcV/s1I4jfNh8653pd7Y43N4ba9sbbOUES",
	"WRhbUgrFC9QQVTdguqRsTsnZadMkLS7qjLunFmLsbNzUYd4noLftYncF+NcvjAZdYjY2rCZV5wb7G91f",
	"sp59skiWJHeqKO2FaDSGgYd6x8NkJxhoiTZE83QQiOp+4A9a1IajgVbMZuyhMIvGa2Bz997ne33EnA6C",
	"1GpGpdfo8cz7C5K4t84v6UcNLRLEieuWkQy9FQk+mSGZMFxfhGu/ygtFrcRia6phG1macrrLF+fFw4Jt",
	"knrJcWAHbUK5Q7S4f15YGPy4+0utM7i969+FIA9Zqt6gAGeK9WjaVAh0j0UDwVbPQTdn3dx5vUSXre3k",
	"unDcWn32PI77fGhiasRQycCyyWybWx2dQeQy8cE+uLCep+1TfOF0bPdqQoymhtkEGsdv4OwqnNn4oOFk",
	"0EXWql9fcEGRz/4TLaBV2aN5zJMj5bc5qRKztPZK1Zmu20XvjVoDD0mnxCRJcQOAVB/Naj0Mgtw4aNds",
	"F0myvFlVk+QPVf5WsRDeE6p1/3AuCVwmMHltR28dqD8n5nWN0gyl+0sIodr3G64mmOoIgMr+Y/Ts8A8e",
	"T5FFXgpu6cdCOgdcQ63HLiPYah17cBFoDXmuPMiSs9OeoUYtfWdYvVumsqnHW0MemNmWynOkvUlr1009",
	"hZU0qdWbJcaN8R9K7GW+lKCvlR3rdQp9iLsuXuuMVZ9GLUGkqYXc+Qha3Jez03AvgZ4d6ppxXi39XUBX",
	"oYhWa7CWRvETnASqXNI44BrEchj94idSOSKVt6TKHJwtNGoJnFY+LhKOo9gi+UouMLKzIkfIE2lh7Brp",
	"0egMeoYj9JeCeoa2LTeFYXK1wFVDH3wyQyTR3mGipZtkK5JczLUahWdLZmmZxPFBgZ9V/v3CP5urGq4K",
	"AntTQZyQpudhtNIZAC9IU38P8KfdDqJGblK5glYyUnlLvSOENBOrNtKoxcydzmk3mKjfwGG+maODKblC",
	"wIGHjHbdyuQAr3dnXnWO1aSpXwZOOu4M2t7HtMZoU7Y2RFpd/0BFHXNxWF2d3n3buh/I7Cl6aud9f7Xv",
	"7vEvz9e7gdgmr67ayxtcvJNbl8qpDmec20X2AXr7/uc6bfeHXaWnv9g854JU9Xeb5WiHXNQTROTGLHJx",
	"Y9v1YLnO5+dtL0tr1BLGM/MWM+oMeQMP1VvV/JMDIY4LXCN9ydeMJ7yv2t0T+vpl3+TMDFZ402mafhi5",
	"8wn7S66lEvO2D9m1UzCaLeu3U2BbVhvp/9xeskQw7acTtVuAY4v1SARHN+YDjrc+uzb4SaOWM5wJTyqP",
	"T1HuTKqu2Z1yfE9zJtdKXDNY9R/fmMmxOBtjvnxDIqjeqGmHWAhi40DXoA1/2lLbnqB2xpbADjmW225g",
	"DhalmVsmBdMl6WwPLZzUo0m0uN8UhZM1hYVuLSXfC5fVSWI80OEiANN2ti+uAVQN5cmojVpMXihKlRTm",
	"+PzzeiSO5n4xc5Fw7t6kpQnXfIbjh3vYYMkRCoI6YT5A3aQG6BAzMH6dwv9qA1o3tcnFPZrjaZ3+IP27",
	"GGGsjcE7ML+vHL6G6WPS5iyVU6QVvFGL3ffxE+qpDEtHO1mSNrbaBt0+srEH9l1kythNqV/yAWNRlHyF",
	"g7v1LPnF8/frHiXxGOYOTXPoW2/t85j2iXDwTJrtyym0sqGU8OB6dEloIKHf4HXTBNwYbzO2dvFibk9t",
	"l48Zpap3DBp2se3Iax3aVyfHnDCYolROWcwUR6xNA30XmTIEqQZ34DyRpQqgXdubc3l00TCFXgCYvDf5",
	"fwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
