//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MemberRole.
const (
	Admin  MemberRole = "admin"
	Editor MemberRole = "editor"
	Member MemberRole = "member"
	Viewer MemberRole = "viewer"
)

// Valid indicates whether the value is a known member of the MemberRole enum.
func (e MemberRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Editor:
		return true
	case Member:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for ProjectStatus.
const (
	Archived   ProjectStatus = "archived"
	Completed  ProjectStatus = "completed"
	InProgress ProjectStatus = "in_progress"
	NotStarted ProjectStatus = "not_started"
)

// Valid indicates whether the value is a known member of the ProjectStatus enum.
func (e ProjectStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Completed:
		return true
	case InProgress:
		return true
	case NotStarted:
		return true
	default:
		return false
	}
}

// AddProjectMemberRequest defines model for AddProjectMemberRequest.
type AddProjectMemberRequest struct {
	// Role 成员角色（项目管理员／可编辑成员／普通成员／只读成员），见词汇表「成员角色」
	Role   MemberRole `json:"role"`
	UserId int64      `json:"userId"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Name             string              `json:"name"`
	OwnerId          int64               `json:"ownerId"`
	PlannedEndDate   *openapi_types.Date `json:"plannedEndDate,omitempty"`
	PlannedStartDate *openapi_types.Date `json:"plannedStartDate,omitempty"`
	Stage            *string             `json:"stage,omitempty"`
}

// CurrentUser defines model for CurrentUser.
type CurrentUser struct {
	DisplayName string `json:"displayName"`
	Id          int64  `json:"id"`
	Username    string `json:"username"`
}

// Error defines model for Error.
type Error struct {
	// Code 机器可读错误码
	Code string `json:"code"`

	// Message 面向用户的错误说明
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// MemberRole 成员角色（项目管理员／可编辑成员／普通成员／只读成员），见词汇表「成员角色」
type MemberRole string

// Project defines model for Project.
type Project struct {
	// CanEdit 当前用户能否编辑本项目（派生字段，按成员角色与项目负责人身份在 domain 层判定）
	CanEdit bool `json:"canEdit"`

	// CanManageMembers 当前用户能否管理本项目成员和权限（派生字段，同上）
	CanManageMembers bool      `json:"canManageMembers"`
	CreatedAt        time.Time `json:"createdAt"`
	Id               int64     `json:"id"`
	Name             string    `json:"name"`

	// OwnerId 项目负责人（单人；与项目管理员为独立角色）
	OwnerId int64 `json:"ownerId"`

	// OwnerName 项目负责人姓名（派生字段，前端直接展示）
	OwnerName        string              `json:"ownerName"`
	PlannedEndDate   *openapi_types.Date `json:"plannedEndDate,omitempty"`
	PlannedStartDate *openapi_types.Date `json:"plannedStartDate,omitempty"`

	// Stage 业务里程碑标签，自由文本，选填
	Stage *string `json:"stage,omitempty"`

	// Status 项目状态（未开始／进行中／已完成／已归档），与自由文本“阶段”正交
	Status ProjectStatus `json:"status"`
}

// ProjectMember defines model for ProjectMember.
type ProjectMember struct {
	DisplayName string `json:"displayName"`

	// Role 成员角色（项目管理员／可编辑成员／普通成员／只读成员），见词汇表「成员角色」
	Role     MemberRole `json:"role"`
	UserId   int64      `json:"userId"`
	Username string     `json:"username"`
}

// ProjectStatus 项目状态（未开始／进行中／已完成／已归档），与自由文本“阶段”正交
type ProjectStatus string

// UpdateProjectMemberRoleRequest defines model for UpdateProjectMemberRoleRequest.
type UpdateProjectMemberRoleRequest struct {
	// Role 成员角色（项目管理员／可编辑成员／普通成员／只读成员），见词汇表「成员角色」
	Role MemberRole `json:"role"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Name             string              `json:"name"`
	OwnerId          int64               `json:"ownerId"`
	PlannedEndDate   *openapi_types.Date `json:"plannedEndDate,omitempty"`
	PlannedStartDate *openapi_types.Date `json:"plannedStartDate,omitempty"`
	Stage            *string             `json:"stage,omitempty"`

	// Status 项目状态（未开始／进行中／已完成／已归档），与自由文本“阶段”正交
	Status ProjectStatus `json:"status"`
}

// UserSummary defines model for UserSummary.
type UserSummary struct {
	DisplayName string `json:"displayName"`
	Id          int64  `json:"id"`
	Username    string `json:"username"`
}

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// AddProjectMemberJSONRequestBody defines body for AddProjectMember for application/json ContentType.
type AddProjectMemberJSONRequestBody = AddProjectMemberRequest

// UpdateProjectMemberRoleJSONRequestBody defines body for UpdateProjectMemberRole for application/json ContentType.
type UpdateProjectMemberRoleJSONRequestBody = UpdateProjectMemberRoleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login 登录，成功后通过 HttpOnly Cookie 建立会话
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout 退出登录，销毁当前会话
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// GetCurrentUser 当前登录用户
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// GetHealthz 健康检查
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// ListProjects 当前用户可见的项目列表
	// (GET /projects)
	ListProjects(w http.ResponseWriter, r *http.Request)
	// CreateProject 创建项目
	// (POST /projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// UpdateProject 更新项目（全量字段）
	// (PUT /projects/{projectId})
	UpdateProject(w http.ResponseWriter, r *http.Request, projectId int64)
	// ListProjectMembers 项目成员列表（含成员角色）
	// (GET /projects/{projectId}/members)
	ListProjectMembers(w http.ResponseWriter, r *http.Request, projectId int64)
	// AddProjectMember 将用户加入项目并赋予成员角色（仅项目管理员／项目负责人）
	// (POST /projects/{projectId}/members)
	AddProjectMember(w http.ResponseWriter, r *http.Request, projectId int64)
	// RemoveProjectMember 将成员移出项目（仅项目管理员／项目负责人）
	// (DELETE /projects/{projectId}/members/{userId})
	RemoveProjectMember(w http.ResponseWriter, r *http.Request, projectId int64, userId int64)
	// UpdateProjectMemberRole 调整成员角色（仅项目管理员／项目负责人）
	// (PUT /projects/{projectId}/members/{userId})
	UpdateProjectMemberRole(w http.ResponseWriter, r *http.Request, projectId int64, userId int64)
	// ListUsers 全部用户（用于人员选择）
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectMembers operation middleware
func (siw *ServerInterfaceWrapper) ListProjectMembers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectMembers(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddProjectMember operation middleware
func (siw *ServerInterfaceWrapper) AddProjectMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddProjectMember(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveProjectMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveProjectMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId int64

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveProjectMember(w, r, projectId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProjectMemberRole operation middleware
func (siw *ServerInterfaceWrapper) UpdateProjectMemberRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId int64

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId int64

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProjectMemberRole(w, r, projectId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects", wrapper.ListProjects)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects", wrapper.CreateProject)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/projects/{projectId}", wrapper.UpdateProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/members", wrapper.ListProjectMembers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/members", wrapper.AddProjectMember)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/projects/{projectId}/members/{userId}", wrapper.RemoveProjectMember)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/projects/{projectId}/members/{userId}", wrapper.UpdateProjectMemberRole)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users", wrapper.ListUsers)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fpbc9PYHf8qHrVv9eJkoZ1p3ihlF6awZZayLzSzI+yTRLu25JVkqJfxjEMIseNrWAcSxxBMEuLNxU5S",
	"Q4ztwHdZdI7kJ3+FzjlHliVbvrC5sO30TZZ0/ud////OT77PuAWfX+ABL0vM2H1GBJJf4CVAflwS+Akv",
	"55bxtVvgZcCTS9bv93JuVuYE3vWdJPD4nuSeAj4WX/1eBBPMGPM7V1uwiz6VXJdFURCZUCjkZDxAcouc",
	"HwthxhilklSTeygX1V4/RNW0Ov8GhafhowN1a5oJOZkvBPEO5/EA/vQ1gUc/wWhCzRRQ5BA9fYGezaDo",
	"ppaPa6UNOF9QjnLNeoReoGczjeU0ikdRJA0XlrTNx1r0AOYKDo/gYzneAfcfqLVVpRKGkXVYzDbrUWzK",
	"V4L8hRDgPadvCXWlUknA3SWYK+DN/yEI11k++DX4IQAkGvDT1UFdrsGjRbi+r5U30E4eLe5p7+fgerZZ",
	"j6PsA/T0TWM53QivYt1u8WxAnhJE7kdwBs5BuS2qG4o8UepZrfQMHh5o7+dQjijzDevlPGRDKuH0g1U6",
	"RPsP4KNZWHyLcluNcBYr8yLf2Ioz+G1dAJZ/0eO5IQrfAbd8HfjuAFGPJn7kFwU/EGWOlq8oeMEghXQR",
	"+M2QkwlIQLxKvD8hiD5WZsYYjpf/dIFxMnLQD+hPMAlEopMIfghwIo7W7dZKJ9103HhfuIMVxbIviYCV",
	"ga55T5151kd09rH/ugb4SXmKGRsdGXEyPo43fhvCJVnk+EksXLjHD625k/F7WZ4Hnsu856+sDCyLPPiG",
	"zQb6kpsyK8pDL5JkdrLTmj+OdL3Y4UrigrZJtr4MiCLg5VsSELtd6OEkv5cNfqV7sksrblg34Zjy9lI6",
	"VOZw5I3XnRYV7PQ3isqquVvwkM06S7UKlwswVdJKtUZmWSuV1BfTdu72AUnSHW6V0Hj2EqYXaE9Xsw+p",
	"EK1URktJZlA0iE5t2XbWXAGsF4e20xxJZuUAuQJ8wIeFCd+bBPTYUF9lt9E1YZLje5aOn5Wke4Joja5x",
	"c2AJmaPd91WbytfDbmxmp7yp03SH2DRBm/VII/9WXSmqxbyafgQXlpr1FEyV1PoT7d0CfbNZT6HlYiOc",
	"NX7C1JZWqrV+Rpv1uLY5rZUSaH9Oyxc+hOPmLT6EE4zTCArr8XE8/u3hZEEkscaaMk7mLgfuAdEmZE5G",
	"72M2Oczylz2c3G2jGVhoM0cw/Uq3KLdD7W3WI6j8Ts2swt2nqPgaj0grtlAqSfqmVl7VymtKtapVt5Xa",
	"kRVztNGGofYdQfAClsd6u1n+Osuzk4CGQxpKTxIIQ0+qEnwcpwCoW22YjiuV+Z4akDnguSh3tdDPZM5n",
	"20eH7lh8r55nmg8drcHqUAzuEovkYsVwt5GISqWqxnbU7VgrU7GFQ6hFdm/14777w82fYDph49JoQt0u",
	"qStllNyA+4vqetXi3q45dXajrRPHZ+F8vjEXVwsx9eUCejGn7r7DxTi3pWb20ZM5lNtp1uONcBTmt3vI",
	"1XtmP9SiV99N+rLtNOqYouYgGLuYk9FpVK5Nkdj1MwsG+/gpfKrg7GNmt4HceszvPpDOGoYeuU3Pcjil",
	"c1uwHoabsWY9pb1f0fJxpbKLW/fhASzi/qxfHz1G+TXaw5VK0pw5v4RzjaU3qPj6l/AztLumVNdNbZwX",
	"5G8lnMMAG8Px3/pFYVIEEgmz4PN7AX3Ciu4p7i7w2Lb1W35PG6S23X9iELvD9z09a9Hj/2D5xFtEV3fo",
	"g7owyr4Z8PlYMfhfCLaxw4A7IHJy8CZ2TQtpC99z4GKAwlYOVyu91eqcY4wEJAnXsSGR9XN/A0F6eOX4",
	"CaG74G/6gfuzCU6UZAfMlJRKGG4sqNVXqJr+EH7wT/5LwaG821QzBYfA+rnPMLKeBLxDzayiSNohAfEu",
	"EB14wKXWlEoSFfLweaw9+/AyP+DxSqwQ3dfxB+PmBJDdU7owdb8Gn8dg/AksvsSYf7vUrK/oj6I/K5UE",
	"isZQ5i3Rio4sbfMhjCzD1BbMFWA6qW6XDEgVn4XF52pyr1mPq4txfJZIJRqvIti8dzH0JqKV36LcDjVV",
	"e5+BK8/V7EPz/CbbYD9yMu4WDEykYDquo4rDDTh76Lh44yrGm0CUqCdHzo2eGyG1Sq1jxpjz50bOnScg",
	"W54iMXSxAXnK5cVnApKXAm0RODsJNYErnB4ZGJpAQJL/IniCJ0ZmWI4jIWuaymIAkBsmOvHzkZET29t8",
	"Au7JO2GkOk/4nAsjo70kGiq6LAwUXvT5nwcv6qTUzAXHjN0edzJSq3foWmFgTxSD6STleRxXZNn/d94b",
	"dFwiReiAtaq6HaO8FE4cdlIiJxVcr+N4ByP2QkDuG3z8vCsMF2xQ/+FBIxyGc1VqgKEyvWko3siEUWma",
	"HhEGqkeb2SSw0exLIJsj+OkSxXza+ZWJYvGXLo/4S5dq66Apwhn82M9BV/RXTtE5OnNhy48m4Hwe7a7B",
	"SqVvTsPpDVg9RGthtLphMlUKSjLw6cb66SyWelp7jZPkG62XjmkvJwPfsOgAR7w13USRDdp5gqJYGHmq",
	"5QsnmCEkN2CqpG1Oq9mHlk3aXjQcN45RlW2NW2jVU2r0ttTtUA1/9MR0MCJmU8ORFVirHrvZfz54Uedn",
	"gY7IEj1oKO2DaC4G13396qonRFp4wCa6lnMAGf4i6wMyIW5u68ANA4I2bDOEMp3RcZo8PZjeHz+dVLI9",
	"2JwxduiTSmiljJ7sHTeVRs4PXtT+pElWXBi8wvhyeDLZSk01qEc4W2jMpVqEU/Tj8tfla7OJgxp8i1M5",
	"wzavczRDNHud2zxOs//oaFrxlpliJWrg2KS3rQx5tOeMOMv+YD+QOj9PntJM6vUV9NOMpVaG2QynwwM4",
	"/wLObvym28nIECcd498gJzQt9x7pIIi4R0dAb99or2NKNdLxRUipzXZ/FOri7n9l13LdpxxoiB6LvIAy",
	"Vta0/hr4hLugO7OHOFipmzVysPqtxr8zLNT3VGtjPhwrAmfZmJy20tv/TzhmzxuI0kx07xlAqG6O+tOA",
	"qb4NUNubQYvl/3E8RY086b6F87Y/rLolnRWaMhPhQ2Apvbuf3MF5ttCYKVCpzXpEzRSUalKpVuHCUiMc",
	"RbGfrY6knhsPdZAXVu779jguako9084UEL3MGONi/Zzr7iiDn+oCOxu7+u+aWlulX7dMrDnlPXAX6iRU",
	"dmBuTyu/gqlDSg8plSSl0Jr1yB23GCRsdgcTSE3SZRP6qFuymTv4EJ42n0KNT9gwMocSLzGUXM/SO45v",
	"Rh1afAaulC17GOnXvY/+/5mVIqECI2bPq5mCRQr1fWg89J8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
