-- 任务、中间审核组、接收方与接收记录（裁决 #162：无入池审批，任务创建即入池）。
--
-- 状态分布是刻意安排的：
--   · 6、22 已过截止仍在执行  → 任务超期卡点
--   · 14（终审，5 天）、7（关键字段变更，4 天）停在审批环节 → 审批超时卡点（N=3）
--   · 9、13、29、37、45 的必要输入未就绪         → 显示「等待输入」＋上游未就绪卡点
--   · 8 有一张退回未处理的变更单 → 我的工作「待我处理」

INSERT INTO tasks (id, key_result_id, name, owner_id, start_date, end_date, status, created_by,
                   progress, cancel_reason, description, completion_criteria, receiver_scope, created_at, updated_at)
OVERRIDING SYSTEM VALUE VALUES
-- KR1 兼容性评估（已收口）
(1, 1, '盘点三套核心库对象与不兼容项', 3, current_date - 175, current_date - 158, 'completed', 3, 100, '',
 '交易库、资金库、对账库的表、视图、存储过程、触发器全量导出，逐类比对目标库语法支持情况。', '形成对象清单并标注每一项的兼容结论，无「待确认」条目。', 'members',
 now() - interval '178 days', now() - interval '157 days'),
(2, 1, '输出存储过程改造清单与工作量评估', 4, current_date - 168, current_date - 150, 'completed', 3, 100, '',
 '按模块拆分需要重写的存储过程，给出人天估算，供排期使用。', '清单覆盖全部不兼容存储过程，估算经开发组长确认。', 'none',
 now() - interval '170 days', now() - interval '149 days'),
(3, 1, '完成字符集与排序规则差异专项确认', 9, current_date - 160, current_date - 140, 'completed', 9, 100, '',
 '重点确认中文排序、大小写敏感和空串／NULL 处理三处差异对业务的影响。', '', 'none',
 now() - interval '162 days', now() - interval '139 days'),
(4, 1, '组织兼容性评估结论评审', 3, current_date - 145, current_date - 135, 'completed', 3, 100, '',
 '评估结论对齐业务与运维，确认后作为改造排期基线。', '评审通过并形成会议纪要，结论纳入项目基线。', 'all',
 now() - interval '147 days', now() - interval '134 days'),

-- KR2 应用侧适配（进行中，含超期与变更单）
(5, 2, '改造订单模块 SQL 与分页写法', 4, current_date - 140, current_date - 110, 'completed', 4, 100, '',
 '订单模块共 214 处 SQL，重点是分页语法和隐式类型转换。', '改造后订单主流程回归用例全部通过。', 'none',
 now() - interval '142 days', now() - interval '109 days'),
(6, 2, '完成资金模块驱动切换与连接池调优', 4, current_date - 100, current_date - 3, 'in_progress', 4, 65, '',
 '切换 JDBC 驱动后连接池参数需要重新压测确定，目前卡在长事务连接回收。', '资金模块在 200 并发下无连接泄漏，日终批量在 40 分钟内完成。', 'none',
 now() - interval '103 days', now() - interval '2 days'),
(7, 2, '处理批量对账 SQL 的语法不兼容项', 3, current_date - 80, current_date + 6, 'in_progress', 4, 40, '',
 '对账日终脚本里大量使用了原库特有函数，需要逐条改写并保证结果一致。', '改写后连续 5 个工作日对账结果与原库一致。', 'none',
 now() - interval '83 days', now() - interval '4 days'),
(8, 2, '补齐适配后的回归用例并跑通两轮', 6, current_date - 60, current_date + 12, 'in_progress', 4, 55, '',
 '在原有回归集基础上补充国产化差异场景，两轮全量回归留痕。', '回归用例通过率 ≥ 99%，失败项全部有结论。', 'none',
 now() - interval '62 days', now() - interval '1 day'),
(9, 2, '完成第三方报表工具兼容性验证', 13, current_date - 5, current_date + 20, 'not_started', 4, NULL, '',
 '报表工具由集成商提供，需要对方确认驱动版本与函数支持范围。', '', 'none',
 now() - interval '12 days', now() - interval '6 days'),

-- KR3 迁移演练
(10, 3, '编制全量迁移数据校验方案', 9, current_date - 115, current_date - 95, 'completed', 9, 100, '',
 '明确抽样比例、校验字段和差异判定口径。', '方案通过 DBA 与业务双方确认。', 'none',
 now() - interval '117 days', now() - interval '94 days'),
(11, 3, '完成第一轮全量迁移演练', 9, current_date - 90, current_date - 70, 'completed', 9, 100, '',
 '第一轮演练窗口 9 小时 20 分，超出目标，问题集中在索引重建。', '完成全量迁移并出具校验报告。', 'none',
 now() - interval '92 days', now() - interval '69 days'),
(12, 3, '完成第二轮全量迁移演练并压缩窗口', 9, current_date - 20, current_date + 10, 'in_progress', 6, 35, '',
 '目标把窗口压到 6 小时以内，主要手段是并行导入与索引延后重建。', '演练窗口 ≤ 6 小时，数据校验零差异。', 'none',
 now() - interval '24 days', now() - interval '3 days'),
(13, 3, '输出迁移演练问题清单与优化项', 6, current_date + 5, current_date + 18, 'not_started', 9, NULL, '',
 '', '', 'none',
 now() - interval '18 days', now() - interval '18 days'),

-- KR4 割接与回退（两张审批停在路上）
(14, 4, '编制割接实施方案', 9, current_date - 60, current_date + 2, 'pending_final_review', 2, 90, '',
 '含割接时序、人员分工、通信机制与观察指标，需公司级评审前定稿。', '方案覆盖割接全过程，关键节点有明确责任人和时间点。', 'members',
 now() - interval '63 days', now() - interval '5 days'),
(15, 4, '编制回退预案与判定标准', 3, current_date - 55, current_date + 8, 'pending_intermediate_review', 2, 80, '',
 '回退判定要能在 15 分钟内做出决定，避免现场扯皮。', '回退触发条件、决策人和操作步骤明确到分钟级。', 'none',
 now() - interval '58 days', now() - interval '2 days'),
(16, 4, '组织割接方案公司级评审', 2, current_date + 8, current_date + 15, 'not_started', 2, NULL, '',
 '', '', 'none',
 now() - interval '30 days', now() - interval '30 days'),
(17, 4, '完成一次回退演练', 9, current_date + 12, current_date + 22, 'not_started', 2, NULL, '',
 '在演练环境验证回退流程可用，记录耗时。', '回退演练一次成功，耗时 ≤ 90 分钟。', 'none',
 now() - interval '28 days', now() - interval '28 days'),

-- KR5 性能基线
(18, 5, '建立迁移前性能基线', 6, current_date - 78, current_date - 60, 'completed', 6, 100, '',
 '选取 12 个关键交易，连续采集 5 个工作日的响应时间分布。', '形成基线报告，TP50／TP99 数据完整。', 'none',
 now() - interval '80 days', now() - interval '59 days'),
(19, 5, '完成迁移后关键交易性能对比', 6, current_date - 30, current_date + 8, 'in_progress', 6, 45, '',
 '目前已完成 5 个交易的对比，其中账户查询劣化 14%，待优化后复测。', '12 个关键交易 TP99 劣化不超过 10%。', 'none',
 now() - interval '32 days', now() - interval '3 days'),
(20, 5, '输出性能优化建议清单', 4, current_date + 2, current_date + 20, 'not_started', 4, NULL, '',
 '把对比中发现的劣化项按优化手段归类，给出优先级。', '', 'none',
 now() - interval '9 days', now() - interval '3 days'),

-- KR6 运维与安全基线
(21, 6, '制定新库备份恢复策略并完成演练', 9, current_date - 65, current_date + 2, 'in_progress', 11, 70, '',
 '全备＋增备策略已定，恢复演练还差异地恢复一次。', '完成一次全量恢复演练，RTO ≤ 2 小时。', 'none',
 now() - interval '68 days', now() - interval '6 days'),
(22, 6, '配置新库监控告警与巡检脚本', 9, current_date - 50, current_date - 1, 'in_progress', 11, 60, '',
 '监控项已接入 60%，慢查询与锁等待告警还没配。', '核心指标告警覆盖率 100%，巡检脚本每日自动执行。', 'none',
 now() - interval '52 days', now() - interval '4 days'),
(23, 6, '梳理数据库权限与账号基线', 11, current_date - 10, current_date + 14, 'not_started', 9, NULL, '',
 '清理历史遗留的共享账号，按最小权限重新分配。', '账号与权限台账完整，无共享高权限账号。', 'none',
 now() - interval '11 days', now() - interval '6 days'),

-- ── 客户服务中台 ────────────────────────────────────────────────────────────
-- KR7 契约定稿（已完成）
(24, 7, '输出工单域模型与状态机说明', 3, current_date - 95, current_date - 75, 'completed', 3, 100, '',
 '统一工单状态机，把三个系统里不一致的状态收敛成 7 个。', '状态机通过产品与业务确认，无歧义状态。', 'none',
 now() - interval '97 days', now() - interval '74 days'),
(25, 7, '定稿工单与客户信息接口契约', 3, current_date - 80, current_date - 55, 'completed', 3, 100, '',
 '一期共 23 个接口，冻结后变更走版本管理。', '契约评审通过并冻结版本 v1.0。', 'members',
 now() - interval '82 days', now() - interval '54 days'),
(26, 7, '完成历史工单数据结构映射分析', 8, current_date - 70, current_date - 45, 'completed', 3, 100, '',
 '老系统 380 万条工单的字段映射与脏数据分布。', '映射表覆盖全部字段，脏数据处理策略明确。', 'none',
 now() - interval '72 days', now() - interval '44 days'),

-- KR8 中台服务开发
(27, 8, '开发工单受理与流转服务', 4, current_date - 65, current_date + 3, 'in_progress', 4, 75, '',
 '受理、指派、流转、归档四个能力，目前归档还没提测。', '接口全部通过契约测试，联调环境可用率 ≥ 99.5%。', 'none',
 now() - interval '67 days', now() - interval '1 day'),
(28, 8, '开发客户信息聚合查询服务', 4, current_date - 50, current_date + 10, 'in_progress', 4, 50, '',
 '聚合 CRM、计费、工单三个来源，只读不写。', '聚合查询 P95 响应时间 < 300ms。', 'none',
 now() - interval '52 days', now() - interval '2 days'),
(29, 8, '完成中台与呼叫中心系统联调', 6, current_date - 25, current_date + 15, 'in_progress', 4, 30, '',
 '呼叫中心侧的弹屏取数依赖工单受理接口，目前只能用挡板联调。', '联调用例全部通过，无阻塞缺陷。', 'none',
 now() - interval '27 days', now() - interval '2 days'),
(30, 8, '完成接口鉴权与限流策略配置', 11, current_date + 2, current_date + 16, 'not_started', 4, NULL, '',
 '统一走网关鉴权，按坐席工号维度限流。', '', 'none',
 now() - interval '15 days', now() - interval '15 days'),
(31, 8, '完成中台服务压测与容量评估', 6, current_date + 5, current_date + 25, 'not_started', 6, NULL, '',
 '按上线首月 1.5 倍峰值压测，给出扩容建议。', '', 'none',
 now() - interval '6 days', now() - interval '6 days'),

-- KR9 坐席工作台
(32, 9, '输出坐席工作台交互改版方案', 10, current_date - 55, current_date - 38, 'completed', 5, 100, '',
 '把原来分散在四个页签的操作收敛到一屏，减少坐席切换。', '方案通过可用性走查，关键路径步数下降 30%。', 'none',
 now() - interval '57 days', now() - interval '37 days'),
(33, 9, '完成工作台前端组件开发', 5, current_date - 35, current_date + 9, 'in_progress', 5, 60, '',
 '工单列表、详情抽屉、快捷回复三个组件，详情抽屉还在联调。', '组件通过设计走查与前端 Code Review。', 'none',
 now() - interval '37 days', now() - interval '1 day'),
(34, 9, '完成工作台可用性测试与问题修复', 10, current_date + 10, current_date + 25, 'not_started', 5, NULL, '',
 '招募 8 名一线坐席做任务式测试。', '可用性问题全部有处理结论，严重问题清零。', 'none',
 now() - interval '20 days', now() - interval '20 days'),
(35, 9, '完成前端埋点与体验指标接入', 5, current_date - 20, current_date + 5, 'cancelled', 5, 20,
 '一期不单独做埋点，随二期统一埋点方案一起实施，避免重复改造。',
 '', '', 'none',
 now() - interval '24 days', now() - interval '11 days'),

-- KR10 UAT
(36, 10, '编制 UAT 用例与验收标准', 12, current_date - 28, current_date + 1, 'in_progress', 12, 80, '',
 '三类场景共 96 条用例，验收标准与业务部门对齐。', '用例评审通过，验收标准业务部门签字。', 'none',
 now() - interval '30 days', now() - interval '1 day'),
(37, 10, '组织售后场景 UAT', 12, current_date + 5, current_date + 20, 'not_started', 12, NULL, '',
 '售后换货、退货、上门三个子场景。', '场景用例通过率 100%，无阻塞缺陷。', 'none',
 now() - interval '22 days', now() - interval '22 days'),
(38, 10, '组织投诉场景 UAT', 14, current_date + 8, current_date + 22, 'not_started', 12, NULL, '',
 '', '', 'none',
 now() - interval '22 days', now() - interval '22 days'),
(39, 10, '汇总 UAT 问题并跟踪闭环', 12, current_date + 18, current_date + 35, 'not_started', 12, NULL, '',
 'UAT 问题按严重程度分级，阻塞与严重问题必须上线前闭环。', '', 'none',
 now() - interval '20 days', now() - interval '20 days'),

-- KR11 培训与运营
(40, 11, '编制坐席操作手册', 14, current_date - 12, current_date + 18, 'in_progress', 14, 45, '',
 '按新工作台的操作路径重写，配截图。', '手册覆盖全部一线操作场景，业务主管验收通过。', 'none',
 now() - interval '14 days', now() - interval '3 days'),
(41, 11, '组织两轮坐席集中培训', 14, current_date + 20, current_date + 40, 'not_started', 14, NULL, '',
 '分两批，每批 60 人，含实操考核。', '培训覆盖 120 名坐席，考核通过率 ≥ 95%。', 'none',
 now() - interval '16 days', now() - interval '16 days'),
(42, 11, '建立上线后运营值班与反馈机制', 12, current_date + 25, current_date + 45, 'not_started', 12, NULL, '',
 '上线首月双人值班，问题按 30 分钟响应。', '', 'none',
 now() - interval '5 days', now() - interval '5 days'),

-- KR12 数据看板
(43, 12, '梳理客服核心指标口径', 8, current_date - 42, current_date - 25, 'completed', 8, 100, '',
 '18 个核心指标，重点解决「首次解决率」三个部门三种算法的问题。', '指标口径文档通过业务与数据双方确认。', 'all',
 now() - interval '44 days', now() - interval '24 days'),
(44, 12, '完成服务质量看板开发', 8, current_date - 22, current_date + 12, 'in_progress', 8, 55, '',
 '看板分管理视角与班组视角两套，数据日更。', '看板上线且数据与源系统核对一致。', 'none',
 now() - interval '25 days', now() - interval '2 days'),
(45, 12, '完成看板数据校验与试运行', 8, current_date + 12, current_date + 28, 'not_started', 8, NULL, '',
 '连续两周与人工报表比对，差异率控制在 1% 以内。', '', 'none',
 now() - interval '18 days', now() - interval '18 days'),

-- ── 智能客服知识库试点 ──────────────────────────────────────────────────────
(46, 13, '制定知识条目分类与撰写规范', 12, current_date - 46, current_date - 32, 'completed', 12, 100, '',
 '分类树三层，撰写规范明确到标题、摘要、正文结构。', '规范经两名资深坐席试写验证可执行。', 'members',
 now() - interval '48 days', now() - interval '31 days'),
(47, 13, '完成首批 500 条知识入库与审校', 14, current_date - 30, current_date + 4, 'in_progress', 12, 62, '',
 '已入库 312 条，审校返工主要集中在摘要过长。', '500 条全部通过审校，返工率 < 10%。', 'none',
 now() - interval '32 days', now() - interval '1 day'),
(48, 13, '建立知识条目更新与下线流程', 14, current_date - 6, current_date + 18, 'not_started', 14, NULL, '',
 '知识条目要有责任人和复核周期，过期自动提醒。', '', 'none',
 now() - interval '7 days', now() - interval '1 day'),
(49, 14, '搭建检索评测集与评分口径', 8, current_date - 33, current_date - 20, 'completed', 8, 100, '',
 '从真实坐席提问里抽取 300 条构造评测集。', '评测集与评分口径经产品确认。', 'none',
 now() - interval '35 days', now() - interval '19 days'),
(50, 14, '完成两轮检索效果评测', 8, current_date - 18, current_date + 6, 'in_progress', 8, 40, '',
 '第一轮 Top3 命中率 76%，问题集中在同义词和口语化提问。', 'Top3 命中率 ≥ 85%。', 'none',
 now() - interval '20 days', now() - interval '4 days'),
(51, 14, '优化召回策略并复测', 8, current_date + 6, current_date + 22, 'not_started', 8, NULL, '',
 '', '', 'none',
 now() - interval '14 days', now() - interval '14 days'),
(52, 15, '完成两条业务线试运行部署', 5, current_date - 8, current_date + 16, 'in_progress', 7, 25, '',
 '售后线已部署，投诉线等工作台联调完成后再上。', '两条业务线均可在坐席工作台内调用知识库。', 'none',
 now() - interval '10 days', now() - interval '2 days'),
(53, 15, '收集坐席使用反馈与问题记录', 14, current_date + 10, current_date + 30, 'not_started', 7, NULL, '',
 '每周一次班组访谈，配合工作台内反馈入口。', '', 'none',
 now() - interval '12 days', now() - interval '12 days'),
(54, 16, '输出试点效果对比分析', 8, current_date + 30, current_date + 45, 'not_started', 7, NULL, '',
 '对比试点班组与对照班组的平均通话时长和一次解决率。', '', 'none',
 now() - interval '10 days', now() - interval '10 days'),
(55, 16, '编制试点评估报告与推广建议', 14, current_date + 38, current_date + 58, 'not_started', 14, NULL, '',
 '', '', 'none',
 now() - interval '4 days', now() - interval '4 days'),

-- ── 等保 2.0 三级测评整改（已收尾）────────────────────────────────────────────
(56, 17, '完成主机与数据库安全加固', 9, current_date - 215, current_date - 190, 'completed', 11, 100, '',
 '按加固基线逐项核对，共处理 23 项高危配置。', '加固项全部完成并通过复扫。', 'none',
 now() - interval '218 days', now() - interval '189 days'),
(57, 17, '完成应用系统身份鉴别与审计整改', 4, current_date - 205, current_date - 170, 'completed', 11, 100, '',
 '涉及 6 个业务系统的口令策略、双因素与操作审计。', '身份鉴别与审计要求全部满足测评要求。', 'none',
 now() - interval '208 days', now() - interval '169 days'),
(58, 17, '组织整改复测并出具结论', 11, current_date - 160, current_date - 140, 'completed', 11, 100, '',
 '测评机构复测，46 项问题全部闭环。', '复测结论无遗留高危项。', 'all',
 now() - interval '162 days', now() - interval '139 days'),
(59, 18, '补齐日志审计设备并接入核心系统', 9, current_date - 210, current_date - 175, 'completed', 9, 100, '',
 '新增日志审计设备一台，接入 12 个核心系统。', '核心系统日志接入率 100%，留存 6 个月。', 'none',
 now() - interval '212 days', now() - interval '174 days'),
(60, 18, '完成堡垒机运维审计上线', 13, current_date - 195, current_date - 160, 'completed', 9, 100, '',
 '所有运维操作强制经堡垒机，历史直连通道关闭。', '运维直连通道清零，操作录像可回溯。', 'none',
 now() - interval '198 days', now() - interval '159 days'),
(61, 19, '建立季度安全自查清单与责任分工', 11, current_date - 180, current_date - 150, 'completed', 11, 100, '',
 '自查清单 58 项，明确到岗位。', '清单与责任分工经中心办公会通过。', 'none',
 now() - interval '182 days', now() - interval '149 days'),
(62, 19, '完成首次季度自查与问题闭环', 11, current_date - 150, current_date - 120, 'completed', 11, 100, '',
 '首次自查发现 11 个问题，全部闭环。', '自查问题闭环率 100%。', 'none',
 now() - interval '152 days', now() - interval '119 days');

-- ── 中间审核组 ────────────────────────────────────────────────────────────────
INSERT INTO task_reviewers (task_id, user_id) VALUES
    (14, 3), (14, 11),   -- 割接方案：架构与安全把关（已随完成申请快照）
    (15, 11), (15, 6),
    (27, 3), (27, 6),
    (29, 3),
    (36, 7),
    (44, 7),
    (47, 12);

-- ── 接收方与接收记录 ──────────────────────────────────────────────────────────
INSERT INTO task_receivers (task_id, user_id) VALUES
    (1, 2), (1, 4),
    (14, 2), (14, 11), (14, 13),
    (25, 4), (25, 5), (25, 6),
    (46, 7), (46, 14);

-- 终审通过时按当时接收方名单生成；confirmed_at 为空即「待我接收」。
INSERT INTO task_receipts (id, task_id, user_id, generated_at, confirmed_at)
OVERRIDING SYSTEM VALUE VALUES
(1,  1,  2,  now() - interval '157 days', now() - interval '156 days'),
(2,  1,  4,  now() - interval '157 days', now() - interval '155 days'),
-- 4 号任务接收方为全体项目成员
(3,  4,  1,  now() - interval '134 days', now() - interval '133 days'),
(4,  4,  2,  now() - interval '134 days', now() - interval '134 days'),
(5,  4,  3,  now() - interval '134 days', now() - interval '134 days'),
(6,  4,  4,  now() - interval '134 days', now() - interval '132 days'),
(7,  4,  5,  now() - interval '134 days', NULL),
(8,  4,  6,  now() - interval '134 days', now() - interval '131 days'),
(9,  4,  9,  now() - interval '134 days', now() - interval '133 days'),
(10, 4,  11, now() - interval '134 days', now() - interval '130 days'),
(11, 4,  13, now() - interval '134 days', NULL),
(12, 4,  15, now() - interval '134 days', now() - interval '128 days'),
(13, 25, 4,  now() - interval '54 days',  now() - interval '54 days'),
(14, 25, 5,  now() - interval '54 days',  now() - interval '53 days'),
(15, 25, 6,  now() - interval '54 days',  NULL),
-- 43 号任务接收方为全体项目成员（客服中台）
(16, 43, 1,  now() - interval '24 days',  now() - interval '23 days'),
(17, 43, 2,  now() - interval '24 days',  now() - interval '24 days'),
(18, 43, 3,  now() - interval '24 days',  now() - interval '22 days'),
(19, 43, 4,  now() - interval '24 days',  NULL),
(20, 43, 5,  now() - interval '24 days',  now() - interval '21 days'),
(21, 43, 6,  now() - interval '24 days',  NULL),
(22, 43, 7,  now() - interval '24 days',  now() - interval '24 days'),
(23, 43, 8,  now() - interval '24 days',  now() - interval '24 days'),
(24, 43, 10, now() - interval '24 days',  now() - interval '20 days'),
(25, 43, 11, now() - interval '24 days',  NULL),
(26, 43, 12, now() - interval '24 days',  now() - interval '23 days'),
(27, 43, 14, now() - interval '24 days',  now() - interval '19 days'),
(28, 46, 7,  now() - interval '31 days',  now() - interval '31 days'),
(29, 46, 14, now() - interval '31 days',  now() - interval '30 days'),
-- 58 号任务接收方为全体项目成员（等保整改，早已确认完）
(30, 58, 1,  now() - interval '139 days', now() - interval '138 days'),
(31, 58, 3,  now() - interval '139 days', now() - interval '138 days'),
(32, 58, 4,  now() - interval '139 days', now() - interval '137 days'),
(33, 58, 9,  now() - interval '139 days', now() - interval '139 days'),
(34, 58, 11, now() - interval '139 days', now() - interval '139 days'),
(35, 58, 13, now() - interval '139 days', now() - interval '136 days'),
(36, 58, 15, now() - interval '139 days', now() - interval '135 days');
